### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by mbid** [proginosko/LeechBlockNG#1]
Hi proginosko, I really like (and depend) on LeechBlock and would hate to see it gone. Are you still working on the port? I have a few spare days and some experience with web extensions; I could look into the porting efforts.

**Comment by proginosko** [comment]
Thanks for the offer! Yes, I'm still working on the port, but it's turning out to be a slow and frustrating process due to the quirks and limitations of WebExtensions. I'm nowhere near ready to upload a basic working version here. If/when that happens, feel free to chip in.

**Comment by mbid** [comment]
Hi there, I've actually also started working on it, see https://github.com/proginosko/LeechBlock/pull/19. Maybe you could also upload what you've got so far, so that we can merge things?

**Comment by proginosko** [comment]
This is great! I really appreciate your work here. However, I'm basically rewriting LB from the bottom up for WebExtensions with a new options interface, etc. I'm not planning to develop the original LB project any further. So my recommendation would be that you fork the original LB (in fact, I see you have already) and if you can convert it to use WebExtensions then more power to you! It's open source, so have at it.

**Comment by mbid** [comment]
Thanks for the feedback. I'm a little confused however -- are you saying you are going to change the way LeechBlock works, or just rewrite it using a different API (and a different settings page, given that the original one uses XUL, afaik)? Because the fork is essentially a complete rewrite. Only a few assets and styles are the same as in the original, the scripts are all new.

**Comment by proginosko** [comment]
It will be a near-complete rewrite (obviously I'll reuse code where I can) and I'll aim for it to have the same functionality as the current (legacy) version.
