### ISSUE TITLE
Block only first accessed page of site when delaying page is used doesn't work if opened in a new tab

### ISSUE THREAD

**Issue by kr094** [proginosko/LeechBlockNG#101]
It works as advertised if you stay in the tab. I expected it to work across tabs as well. Is this something you would consider?

To reproduce:
Block old.reddit.com
Open it, see block page and wait for countdown
Middle click any link
Blocked in new tab.

**Comment by proginosko** [comment]
Yes, this is doable and makes intuitive sense. I'll work on it.
