### ISSUE TITLE
Delay timer not counting down (Firefox Nightly)

### ISSUE THREAD

**Issue by zttr23** [proginosko/LeechBlockNG#103]
After switching over to Firefox Nightly, the timer on the delay page just stopped working. After a bit, before the timer can count down even a second, it gets crossed out as if I had changed page
I'm pretty sure it has the same settings as normal Firefox did

**Comment by aprokop** [comment]
I'm experiencing the same issue on Mac Firefox 78.0.2. If I stay on the delayed page, it works normally. But often, when I switch to a different tab, and come back, it is stopped.

**Comment by proginosko** [comment]
That's by design.

**Comment by aprokop** [comment]
@proginosko I'm starting to figure it out. I found no documentation stating that though, and the only way I can see that is by looking through the code. I don't understand the motivation, and ways to change that behavior. Could you please point me to some info related to this?

**Comment by proginosko** [comment]
Sure, happy to explain. The delay is meant to be a disincentive to visiting a site. Having to wait for the delay time is the 'cost' of visiting the site, so if you can simply switch to another tab during the delay time, the cost is all but negated. Does that make sense?

If I recall, this was actually a requested feature earlier on, when I first introduced the delaying page.

**Comment by aprokop** [comment]
> Having to wait for the delay time is the 'cost' of visiting the site, so if you can simply switch to another tab during the delay time, the cost is all but negated. Does that make sense?

Thank you for the explanation. It seems that the feature is oriented towards relatively short delays (maybe < 30s). I was thinking of using it in a slightly different way, setting the delay around 5+min, hoping that delay discounting would work its magic in that period of time. It's fine, though.
