### ISSUE TITLE
malformed options page in Mobile

### ISSUE THREAD

**Issue by jpassaro** [proginosko/LeechBlockNG#104]
In Firefox for Android, the options page is too big for the screen. (Will attach a screenshot later.) Some options are off the screen with only the label visible (e.g. Sunday checkbox in block set), there may be for all I know options that I can't even find.

Hoped I could work around it but I think I may be missing some options related to override.

Thanks in advance for any assistance! Great app!

**Comment by proginosko** [comment]
Have you tried viewing the page in landscape orientation?

**Comment by dbogdanov** [comment]
Same issue here. Landscape orientation works normally.


![ae3a3957-24aa-4a57-aa07-810f4d7d7d31](https://user-images.githubusercontent.com/409668/57028534-a2b4ad00-6c3f-11e9-9649-f75231c2076f.jpeg)

**Comment by jpassaro** [comment]
Landscape seems to work correctly.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.7.
