### ISSUE TITLE
Blocked on Firefox

### ISSUE THREAD

**Issue by christinah83** [proginosko/LeechBlockNG#105]
I've been using LeechBlock for a few weeks now and this evening around 8PM it randomly shut off. It says that it's not verified through Firefox. I went to go re-download it and add it back on as an extension and it says "Download failed". Then it gives me the option to look for an "alternative" extension that does the same thing. Of course, nothing listed was even similar. On the left hand side of my screen it says "Unsupported" as a menu option and if I click on it, LeechBlock has now been moved to that section where you can chose to remove the extension (I did this and tried to re-install and it failed) or find a new one. What's going on? Thanks!

**Comment by proginosko** [comment]
Apparently it's a temporary problem with Firefox that just blew up everyone's extensions:

https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by christinah83** [comment]
Thank you! I just saw that on Reddit while I was trying to figure out how to "fix" this and hundreds of comments have rolled in the past few hours. Let me tell you, I'm not good at anything computer-wise, except wasting time on the Internet, so now I feel better. :)

**Comment by proginosko** [comment]
Mozilla just pushed out a new version of Firefox (66.0.4) which is supposed to fix the issue. Go to Help > About Firefox to trigger the update.

**Comment by kirstymca** [comment]
All my extensions stopped working yesterday, and I had similar issues as the original poster with Leechblock. 

The extension icons appeared again today, but they seem to have issues. In the case of Leechblock, it's not blocking anything, and when I click 'options' I get an error message that says "Error: Unable to retrieve options from browser storage." It also has disappeared from the Tools menu.

I checked, and I do have 66.0.4

**Comment by proginosko** [comment]
> All my extensions stopped working yesterday, and I had similar issues as the original poster with Leechblock.

Sorry to hear this. I don't have an explanation for this error right now. My immediate suggestion would be to uninstall and reinstall LB. Unfortunately, you will lose your settings in the process. If you can't afford to lose your settings, you might be able to locate an archived copy of them in your Firefox profile. You would need to recover this _before_ you uninstall LB.

1. Go to **about:support** in your browser and click Open Folder next to Profile Folder.
2. Navigate to **browser-extension-data** and then to **leechblockng@proginosko.com**.
3. Make copies of any files you find in there (storage.js or storage.js.migrated) and put them somewhere else on your drive.

If you're able to do this, I may be able to help you restore your settings after reinstalling LB (assuming that fixes the problem you describe above).

**Comment by kirstymca** [comment]
Thanks!
I've done as you said, and it's working now.
I have also been able to copy my settings - it would be great if I could replace them instead of having to remember exactly what I had before.
Leechblock is so helpful - I need my artificial willpower :-)

**Comment by proginosko** [comment]
Okay, good. Email the file to me (leechblockng@proginosko.com) and I'll try to convert it to a format you can import back in to LB.
