### ISSUE TITLE
Timer box is huge at any position except top left

### ISSUE THREAD

**Issue by khanc** [proginosko/LeechBlockNG#106]
From this morning, the top left corner of timer box is always at top left corner of window. So the timer only works as expected when its position is top left. At top right it will appear stretched at the top of the window. At bottom right it will cover the whole window.

**Comment by metronidazole** [comment]
Confirmed on Firefox. This is a showstopper bug with version 1.0 that was released today. Did you not test it before releasing?

**Comment by proginosko** [comment]
I'm on it. Fix coming soon.

**Comment by proginosko** [comment]
Fixed in version 1.0.1, just uploaded. Go to about:addons and select "Check for Updates" from the settings (cog) menu to trigger the update.

Sorry about that bug!
