### ISSUE TITLE
Disable Firefox option to start without addons when holding SHIFT during firefox startup

### ISSUE THREAD

**Issue by sneijder** [proginosko/LeechBlockNG#107]
Dear procrastination killer team,

is there any way to disable the firefox option to allow firefox to start without addons when holding SHIFT during firefox startup?

And is there any great tool like LeechBlock for IE?

cheers,
Andreas

**Comment by proginosko** [comment]
See workarounds here: https://www.proginosko.com/leechblock/faq/disable-safe-mode/
