### ISSUE TITLE
days field lost on importing configuration file

### ISSUE THREAD

**Issue by matkoniecz** [proginosko/LeechBlockNG#108]
Version: 1.0.1

I made a test config (with the first set enabled on all days), exported it with intention of importing ( https://gist.github.com/matkoniecz/c83cc74b38d50b6310ca569a23915cd8#file-1_imported-ini )

Then I imported it, inspected ("days of week" checkboxes were gone), and exported again (https://gist.github.com/matkoniecz/c83cc74b38d50b6310ca569a23915cd8#file-2_exported-ini )

```
diff LB2.txt LB3.txt 
8c8
< days1=127
---
> days1=0
```

**Comment by proginosko** [comment]
Good catch! It's a bug in the import function that was inadvertently introduced in v1.0. I'll get it fixed.

**Comment by proginosko** [comment]
Fixed in version 1.0.2, just uploaded. Sorry about that.

**Comment by matkoniecz** [comment]
Is it possible that "Allow temporary override for these sites" similarly affected? I upgraded to 1.0.2 and it is the next issue that I noticed (as block set started working but override continued to be disabled).
