### ISSUE TITLE
 "Allow temporary override for these sites" (allowOverride) field lost on importing config

### ISSUE THREAD

**Issue by matkoniecz** [proginosko/LeechBlockNG#109]
Basically the same bug as #108 - field is exported and ignored on importing

**Comment by proginosko** [comment]
Yikes, I just realized it's a problem with all the boolean options. Working on a fix...

**Comment by proginosko** [comment]
Fixed in version 1.0.3, just uploaded. Hopefully that will be the end of it... 😬

**Comment by matkoniecz** [comment]
I can confirm that for me bug is now gone.
