### ISSUE TITLE
"Cancel Active lockdown" button doesn't work

### ISSUE THREAD

**Issue by JessFairbairn** [proginosko/LeechBlockNG#11]
Hi there,

The "Cancel Active Lockdown" button under Advanced Options doesn't currently do anything when clicked- there's no UI feedback, and the Lockdown carries on going.

(In addition: thank you for making Leechblock NG. Leechblock was my favourite Firefox add on ever and I was scared enough at the thought of losing it I'd actually forked it and tried to turn it into a Web Extension myself, although I struggled greatly. Given my lack of self discipline, you might have single handedly saved my masters degree by making this...)

**Comment by proginosko** [comment]
Wow, you're right. Sorry about that. I'll get that fixed in the next release.

**Comment by proginosko** [comment]
Fixed in v0.5 (just released).
