### ISSUE TITLE
Lag in Blocking Website

### ISSUE THREAD

**Issue by William3342** [proginosko/LeechBlockNG#111]
When Firefox, opens this MSN site by default. I am on an Acer computer, there is a lag before the block takes effect of a few seconds or the page may stay around.

https://www.msn.com/?cobrand=acer15.msn.com&ocid=ACERDHP15&pc=ACTE is NOT blocke

**Comment by proginosko** [comment]
Is the option "Immediately block pages on these sites once blocking conditions are met" selected?

**Comment by William3342** [comment]
Yes.

**Comment by proginosko** [comment]
Unfortunately all Firefox extensions seem to experience some startup lag time. I don't see anyway around that; it's beyond the control of the extension developer. I can only suggest you change your startup page (assuming you can) if its not being blocked is a problem.
