### ISSUE TITLE
Question about data privacy

### ISSUE THREAD

**Issue by trevor87** [proginosko/LeechBlockNG#112]
Hi!

I really like the concept of LeechBlockNG but tend to distrust browser extensions with many privileges since [what happened with the "stylish" extension](https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/). Therefore I wanted to ask:

Does this extension send any user data to external servers? Also, if this extension would be sold to someone at some stage, would you make this expressly clear to the users (e.g. with a popup in the extension)?

Thanks!

**Comment by proginosko** [comment]
https://www.proginosko.com/leechblock/faq/permissions/

LB doesn't send any user data to external servers and never will.

I can't imagine ever selling LB to anyone (although I suppose everyone has their price!) but if that ever happened, I would certainly make that very clear to users.

**Comment by trevor87** [comment]
Thank you for the quick answer! I am very glad to hear that! Keep up the great work!
