### ISSUE TITLE
Buttons to sync settings in Firefox for Android are disabled

### ISSUE THREAD

**Issue by codethief** [proginosko/LeechBlockNG#116]
The buttons "Export settings to sync storage", "Import settings from sync storage" are grayed out / disabled. Moreover, the options "[ ] Use sync storage for options (experimental: …)" and "[X] Automatically export options to sync storage (as backup) whenever options are saved" are disabled, too, i.e. their values are fixed.

Is syncing not available on mobile yet? (I'm using Firefox for Android v68.0.2.)

**Comment by proginosko** [comment]
Sync storage isn't yet supported on Android:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

As soon as it is, those buttons will be enabled! 😃
