### ISSUE TITLE
List of sites from URL not reloaded when opening new browser window

### ISSUE THREAD

**Issue by kfp1871** [proginosko/LeechBlockNG#118]
I've configured LeechBlock to load a list of sites from a URL for one of my blocksets. According to the FAQ, the list should be reloaded every time a new browser window is opened. This does not seem to be happening: when I open a new window, LeechBlock does not perform an http request to the server serving the list of sites, and keeps using the old list.

The list of sites _is_ correctly reloaded when I quit and restart the browser, or when I go to the LeechBlock options and choose "Save Options" for the blockset in question.

Tested on Firefox 60.9.0esr on Linux with LeechBlock NG version 1.0.4.

As I like to keep my browser running for a long time, it would be very convenient if the list could be reloaded when opening a new window, or even, if possible, when opening a new tab. If this is difficult to fix however, perhaps the FAQ entry could be changed to match the current behaviour.

Thank you for your work on this great addon!

**Comment by proginosko** [comment]
Sorry about this discrepancy. It was due to changes introduced by Firefox 57. The FAQ has now been corrected.
