### ISSUE TITLE
Improvements - Better control over Override and Lockdown

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#125]
Would be nice if Override function worked like Lockdown function, allowing you to select the length of time to override rather than being a predetermined fixed amount entered in preferences.

Would also be nice when using Lockdown that it would lockdown any overrides that were activated.

**Comment by proginosko** [comment]
My concern is that if the user could select any duration at the time of the override, it would defeat the purpose of LB altogether. "I blocked these addictive sites, but now I'm going to override the block for 4 hours!"

**Comment by MarkG55** [comment]
How about adding a configuration option to set a maximum override period if a new option to allow variable length overrides was added?

**Comment by smayer97** [comment]
If concern is that override defeats LB, then either create override for any amount but require a password or create override with max, or both.....think like parental control, so that the only person that can apply an override is someone with the password.

**Comment by smayer97** [comment]
Not sure which version but this looks like it was implemented!  :-)
