### ISSUE TITLE
Whitelist option

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#126]
Please consider adding a Whitelist option, i.e., create a list of sites that can only be visited, with all the usual time options.

Might be as simple as creating a switch for each block set to either be a blacklist (as is now) or a whitelist.

**Comment by proginosko** [comment]
https://www.proginosko.com/leechblock/faq/exceptions/

**Comment by smayer97** [comment]
Thanks for the info. Glad to see that at least it is already possible.  😄 

But it is not obvious nor visible. I would still like to suggest that as a UI, it would be most user friendly if you used a visible switch or toggle in the settings.
