### ISSUE TITLE
Options changeable even if advanced option "Prevent access to options for this block set at times when these sites are blocked" is selected.

### ISSUE THREAD

**Issue by OscarPalafox** [proginosko/LeechBlockNG#129]
So let's say I have my options block configured and this is a time where I cannot access the blocked websites. As I have selected the "Prevent access to options for this block set at times when these sites are blocked" option, my options are greyed out and seemingly unchangeable until the allowed time comes for that specific block. But what I can do is access the general tab, export my options to a file, change the file (e.g. removing the blocked times) and import the file back. The settings will be changed right away and I am now able to access the blocked websites or change the options.
I don't know if this is intended or a small bug, in my opinion maybe it would be better if the option to import the settings would only be available once you are able to access all the blocks.

I am using LeechBlockNG version 1.0.4 with Firefox 72.0.1 (64-bit) for Windows.

![Import-Export](https://user-images.githubusercontent.com/46593945/72435882-0dd6ed00-3797-11ea-9ee1-ab3f8d9c961e.png)

**Comment by OscarPalafox** [comment]
I have cloned the repository and I have tried to change the code in order to implement the functionality mentioned above. As far as I see, it would only require to add one line in the `options.js` file. What I was thinking, was to add `getElement("importOptions").disabled = true;` in line 378. 
I have tried to run the changed extension but it does not work correctly. What I have done is:
1) Load a temporary add-on in `about:debugging` page
2) Load the `content.js` file
3) Try to access the `options.html` from the `about:addons` page

Note that I have tried to run the extension the same way without changing any code and it still does not work...
Somehow the options file does not charge when I try to run the extension, what do you think I am missing ? Could please you point me in the correct direction ?

The function `onGot(options)` in `options.js` ends up being:
```
function onGot(options) {
	cleanOptions(options);
	cleanTimeData(options);

	// Initialize form
	initForm(options["numSets"]);

	setTheme(options["theme"]);

	// Get current time/date
	let timedate = new Date();

	// Get current time in seconds
	let now = Math.floor(Date.now() / 1000);

	// Check whether a lockdown is currently active
	for (let set = 1; set <= gNumSets; set++) {
		let timedata = options[`timedata${set}`];
		let lockdown = (timedata[4] > now);
		getElement(`cancelLockdown${set}`).disabled = !lockdown;
	}

	// Check whether access to options should be prevented
	for (let set = 1; set <= gNumSets; set++) {
		if (options[`prevOpts${set}`]) {
			// Get options
			let timedata = options[`timedata${set}`];
			let times = options[`times${set}`];
			let minPeriods = getMinPeriods(times);
			let limitMins = options[`limitMins${set}`];
			let limitPeriod = options[`limitPeriod${set}`];
			let limitOffset = options[`limitOffset${set}`];
			let periodStart = getTimePeriodStart(now, limitPeriod, limitOffset);
			let conjMode = options[`conjMode${set}`];
			let days = options[`days${set}`];

			// Check day
			let onSelectedDay = days[timedate.getDay()];

			// Check time periods
			let withinTimePeriods = false;
			if (onSelectedDay && times) {
				// Get number of minutes elapsed since midnight
				let mins = timedate.getHours() * 60 + timedate.getMinutes();

				// Check each time period in turn
				for (let mp of minPeriods) {
					if (mins >= mp.start && mins < mp.end) {
						withinTimePeriods = true;
					}
				}
			}

			// Check time limit
			let afterTimeLimit = false;
			if (onSelectedDay && limitMins && limitPeriod) {
				// Check time period and time limit
				if (timedata[2] == periodStart && timedata[3] >= (limitMins * 60)) {
					afterTimeLimit = true;
				}
			}

			// Check lockdown condition
			let lockdown = (timedata[4] > now);

			// Disable options if specified block conditions are fulfilled
			if (lockdown
					|| (!conjMode && (withinTimePeriods || afterTimeLimit))
					|| (conjMode && (withinTimePeriods && afterTimeLimit))) {
				// Disable options for this set
				disableSetOptions(set);
				// Disable importing options
				getElement("importOptions").disabled = true;
			}
		}
	}
```

**Comment by OscarPalafox** [comment]
Ended up forking the project and creating a fixed version of the extension.

**Comment by ke352802081770314** [comment]
you may take note of the fact that Leechblock now has, in blockset advanced options: "Prevent access to General options at times when these sites are blocked" which includes access to the import function.

**Comment by proginosko** [comment]
Also, import functionality is now automatically disabled when access has been prevented to at least one block set.
