### ISSUE TITLE
LeechBlock for Firefox Mobile issues

### ISSUE THREAD

**Issue by cream-neapolitan** [proginosko/LeechBlockNG#13]
I installed LeechBlock on Firefox mobile successfully, but it doesn't detect the supposedly blocked website, which mean it won't block any website. When I tried to block the site for all day, the block set editor does lock itself for editing but the specified site is still accessible. I wonder if the mobile version needs different checker implementation, it's  worth looking at.

**Version Tested:** Firefox Release 57.0 / Android 7.1.2

**Comment by Metaception** [comment]
I can confirm this issue. I heard that Firefox Mobile's web-ext API is lagging? Maybe that's why.

**Version Tested:** Fennec F-Droid 57.0 (No proprietary binaries) / Android 5.1.1

**Comment by proginosko** [comment]
Yes, it looks like LB doesn't (yet) work on Firefox for Android. I'd hoped that it would, since it uses only WebExtensions, but apparently not. I've tried it on an Android emulator, but I don't know why it isn't blocking pages. Firefox for Android doesn't offer much support for debugging! I've also heard that it doesn't support all of the web-ext API yet, so I'm guessing that's part of the problem. Perhaps it's just a matter of waiting...

**Comment by lftl** [comment]
Here's a little output from a remote debugging session with the app on my phone:

`TypeError: browser.menus is undefined     background.js:819:1`

I wrapped line 819 in an 

`if(browsers.menus) {
}`

And that at least gets the timer to show up on the tab, but it doesn't count down, and doesn't actively block. Taking a bit more of a look at that now.

**Comment by lftl** [comment]
After gating out browser.menus and browser.windows, blocking by time of day does work. The timer shows up on the page but won't count down or block. The timer pulses once per second in the debugger showing a DOM update, but the time doesn't change. Nothing super helpful showing up in the console. There are a bunch of these, but they don't mean much to me:

`
Handler function threw an exception: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService2.newChannelFromURI2]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/NetUtil.jsm :: NetUtil_newChannel :: line 28"  data: no]
Stack: NetUtil_newChannel@resource://gre/modules/NetUtil.jsm:28:8
this.requireRawId@resource://devtools/shared/loader-plugin-raw.jsm:5:12
requireHook@resource://devtools/shared/Loader.jsm:11:225
require@resource://devtools/shared/base-loader.js:70:24
Require/require.context/<@resource://devtools/shared/base-loader.js:90:45
getProperties@resource://devtools/shared/base-loader.js -> resource://devtools/shared/l10n.js:16:40
getStr@resource://devtools/shared/base-loader.js -> resource://devtools/shared/l10n.js:19:68
parseSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-helper.js:30:128
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:42:61
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:2:467
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:28:22
Line: 28, column: 0
`

**Comment by proginosko** [comment]
Thanks, Scott. That's really helpful info. I'm embarrassed to say I only just discovered the web page showing how much of the web-ext API is supported by Firefox for Android:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

At least now I have a better idea how to move toward a working mobile version.

**Comment by lftl** [comment]
Duh, commenting out browser.windows breaks the functionality for running the timer when a window is focused. If I uncheck the option for only blocking when a window is focused, the timer works, but it continues running if I switch to a different tab.

**Comment by proginosko** [comment]
Right. But I guess active tab could serve as a proxy for focused tab on a mobile browser, at least until browser.windows is supported.

**Comment by lftl** [comment]
Yep. That works.... I went through and basically stripped out any logic about whether the window was focused or not, and now the timer stops running if I switch to another tab. Seems to also stop if I switch to another app or exit FF via the home button.

**Comment by proginosko** [comment]
Sweet. No need for a pull request; I'll do it myself and put it in the next release. Thanks!

**Comment by proginosko** [comment]
Scott, since FF for Android doesn't (yet) implement the windows API, I'd love to know what value it returns for the windowId property of a Tab object. Any chance you could find that out for me? For example, put `console.log(tab.windowId);` in the `handleTabUpdated` function.

**Comment by proginosko** [comment]
I just release v0.5.1. Looks like it works on Android (on my emulator, at any rate).

**Comment by cream-neapolitan** [comment]
Thank you! Can confirm LeechBlock 0.51 works on my phone now.

**Comment by cream-neapolitan** [comment]
Anyway, is there no way to do lockdown on mobile version right now. Maybe you could use the overflow menu and place it there?

**Comment by proginosko** [comment]
The next release will add a popup menu so you can select either Options or Lockdown.

**Comment by cream-neapolitan** [comment]
Nice, I'm looking forward to it. 
While we're on that topic, you should add the _"Add site"_ option as well to reflect the right click menu.

Again, thank you for all the support. I',m sorry if I request too much.

**Comment by codethief** [comment]
I'm not sure if this related to the issues above but a couple days ago, LeechBlock stopped working for me all of a sudden on Firefox for Android. None of my block sets is working anymore (no matter whether it's tied to certain sites, timeframes or both).

I'm running Firefox 58.0.2 and LeechBlock NG 0.9.1.

**Comment by proginosko** [comment]
> I'm not sure if this related to the issues above but a couple days ago, LeechBlock suddenly stopped working for me at all on Firefox for Android. 

My fault -- I broke something in 0.9.1. It will be fixed in 0.9.2, to be released later today.
