### ISSUE TITLE
Putting local html file into block page URL gets around block

### ISSUE THREAD

**Issue by yarivaltean** [proginosko/LeechBlockNG#130]
Hi! 
I wanted to write up a little of my own html that I would see every time I visited a blocked page so that I could redirect my attention. 
When I put the filepath into the field labeled: "Enter the fully specified URL of the page to show instead of these blocked sites:"
LeechBlock just took me right on through to the site I was trying to block instead. 

Not a big problem by any means, I'm just continuing to use the default page for now, but it would be nice to be able to put in a message for myself when I hit the block page. 

Thanks for the great extension!

**Comment by proginosko** [comment]
See here:

https://www.tapatalk.com/groups/leechblock/viewtopic.php?p=705
