### ISSUE TITLE
When refreshing a site after a block time limit expires, the time limit immediately finishes for the next period

### ISSUE THREAD

**Issue by Scharnvirk** [proginosko/LeechBlockNG#134]
I have LeechBlock configured as follows:

![3nAkVbR](https://user-images.githubusercontent.com/11149454/76400829-3c310d00-6381-11ea-9fe4-1f919587c63c.png)

The problem is, when refreshing a site after a block time limit expires, the time limit immediately finishes for the next period.

To reproduce:
1: use configuration as above
2: allow a site to trigger a blocking limit. For example enter it at 12:03. At 12.07 it will get blocked.
3: allow enough time to pass to clear the limit. For example wait till 13:00.
4: refresh the site. 

Observe how the timer immediately sets itself to 00:00 instead of 04:00. 
If you go to a non-listed site and then go back to your site, the addon works as intended.

**Comment by proginosko** [comment]
Thanks for the report. Is this happening in Firefox or Chrome?

**Comment by RX14** [comment]
This is happening to me, in firefox.

I think that perhaps leechblock is counting time spent on the "site blocked" page as time spent on the site, but I'm not entirely sure.

**Comment by RX14** [comment]
To be specific: Firefox 74 with leechblock 1.0.5.

**Comment by Scharnvirk** [comment]
Sorry @proginosko, I thought I replied and yet I forgot.
This happens in Chrome, since at least a year or so so any relatively new version is affected.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.6.1. If not, reopen this issue.
