### ISSUE TITLE
Bug in block sets ≥10

### ISSUE THREAD

**Issue by luuf** [proginosko/LeechBlockNG#138]
In the general settings, it is possible to increase the number of block sets up to 30, which is very nice. However, there are bugs in block 10 and above.

When trying to visit a website that is blocked in block set 10 or above, the site is blocked as normal, but an ampersand & is prepended to the url displayed in the middle of the screen. Delay-pages will, after the delay, fail to load the original url, instead trying to load for example "moz-extension://6870ada5-517a-1d47-bfd0-24476f5e2cd6/&https://www.reddit.com/", and not find any such file.

In addition, Overriding does not work for block set 10 or higher. The sites remain blocked. I'm not sure whether this is connected to the ampersand issue.

My best guess is that the bug has something to do with the url-arguments passed to the delaying/blocking sites. For block set 9, the end of the blocking-page url look like "?9&https://www.reddit.com/", and for block set 10, it looks like "?10&https://www.reddit.com/". Perhaps the additional numeral causes some string-manipulation to include the ampersand in the url.

Versions:
LeechBlock NG 1.0.4
Firefox 74.0
Mac OS 10.14.6

**Comment by proginosko** [comment]
Wow, good catch! I can't believe this wasn't discovered earlier. It suggests not many users need >9 blocks!

I will get it fixed ASAP.

**Comment by proginosko** [comment]
Fixed in version 1.0.5.

**Comment by luuf** [comment]
Thanks, works great!
