### ISSUE TITLE
Over night blocking does not work

### ISSUE THREAD

**Issue by sirati** [proginosko/LeechBlockNG#139]
I wanted to set a time restriction to be over night: 2200-0700 but it does not accept this as a valid time restriction

**Comment by smayer97** [comment]
The work-around is to create 2 entries, one from 2200-2359 and one from 0000-0700

**Comment by proginosko** [comment]
https://www.proginosko.com/leechblock/faq/overnight-block/

**Comment by sirati97** [comment]
Thank you for the information, but I do not want to block the sites at the same say from 0 to 6am and 11pm to midnight, but i want to block them from 11pm to the next day. I do feel like that this should be added as it is fundamentally different behaviour. 

If i have an important thing to do, then it doesn't help if i can surrender to the computer again after midnight because I didnt also select the next day for blocking

**Comment by proginosko** [comment]
Sure, I understand that's the desired behavior for some users. The workaround for now would be to use additional block sets to cover the extra times. Let me know if you need me to explain further.

**Comment by sirati97** [comment]
thank you for reopening. till this i guess feature request is implemented i am fine with using workarounds. i do not think i need further assistance to do so 

cheers

**Comment by proginosko** [comment]
I'm willing to consider implementing this, but I'm unsure what it would like in terms of user interface. How would the options be presented to the user?

**Comment by sirati97** [comment]
I think simply allowing an input like 2200-0700 is sufficient as it feels intuitive enough for me. To make sure that people do not get confused about it, you could display a warning whenever a user uses such a timespan, which explains how the input in being interpreted.

Alternatively, you could add a graph visualising the input.

Also I might note that their is another possible way of writing the timespan 2200-0700. In Japan they display over midnight opening times by simply counting higher than 24. e.g. Opening hours 18:00-26:00 meaning being open until 2AM. if you feel like that 2200-0700 is ambiguous, you could refuse such a range with the warning that the correct way of writing is would be 2200-3100

**Comment by proginosko** [comment]
If this is still a current feature request, please create a fresh thread under Discussions/Ideas.
