### ISSUE TITLE
Custom Blocked page URL doesn't work with file:/// or data: URIs

### ISSUE THREAD

**Issue by retnikt** [proginosko/LeechBlockNG#142]
The page just loads as normal. This seems likely to be some sort of browser limitation, but is there a way around it? I'm using Firefox

**Comment by proginosko** [comment]
Yes, Firefox introduced new security restrictions in version 57, including preventing extensions from opening local URLs.

For a workaround, see the thread here: https://www.tapatalk.com/groups/leechblock/load-list-of-sites-from-url-t241.html

**Comment by woj-tek** [comment]
I'm aware this is closed issue but I just ran into it (put `file:///…` in the block page and nothing was blocked) and have coupe of suggestions:
* add a warning, that `file:///` protocol is not supported if someone puts it there
* add option to create custom html file/template that would be served from LB so there wouldn't be a problem with security model? currently I'm pondering either putting the page on RPi (but that would case slightly longer delays, especially if I'm not at home) or using something akin to `python -m http.server 8000` (but this would have to be launch at startup and I would have to monitor it's running and available if something would crash; though - in that case the website would be blocked either way so there's that).

**Comment by woj-tek** [comment]
> Mozilla won't approve any extension with code that might be vulnerable to malicious attacks.

I assume this refers to suggestion to make it possible to edit/add blocking html page directly to LB? (ie. malicious code code put there their own code thus making it an attack vector)?
