### ISSUE TITLE
Cannot access option page

### ISSUE THREAD

**Issue by yanickDuhaime** [proginosko/LeechBlockNG#144]
Error: Unable to retrieve options from browser storage.
I keep getting this error when i try to access the option page.

**Comment by proginosko** [comment]
Have you always got that error message when you've tried to access the options page? In other words, is this an error that has only just started to appear?

**Comment by yanickDuhaime** [comment]
It's my first time trying it so yes and yes.
more info: I am using firefox, i tried uninstalling and reinstalling and nothing changes, i installed it on google chrome and it works fine there, multiple of my extensions on firefox seems to break so the problem could be on my end i'll look into it some more.

**Comment by proginosko** [comment]
Which OS are you using?

**Comment by yanickDuhaime** [comment]
Windows 10

**Comment by proginosko** [comment]
Okay, try this. Open Firefox's browser console (Ctrl+Shift+J). Make sure "Errors" is selected for the output filter. Clear the console, then try to open the options page. If any errors appear in the console, post them here.

**Comment by juvarov** [comment]
in console the same error:
[LBNG] Cannot get options: Error: An unexpected error occurred

I faced this problem also several days ago. On the Firefox, too. I see that I browser was updated 11 may to the new release. Seem that the problem is related to this update

**Comment by proginosko** [comment]
@juvarov So it is working on one laptop but not the other, both with the latest version of Firefox?

**Comment by juvarov** [comment]
yes

**Comment by juvarov** [comment]
on the problematic laptop this plug in was turned of during last 2 weeks and 3-4 days ago I turn it on and found that I can't enter the options

**Comment by proginosko** [comment]
It sounds like the local storage has become corrupted. Try creating a new Firefox profile and see if it works with that profile.

**Comment by yanickDuhaime** [comment]
I created a new profile and it works fine on this profile. Thanks for the help.

**Comment by juvarov** [comment]
but if to create the new profile I lost all my previous history, bookmarks and etc? I'll check if it possible without to lost

**Comment by proginosko** [comment]
For now I'm just suggesting you test it with a new profile. If it works with a new profile, that tends to confirm that corrupted storage is at fault.

**Comment by juvarov** [comment]
yes I confirm that the new profile solved it

**Comment by proginosko** [comment]
Okay, thanks. I don't know if there's a way to fix the corrupt storage in the original profile. "Refresh Firefox" in about:support may be the only solution.
