### ISSUE TITLE
LeechBlockNG should automatically whitelist its own sites

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [proginosko/LeechBlockNG#145]
Hi,
I had troubles making this addon work and had to go to the FAQ several times, I think the official website, as well as the github repo and the support forum should be automatically whitelisted.

Thanks for considering this

edit : added benefit : it would show how to exclude website from the blocking list, as this example would appear by default

**Comment by proginosko** [comment]
Good suggestion!

**Comment by proginosko** [comment]
Implemented in version 1.0.6.
