### ISSUE TITLE
Timer resets at the top of the hour! Also, doesn't work with Instagram Dark Mode plugin

### ISSUE THREAD

**Issue by mariocaiti** [proginosko/LeechBlockNG#146]
Hi, great plugin! Some problems, though:
At the top of the hour, the timer will reset! For example: for twitter I have it set to 25 minutes for every half hour. At 5:00 PM on my computer, the countdown may have been down to 3:00, but it will reset to 25:00.
Also, it doesn't seem to work on Instagram unless I toggle the Dark Mode plugin I also installed on Firefox (version 76.0.1).
I use Mac OS Mojave 10.14.6. If you could work on these, that would be great! (I didn't see this issue reported by anyone else. If I missed that, please direct me over.)

**Comment by proginosko** [comment]
The timer operation is correct; that's how it's designed to work. If you set a limit of 25 minutes in every half hour, then the timer will reset to 25:00 every 30 minutes. You have 25 minutes of browsing in every 30-minute period. What behavior did you expect or want?

Thanks for the info about the Dark Mode plugin. In what way does LB not work when it's installed?

**Comment by mariocaiti** [comment]
So, I thought it would be 25 minutes regardless of the time I go to the page, and then shut off for 5 minutes. Again, not dependent on the top of the hour, just on the time accessing the page. So, you're not interested in that feature, understood.
