### ISSUE TITLE
Time Period is Off by 1 Hour

### ISSUE THREAD

**Issue by Rendigo-345** [proginosko/LeechBlockNG#147]
Some some reason the timer periods i set start/end 1 hour earlier than set. I had it set to block from 0000-1600, 1900-2400, but in reality it blocks from 0000-1500, 1800-2300. I checked my PC's internal clock, but its running on the right time. And it only started recently.

Any thoughts?

**Comment by proginosko** [comment]
Could be related to #70. Which time zone are you in?

**Comment by Rendigo-345** [comment]
> 
> 
> Could be related to #70. Which time zone are you in?

I'm in the Central European Time zone (CET, +1). However, when I set this time into my PC when i got it after new-years i have some issues with the time. I set in the proper time zone, but it was still one hour off. I had to move it over one time zone (+2) for it to align with my other clocks and [this site ](https://time.is/) which i use to double check for the correct time. When you asked i checked [here ](https://www.timeanddate.com/), and apparently my country's using Central European _Summer_ Time, which is +2. It's also supposed to go back to CET in October. So that's probably the issue, but is there something I can do about this?

**Comment by proginosko** [comment]
I'm considering adding an option to manually adjust the time zone correction. Stay tuned...

**Comment by balayanr** [comment]
> I'm considering adding an option to manually adjust the time zone correction. Stay tuned...

Is there any progress on this issue? Probably due to some privacy setting, websites can't read local time in my browser and everything is in GMT, so time zone in LeechBlock is off.

**Comment by proginosko** [comment]
Yes, the option to specify a custom clock offset was introduced in version 1.0.8 (see #70). Sorry for not remembering to post a notification here.

**Comment by balayanr** [comment]
Ah, I was looking for an option labelled as "timezone" or something, but it's called "offset clock." Thanks
