### ISSUE TITLE
Have a leechblock this site is blocked website open counts as time on that page

### ISSUE THREAD

**Issue by sirati97** [proginosko/LeechBlockNG#150]
I accidental opened a page in the background that had a time limit and i did not notice until the next time period just started. (like x minutes every 8 hours)

When i then opened another website of that block set 5 minutes into the new time period it was blocked and i did not know why. Then i realised that this other tab was open. 

So there are two issues here: When a page is already blocked (redirected to the this site is blocked website) then this should not be counted towards usage of that block set. 
Secondly, time is counted incorrectly

**Comment by proginosko** [comment]
Please provide a specific step-by-step example so I can try to reproduce this issue.

**Comment by sirati97** [comment]
Step 1: 
-create Block list with x minutes allowed every y minutes/hours
-disable 'Count time spent on these sites only when browser tab is active'
- enable 'Immediately block pages on these sites once blocking conditions are met'
for demonstrating this i chose example.com 1 minute every 15 minutes.
Step 2: open example.com, wait until you see the 'The page you're trying to access has been blocked by LeechBlock.' message and keep that tab open.
Step 3: wait a time until you enter the next blocking period (here the clock-time rounded up the next full 15 minutes) and try opening a site from the blocklist in a new tab (here example.com)

Example.com will be blocked in the new blocking period even though it was not accessed during that period at all

**Comment by proginosko** [comment]
Thanks, this is helpful. I have been able to reproduce the issue and will work on a fix.

**Comment by proginosko** [comment]
Should be fixed in version 1.0.6.1. Give it a try!
