### ISSUE TITLE
version history does not cover 1.0.6

### ISSUE THREAD

**Issue by ke352802081770314** [proginosko/LeechBlockNG#151]
The page https://www.proginosko.com/leechblock/version-history/ only covers changes up to 1.0.5, but current version is 1.0.6 and I have the impression that you did a lot of improvements in this version, so it would be good to also demonstrate these achievements!
Many thanks for providing and maintaining LeechBlockNG.

**Comment by proginosko** [comment]
Thanks for the reminder! Fixed now.
