### ISSUE TITLE
Where is sync storage files are stored?

### ISSUE THREAD

**Issue by kaushalyap** [proginosko/LeechBlockNG#153]
Thanks for creating this great extension. I have couple of questions about sync storage feature

- I would like to know where is sync storage files are stored? AWS, Azure, GCP DO,
- How to use this feature to restore settings in another machines browser?
- What about data privacy of the synced settings?

**Comment by proginosko** [comment]
LB uses Firefox's built-in sync storage API. Further information:

https://hacks.mozilla.org/2018/11/firefox-sync-privacy/

https://support.mozilla.org/en-US/kb/how-firefox-sync-keeps-your-data-safe-even-if-tls-fails

To restore settings that were saved to sync storage, use "Import Options from Sync Storage" under General options.

**Comment by kaushalyap** [comment]
@proginosko thanks for the response. How it is done in in Chromium based browsers? I am using Brave.

**Comment by proginosko** [comment]
Sorry, I don't know anything about Brave sync storage. I recommend you search their website:

https://community.brave.com/

**Comment by kaushalyap** [comment]
@proginosko How it works in Chrome?

**Comment by proginosko** [comment]
In Chrome, the sync data is stored in your Google account, so I believe.

**Comment by kaushalyap** [comment]
Thanks for your support! I'll close this now.
