### ISSUE TITLE
Time periods not working

### ISSUE THREAD

**Issue by tyranteon** [proginosko/LeechBlockNG#154]
I have my time period set up as `0400-1800`. This worked, once. Then it just blocked the site for the entire day (said it would unblock them at 1:29:something in the middle of the night). Now it doesn't block them at all.

**Comment by proginosko** [comment]
Do you have a time limit set as well as time periods? If possible, post a screenshot of your settings (just the "When to Block" section will do).

**Comment by tyranteon** [comment]
No, I don't have such time periods.

Here are the settings: https://i.imgur.com/YuzRDak.png

I didn't change much, pretty much anything is still default settings.

**Comment by proginosko** [comment]
Please export your options to a file and email it to leechblockng@proginosko.com so I can try to figure out what's happening.

**Comment by tyranteon** [comment]
I think it was just because I forgot to tick the weekend days. Thanks for the quick help!
