### ISSUE TITLE
Countdown running even though time limit is not setup (Android)

### ISSUE THREAD

**Issue by dbogdanov** [proginosko/LeechBlockNG#158]
I've done a fresh install of LeechBlockNG on Firefox Android. The countdown popup window is shown and running even though I haven't setup a time limit (the field is empty by default).

The option  "block within time periods OR after time limit" is selected.

Versions:
- LeechBlockNG  1.0.6
- Firefox 68.10.1

**Comment by proginosko** [comment]
The countdown shows the time left until the current website will be blocked. It will be shown regardless of whether you're blocking by time periods or by time limit or some combination of the two.

**Comment by Redevectored** [comment]
Perhaps one needs to enable to "Immediately block pages on these sites once blocking conditions are met" 
and disable "Count time spent on these sites only when browser tab is active".

**Comment by proginosko** [comment]
Assuming this is resolved.
