### ISSUE TITLE
Page not blocked when timer reaches 00:00:00 (Firefox for Android)

### ISSUE THREAD

**Issue by dkoprowski** [proginosko/LeechBlockNG#159]
Hi,
while browsing infinite-scroll page like 9gag for example you can browse forever. When timer goes to 00:00 you can still scroll through page. It will block properly only when you click some link.

- Firefox 68.10.1
- LeechBlockNG 1.0.6
- Android 10
- EMUI 10.0.0 (Huawei's version of Android)

**Comment by proginosko** [comment]
Have you selected the option "Immediately block pages on these sites once blocking conditions are met"?

**Comment by dkoprowski** [comment]
@proginosko I selected the option and it works well. Sorry for bothering. I'm using the extension for few year now and somehow I missed that option. Thanks!

**Comment by proginosko** [comment]
No worries!
