### ISSUE TITLE
Please re-introduce warning dialog xx seconds before blocking

### ISSUE THREAD

**Issue by alphestdev** [proginosko/LeechBlockNG#16]
It was a such a critical feature for me in the old version. Most time wasters for me are social networks and Q&A sites like Quora.  It's such a loss every time I'm in the middle of a long post/question/comment and suddenly it's gone without warning. Even the "page leave" dialog gets auto closed in an instant. It happens so quickly I can't even make screenshot or copy unsaved text.

Please think of all those great ideas humanity is losing.

Love your addon.

**Comment by proginosko** [comment]
Coming soon!

**Comment by proginosko** [comment]
Added in version 0.6.
