### ISSUE TITLE
Delayed + Filtered

### ISSUE THREAD

**Issue by doozan** [proginosko/LeechBlockNG#161]
I'd like to delay a page and then have the filter applied after the day.  I tried creating two separate blocks, one with the delay and another with the filter, but the filter does not get applied.  Is this currently supported or does it need a code change? Would it be be fixed by #156?

**Comment by proginosko** [comment]
Sorry, there is currently no way to do this. I may be introducing some changes to the code in a future version that will allow this, so stay tuned.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.7.1. Make sure the delaying set _precedes_ the filtering set in the order of sets.
