### ISSUE TITLE
LeechBlock fails to block sites intermittently

### ISSUE THREAD

**Issue by gitthepie** [proginosko/LeechBlockNG#162]
LeechBlock sometimes works for me and sometimes doesn't. At first, I thought the problem was caused by using 2 different time intervals (for example, 0000-0400 and 1500-2400), so I split up the time intervals into two different block sets. That seemed to work for a while, but I'm back to square one now, so I think the bug/problem was caused by something else.

Attached is my exported settings file. I hope it helps the developers figure out why the 2 sample sites (YouTube and Google News) aren't being blocked. Thanks!
[Settings.txt](https://github.com/proginosko/LeechBlockNG/files/5146109/Settings.txt)

**Comment by proginosko** [comment]
Which browser and OS are you using?

The next time it happens, copy the exact URL of the page that isn't blocked (but should be) and post it here. Thanks!

**Comment by gitthepie** [comment]
Firefox 80.0 under a Debian derivative. But I just found a problem with my Block Set 2. It looks like I had "within time periods AND after time limit" set rather than "within time periods OR after time limit", as my Block Set 1 was set to. Fixing this seemed to fix the problem. I'll leave this open for a few more days, since I ran into more than one problem, and I want to finish testing to make sure this really is resolved, but the specific issue I described is gone for the moment.

**Comment by proginosko** [comment]
Yes, that's probably it. But let's leave this open for now.

**Comment by gitthepie** [comment]
Well, I've done more testing, and everything seems to be working properly now, even with two different time ranges within the same Block Set. Thank you for your help and your work on this add-on. I can't even count the number of times I unconsciously visit a time-wasting site and get stopped by LeechBlock. The add-on has saved me much time.
