### ISSUE TITLE
Load list of allowed sites from URL?

### ISSUE THREAD

**Issue by levihb** [proginosko/LeechBlockNG#163]
The load list of blocked URLs from a URL is useful, but could you also add a way to load a list over allowed Regex overrides from a URL as well?

I use it on multiple computers, but I also keep a list of allowed overrides. Reddit is a really good example of this, because while I block most subreddits, I then have a list of subreddits to unblock in the allowed regex, and frequently add to this list. e.g.:

`/r/(programming)|(python)|(sql)` etc

Would we be able to load a regex list of allowed sites from the URL as well somehow? Maybe add a special syntax so that if a line starts with something it acts as an allow override?

**Comment by proginosko** [comment]
What would be the advantage of that over adding individual exceptions to the loaded list?

`+reddit.com/r/programming`
`+reddit.com/r/python`
`+reddit.com/r/sql`

etc.

**Comment by levihb** [comment]
Well one of the reasons is for multiple base domains. For example multiple sites like ceddit.com, removeddit.com, and uneddit.com (now gone), and I'm sure others. All those other sites store (or at least try to) backups of reddit's comments, so if a user or moderator/admin deletes a comment you can easily look it up there.

But yes even having the ability to just add individual exceptions would be great. With your examples would:

https://old.reddit.com/r/programming

https://www.reddit.com/r/programming/comments/jazoyx/verless_a_simple_and_lightweight_static_site/g8sza8c/

Work just fine?

Also the way you said that I couldn't tell if you were asking whether individual exceptions would be ok to add, or if it already supports them? It doesn't already support what you posted, does it?

**Comment by proginosko** [comment]
Sure, just leave out the https:// part:

`+old.reddit.com/r/programming`
`+www.reddit.com/r/programming/comments/jazoyx/verless_a_simple_and_lightweight_static_site/g8sza8c/`

You can even use wildcards:

`+*.reddit.com/r/programming`

Or to catch those alternative sites:

`+*eddit.com/r/programming`
