### ISSUE TITLE
Feature Request: Always delay + block after countdown

### ISSUE THREAD

**Issue by Sh3Rm4n** [proginosko/LeechBlockNG#164]
I like to see an option, where a page is initially always blocked by a delay page. After that a countdown timer is running and then the page will be blocked, so that accessing it again shows up not a delay page, but a blocked page.

This would prevent impulsive behavoir of opening some urls but also would prevent spending too much time on the page after the delay. 

The request is similar to  https://github.com/proginosko/LeechBlockNG/issues/161 and could also be fixed by https://github.com/proginosko/LeechBlockNG/pull/156, as two block sets are not working together if defined for the same page.

Thanks for your great work on this addon! :)

**Comment by proginosko** [comment]
You should be able to do this with version 1.0.7.1. You need to set up two block sets. The first one has the time limit and applies the blocking page. The second one uses time periods (sounds like you want 0000-2400) and applies the delaying page. It's important that the blocking set precedes the delaying set in the order of block sets.

**Comment by Sh3Rm4n** [comment]
Thanks! 

I could confirm, that this is working as intended. It was really easy to add a block set, which delays every page. It does apply to every preceding block set (I have 5), when the url is included in the last set as well.
