### ISSUE TITLE
Filters are overridden when using multiple block sets.

### ISSUE THREAD

**Issue by ceiphr** [proginosko/LeechBlockNG#165]
On GitHub, as an example, the grayscale filter works perfectly.

But on sites such as Reddit and Twitter, the filter applied to the body of the web pages is only applied for half a second before being set to `filter: none;`.

**Comment by ceiphr** [comment]
After messing around a little more, I now know this **is not** due to a conflict with other add-ons. 

**The issue occurs when two or more block sets contain the same domain(s).**

It doesn't matter if the two block sets have/don't have overlapping time periods or limits. It also doesn't matter if one or both are using the grayscale filter.

As long as multiple block sets contain the same block list, the filter will be overridden with `filter: none;`.

**Comment by proginosko** [comment]
Yes, I was going to ask whether you had Reddit and Twitter in other (later) block sets. This is a known issue. See thread here:

https://www.tapatalk.com/groups/leechblock/can-t-apply-filter-to-twitter-t386.html

I will try to get this fixed in the next release.

**Comment by ceiphr** [comment]
Happy to hear this is already being looked into. I look forward to your next release.

Feel free to close this issue now or when the problem is resolved.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.7.1.
