### ISSUE TITLE
Override timer stuck

### ISSUE THREAD

**Issue by skeskinen** [proginosko/LeechBlockNG#166]
Override timer is stuck at 0:00 and nothing gets blocked. I tried removing and reinstalling the extension but it didn't help, nothing is blocked.
![countdown](https://user-images.githubusercontent.com/908332/93312262-4ee03f00-f807-11ea-8c68-cee7b12407dd.png)

**Comment by proginosko** [comment]
What have you entered as the URL for the blocking page (i.e., first field in **How to Block** section)?

**Comment by skeskinen** [comment]
Yes, that is actually the real issue. I was trying to use file:///, and misinterpreted it as override problem since I changed override settings at the same time.

Now I see that file:/// doesn't work https://github.com/proginosko/LeechBlockNG/issues/142

Thanks
