### ISSUE TITLE
Infinite Refresh caused websites and google to block my IP

### ISSUE THREAD

**Issue by nicolae-stroncea** [proginosko/LeechBlockNG#167]
There appears to be some glitch which keeps refreshing indefinitely when a page has a URL that should be banned. I used to experience this on Firefox for the Web, and now problem recently occurs a lot on Firefox Mobile. It refreshes the page so often and so quickly that some websites temporarily banned my IP, and now google asks me to do "I'm not a robot" tests every time I search for something. Worse, that's for my router's IP, so hopefully my roommates don't find out they have to do these challenges because of me...

This is the set for which it happens:
```
setName1=Distractions
sites1=+youtube.com/channel +youtube.com/results +youtube.com/user +youtube.com/watch quora.com reddit.com youtube.com
times1=0000-2400
limitMins1=
limitPeriod1=
limitOffset1=
conjMode1=false
days1=127
blockURL1=http://www.google.com
applyFilter1=false
filterName1=grayscale
activeBlock1=true
countFocus1=true
delayFirst1=true
delaySecs1=60
reloadSecs1=
allowOverride1=false
prevOpts1=false
prevGenOpts1=false
prevAddons1=false
prevSupport1=false
showTimer1=true
sitesURL1=
regexpBlock1=
regexpAllow1=
ignoreHash1=true
```

This is the general settings:
```
numSets=10
sync=true
theme=
oa=0
password=
hpp=true
timerVisible=false
timerSize=1
timerLocation=0
timerBadge=false
orm=10
ora=3
orc=true
warnSecs=
warnImmediate=false
contextMenu=true
toolsMenu=true
matchSubdomains=false
saveSecs=10
processActiveTabs=true
accessCodeImage=false
autoExportSync=false
```

**Example when it happens**:

1. On Firefox Android, go to google.com
2. Search for a query that will return a Reddit post(not subreddit, has to be a post). Click on reddit link
3. Leechblock will start refreshing the page indefinitely. This is not fully reproducible, and sometimes only refreshes it for a couple of seconds before it settles.

**Comment by sirati97** [comment]
I have had the same problem once on firefox desktop

**Comment by proginosko** [comment]
I notice that you have www.google.com as your blocking page. Does the problem ever arise if you use LB's default blocking page?

Also try changing the URL of the blocking page to https://www.google.com (note: HTTPS) and see if the problem still occurs.

**Comment by sirati97** [comment]
> 

> Also try changing the URL of the blocking page to https://www.google.com (note: HTTPS) and see if the problem still occurs.

As i said i also experience the problem and I too have google as the blocking page. I do use HTTPS however. And for me the problem only occurs for the block set that has google as the blocking page and not for the other ones

**Comment by nicolae-stroncea** [comment]
@proginosko  I was only using google above as a place-holder, but it's still http for the website I'm using as the blocking page. I've noe switched to the default leechblock block page. Last time I hit the infinite refresh was actually earlier this week both from desktop and android, so I'll update if i hit it with this change.
