### ISSUE TITLE
Second time limit setup

### ISSUE THREAD

**Issue by AgataPB** [proginosko/LeechBlockNG#168]
Hi! I would like to ask if it is possible to add a second time limit setup. For example, I want to be able to watch freely the youtube after 18:00, but before that, on the time frames I allowed the page to load, I have only 20 min of use.

Times to block: 0800-1230,1300-1800
Time limit before 18:00: 20 minutes in every 3 hours
Time limit after 18:00: None
Select when to block these sites: within time periods OR after time limit.

Thank you very much!

PS: The extension is helping me very much, thank you!

**Comment by proginosko** [comment]
Use two block sets. Set up the first block set to completely block from 0800-1230 and 1300-1800 (no time limit). Set up the second to block from 00:00-18:00 with a time limit of 20 minutes in every 3 hours (within time periods AND after time limit).

That should do it. Let me know if it works.

**Comment by AgataPB** [comment]
It looks like it will do! Thank you.
