### ISSUE TITLE
Add feature || Auto close blocked page

### ISSUE THREAD

**Issue by ShinoIro** [proginosko/LeechBlockNG#169]
this feature is the most thing i need.. for me leechblock is the best page blocker i've tried.. it only mising that feature that i need most.
Please add the feature, maybe place it on general tab whether enable or not.. and the timer before it gets closed
Thank you.

**Comment by proginosko** [comment]
Yes, this could be added. Look for it in the next version.

**Comment by proginosko** [comment]
Added in version 1.0.7.
