### ISSUE TITLE
Carry over unused time from previous time limit

### ISSUE THREAD

**Issue by alistair-low** [proginosko/LeechBlockNG#170]
Thanks for this great browser extension! I have a small feature request:
- I have a block group set up with a time limit of 30 minutes in every 12 hours
- If I've been incredibly productive in the morning, it would be nice to give myself a little extra leisure time in the afternoon
- Therefore, could there be an option on the time limit to add the remaining time from the previous period to the next period? e.g. if I have 7 minutes remaining, the next time limit would be 37 minutes
- My feeling is that it should only add on the time remaining from the unadjusted limit in the previous period, to avoid a large cumulative surplus building up

Thanks for considering this idea. I am not sure whether this is a niche feature or something that lots of people could use :)

**Comment by proginosko** [comment]
I'm working on this and plan to include it in a future version.

**Comment by alistair-low** [comment]
This was added a long time ago - closing my ticket.
