### ISSUE TITLE
Support new version of Firefox Mobile

### ISSUE THREAD

**Issue by tmcguire** [proginosko/LeechBlockNG#172]
The new version of Firefox on Android (81.1.4 for me) no longer allows installing the LeechBlock NG extension, and actually disabled it after an automatic update.
In the add-on manager, the extension shows up as "Not yet available", with a text saying "We're currently building support for an initial selection of Recommended Extensions".
It would be great to have LeechBlock NG available on Firefox for Android again.
Given the text I understand that this might be out of your control though.

Also, thanks a lot for this useful software! Now that I can compare my mobile browsing with and without LeechBlock NG, I can say that it helped reducing my idle browsing a lot!

**Comment by proginosko** [comment]
LB is already available for Firefox for Android Nightly and will hopefully be available for the release version of Firefox for Android in November:

https://blog.mozilla.org/addons/2020/09/25/more-recommended-extensions-added-to-firefox-for-android-nightly/

**Comment by tmcguire** [comment]
> LB is already available for Firefox for Android Nightly and will hopefully be available for the release version of Firefox for Android in November:
> 
> https://blog.mozilla.org/addons/2020/09/25/more-recommended-extensions-added-to-firefox-for-android-nightly/

Oh, that's great to hear, looking forward to the next Firefox version then! I'll close this ticket then, as there seems to be nothing to do from the Leechblock NG team, besides waiting for the new Firefox to get released.
