### ISSUE TITLE
Countdown timer goes to 00:00 but doesnt block

### ISSUE THREAD

**Issue by pizzadeliverymen** [proginosko/LeechBlockNG#174]
I am trying to block youtube for 30 in each hour from noon to 5:00 pm on the weekends.  The countdown timer shows up to say how much time i have left, but it reaches 00:00 and doesn't block.  I have attached an image of my settings for the block set.  
I even made a new block set to try to block youtube for the entire day, and it has the countdown timer at 00:00 but still doesn't block

Here is the settings for the original block set
![image](https://user-images.githubusercontent.com/50088322/97812048-a833ee80-1c4c-11eb-830b-45e45e210362.png)

Here are the settings for the test block set
![image](https://user-images.githubusercontent.com/50088322/97812127-432cc880-1c4d-11eb-9302-66b9c468ba2f.png)

Here is the timer at 00:00
![image](https://user-images.githubusercontent.com/50088322/97812128-49bb4000-1c4d-11eb-87e6-e494a2dfe62e.png)

**Comment by pizzadeliverymen** [comment]
For some reason when I reloaded the page it worked, but that was for the one that blocked for the entire day, as soon as a removed that it went back to being unblocked

**Comment by proginosko** [comment]
Did you select the option "Immediately block pages on these sites once blocking conditions are met"?

What URL are you using for the blocking page?

**Comment by pizzadeliverymen** [comment]
I did select that option, and i am using the default url for blocking, here is a picture of that section of settings

![image](https://user-images.githubusercontent.com/50088322/97812660-d4ea0500-1c50-11eb-864f-6eafdf11a5e6.png)

**Comment by proginosko** [comment]
Do you have youtube.com in any other block sets?

**Comment by pizzadeliverymen** [comment]
Yes i do, i have it on other sets so i can have different block times for each day

**Comment by proginosko** [comment]
Try removing youtube.com (temporarily) from the other block sets to see if the behavior is the same.

**Comment by pizzadeliverymen** [comment]
I just tried that and it still isn't blocking

**Comment by proginosko** [comment]
Okay, let's try this. Export your options to a text file (Options > General > Export Options to File) as a backup. Now try to create a minimal case scenario (i.e., reset all block sets to defaults, apart from one that generates the problem described above). Export the options to a separate text file and email it to me (leechblockng@proginosko.com) so I can take a look.

**Comment by pizzadeliverymen** [comment]
I emailed it to you

**Comment by proginosko** [comment]
Resolved.
