### ISSUE TITLE
cannot use local file as the blocking page

### ISSUE THREAD

**Issue by ajawa-took** [proginosko/LeechBlockNG#175]
Thank you so much -- leechblock has been a lifesaver for me for many years!

I just moved from the original to the "next generation" version. In the old version, I had forbidden webpages redirect to a local file. Now a LeechBlock BlockSet with a local-file url in the "how to block" field does nothing. Just to make things more confusing, this "nothing" overrides whatever a later BlockSet might do to the same webpage.

I am on windows 8.1, running firefox 56.0 32-bit (can't give up some very old plugins), and here's the file url:
 file:///C:/Users/me/Pictures/PascalCampion/3324b.jpg
If I type this url directly into the browser address bar, it opens just fine.

Am I missing something or doing something wrong? or is this functionality just gone?

**Comment by proginosko** [comment]
Yes, this is a known issue due to security changes in Firefox. See #142.

**Comment by ajawa-took** [comment]
Sorry to waste your time: I am new on github, and didn't think to look through "closed" issues before posting. Thank you for quick reply!

**Comment by proginosko** [comment]
No problem!
