### ISSUE TITLE
keyword blocking does not work for some unicode strings

### ISSUE THREAD

**Issue by ke352802081770314** [proginosko/LeechBlockNG#180]
As discussed in the tapatalk forum:
I just did an experiment, and used a blockset:

```
wikipedia.org
~日本語
```
(these characters are "nihongo" = japanese in japanese and are used in the "also available in language" list on the left)
note i have the general option "match all subdomains" set so en.wikipedia.org de.wikipedia.org etc. will be matched by this.
No matter whether on a page that contains the pattern e.g. https://en.wikipedia.org/wiki/Advanced_Micro_Devices (language link to japanese version exists) or on a page that doesn't e.g. https://en.wikipedia.org/wiki/John_E._Caldwell the counter is displayed as 00:00 but the page is not blocked (I have learned that counter 00:00 is expected if site matches but keywords don't). Setting "immediately block" makes no difference. changing the pattern to 
`~*日本語* `
makes no difference.
Changing the pattern to
~deutsch
results in https://en.wikipedia.org/wiki/Advanced_Micro_Devices being blocked and https://en.wikipedia.org/wiki/John_E._Caldwell not blocked as expected.
So it looks to me that the unicode keywords are not working as they should. but I am convinced that the correct way to handle it would be to enter the unicode keyword as-is without any encoding.
for reference:
```
~Français works as expected
~Русский does not work
~Tiếng_Việt works
~Tiếng_Việ* works
~*ếng_Việ* works
~việ* works
~*ệ* blocks everything it seems
~*ệ*smtc blocks "smtc" even with no ệ present
~*日* blocks everything it seems
~*日*smtc blocks "smtc" even with no 日 present
~*日本* blocks nothing it seems
```
from the looks of it, words also containing plain ascii characters and only single unicode characters seem to work, while a sequence of purely non-ascii characters seems not to work. (I didn't test multiple adjacent unicode along with ascii, sorry.)

i did look at the source code, the relevant pieces appear to be common.js getRegExpSites and keywordToRegExp where the keyword regexp is built, plus content.js checkKeyword where the keyword regexp is evaluated. Intuitively there's nothing wrong with these.
i found an article that may be helpful. https://mathiasbynens.be/notes/javascript-unicode gives some hints that are beyond my superficial grasp of javascript.

**Comment by proginosko** [comment]
A little bit of research suggests that the problem has to do with word boundaries in regular expressions for some non-English languages. Currently LB checks for word boundaries around the specific keywords, to avoid partial matches (e.g., matching "humbug" with the keyword "bug"). But that results in missing matches for some non-English languages.

Examples:

`/\bKEYWORD\b/.test("KEYWORD")` returns **true**

`/\bKEYWORD\b/.test("(KEYWORD)")` returns **true**

`/\b日本語\b/.test("日本語")` returns **false** (hence LB misses it)

`/\b日本語\b/.test("(日本語)")` returns **false** (hence LB misses it)

`/日本語/.test("日本語")` returns **true**

`/日本語/.test("(日本語)")` returns **true**

Some thought needed on the best way to resolve this...

**Comment by ke352802081770314** [comment]
In my opinion, instead of translating a leading/trailing * into \b\S* or \S*\b respectively, it would result in a simpler and more robust regexp if the * would cause the \b anchoring to simply be removed. But this is only halöf the solkution because it does not help if we want to match complete words.

I found a positive perspective: according to https://norbertlindenberg.com/2012/05/ecmascript-supplementary-characters/#RegExp ECMAScript 6 introduced a /u qualifier in regexps which modifies behaviour to account for unicode, this includes the meaning of \b \w \W etc. According to https://www.w3schools.com/js/js_es6.asp browser support for ES6 is present since 2017 in all your target browsers so you can rely on it.
So I think you should use this in your keyword handling regexps, both in the substitutes building the regexp in common.js (just precautionary, to safeguard against corrupting multibyte characters, and probably not really necessary)  as well as definitely in content.js where you use the regexp for matching.
Maybe this already results in a unicode compatible version.

**Comment by proginosko** [comment]
Thanks for this. Unfortunately the u flag doesn't seem to solve the problem:

`/\b日本語\b/u.test("日本語")` returns **false**

`/\b日本語\b/u.test("(日本語)")` returns **false**

I think the only solution would be to have some way for the user to specify when word boundaries should be observed/ignored.

**Comment by ke352802081770314** [comment]
Unfortunately, you are right. It seems that \b is prejudiced against non-ascii characters even if /u is used.
/\bРусский\b/u.test(" Русский ") = false
/\bРусский\b/u.test("xРусскийx") = true
/\bРусский\b/.test("xРусскийx") = true
/\b지대로\b/u.test(" 지대로 ")
/\b지대로\b/u.test(" x지대로x ") = true
this shows that even cyrillic which would be closer to out alphabet than Japanese and definitely has a concept of words (as has Korean, whereas in Japanese or Chinese there is no white space signifying word boundaries) the characters are classified as non-word and /u makes no difference

I am not sure how to submit a patch but as I said, not relying on \b if avoidable would help. 
This could be done via (hopefully it is valid Javascript, otherwise just see it as conceptual code and adapt please):
```
function keywordToRegExp(keyword) {
	let special = /[\.\|\?\:\+\-\^\$\(\)\[\]\{\}\\]/g;
	let pattern = "\\b" + keyword
			.replace(special, "\\$&")			// fix special chars
			.replace(/_+/g, "\\s+")				// convert underscores
			.replace(/\*+/g, "\\S*")				// convert wildcards <- there was a /g missing here!
			+ "\\b";
       return pattern.replace(/^\\b\\S\*/,"").replace(/\\S\*\\b$/,''); // strip word boundary test in case of leading/trailing wildcard
}
```
That way at least wildcarded patterns would work, while they currently don't.
I found a bug just now by looking: `replace(/\*+/, "\\S*")`	was missing a /g this explains why *X* with X being a single character, no matter which, would block all pages, because the second * stayed untranslated and matched zero occurrences, and may be responsible for various "keyword doesn't work quite right" reports.

**Comment by ke352802081770314** [comment]
I did some further research and found that indeed Javascript defined \b as the boundary between a \w and a \W where \w is defined as `[A-Za-z0-9_]` and the /u flag does not change that at all.
However, there are https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes which will match across the whole unicode world.
`[^\p{L}\p{N}]` will match something that is neither a letter nor a number, so it would be the unicode equivalent of \W except for _ but I think anybody who is not a programmer would not expect _ to be treated more word-like than & or various other symbols, so most likely you didn't use `\b` with the intent to treat specifically the underscore as being inside words, but just because it was the most appropriate test that regexps provide. 
so to simulate the \b test we can use:
`/(^|[^\p{L}\p{N}])`word`([^\p{L}\p{N}]|$)/u`
Note that for completeness alternatively to matching a non-word character I also match the beginning/end of the string.
Some tests:
/(^|[^\p{L}\p{N}])Русский([^\p{L}\p{N}]|$)/u.test(" Русский!") = true
/(^|[^\p{L}\p{N}])Русский([^\p{L}\p{N}]|$)/u.test(" 娘Русский!") = false (a japanese character was seen as a word-character and prevents the word from standing alone)
etc. Looks good.
so I would refine the last line from my previous suggestion:
```
       return pattern.replace(/^\\b\\S\*/,"").replace(/\\S\*\\b$/,'') // strip word boundary test in case of leading/trailing wildcard
                .replace(/^\\b/,"(^|[^\p{L}\p{N}])").replace(/\\b$/,"([^\p{L}\p{N}]|$)"); // match word boundaries in a unicode-safe way
```
I am puzzled where to put that keywordRE should be /u but I'm sure you know that.
Also I am a bit worried that this may have a performance impact, so maybe it might be better to only perform the \b replacement if the pattern contains non-ascii characters..

**Comment by proginosko** [comment]
This is very helpful. Good catch of the missing g flag!

I also found a good discussion of the issue here:

https://stackoverflow.com/questions/14942652/how-to-emulate-word-boundary-when-using-unicode-character-properties

One of the commenters provided a general recipe for a standalone boundary using negative lookahead:

`(?:(?<!C)(?=C)|(?<=C)(?!C))`

where C is any character class.

I think I will try out a solution based on that recipe. My one concern is the potential performance hit.

**Comment by ke352802081770314** [comment]
many thanks for following up on this.
as mentioned, the performance issue may be mitigated by making it dependent on the pattern containing non-ascii characters, e.g. by testing the pattern for /[^ -~]/ and only using the unicode-safe word boundary if potentially needed. on the other hand, removing the word boundary test in case of leading/trailing wildcard may well improve performance significantly.

**Comment by proginosko** [comment]
I think I found a good solution with minimal performance hit. Beta version available for testing here:

https://www.proginosko.com/files/lbng/leechblock_ng-1.0.8b2-an+fx.xpi

**Comment by ke352802081770314** [comment]
I installed it and did some quick tests, looks good to me. 
Since I do not have the keyword requirement myself but was only playing gateway forum->github for that other guy, please understand that I don't want to expend too much time in further tests. I checked the code and must say, compliments, it looks cleaner than before despite the added functionality! well done, many thanks.
Also people who do not use keywords may find it a lot faster since you skipped the page preparation. Thank you!

**Comment by proginosko** [comment]
> I installed it and did some quick tests, looks good to me.
> Since I do not have the keyword requirement myself but was only playing gateway forum->github for that other guy, please understand that I don't want to expend too much time in further tests. I checked the code and must say, compliments, it looks cleaner than before despite the added functionality! well done, many thanks.

Sure, I understand that you were just playing the role of Good Samaritan! Your input was very helpful though. I certainly wasn't expecting you to do any extensive tests. The post above wasn't directed at anyone in particular, just anyone who happens to be following this issue.

**Comment by proginosko** [comment]
Version 1.0.8, which supports non-English keywords, now released for Firefox, Chrome, and Edge.
