### ISSUE TITLE
Cannot select "Use sync storage" option on Firefox Mobile

### ISSUE THREAD

**Issue by qantravon** [proginosko/LeechBlockNG#181]
Attempting to select this option (Use sync storage for options (experimental: use at your own risk!)) in the General settings results in the check box being selected as text instead of actually becoming checked. This makes the feature impossible to activate. The check box works correctly in Firefox on Windows.

**Comment by proginosko** [comment]
Firefox for Android doesn't support sync storage yet, so that option is disabled:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

Sorry!

**Comment by qantravon** [comment]
Ah, in that case is it possible to hide or otherwise clearly mark that this option is not available? It looks exactly like every other option on the page.

**Comment by proginosko** [comment]
Yes, it would be better to hide the options altogether. I will add that to the next release.
