### ISSUE TITLE
Android: Dark mode not used in main menu(?)

### ISSUE THREAD

**Issue by Jonta** [proginosko/LeechBlockNG#182]
Setup:
- Triple dot
- Add-ons
- LeechBlock
- Options
- General
- Miscellaneous
- Theme: Dark

Seeing the light:
- Triple dot
- Add-ons
- LeechBlock
- Light colours here

=)

```
Android 10
Firefox 83.1.0
LeechBlock 1.0.7.2
```

**Comment by proginosko** [comment]
Should be fixed in version 1.0.10. Reopen this issue if not!

**Comment by Jonta** [comment]
Looks better, but still a white flash. =)

**Comment by proginosko** [comment]
Do you mean that it briefly appears white before the dark scheme kicks in?

**Comment by Jonta** [comment]
Yes

Very similar to what extensions like e.g. WhiteSlash are trying to fix: https://chrome.google.com/webstore/detail/whiteslash-white-backgrou/koiiicglkbcomcplnggedapdhafigbje

**Comment by proginosko** [comment]
It's going to be tricky to avoid that, since LB has to pull the user's theme selection from storage before changing the style sheet. What if you install a dark theme for the browser as a whole?

**Comment by Jonta** [comment]
Already using Dark Reader. Doesn't affect LB

Could LB use dark while fetching theme, and then switch if user theme is light?

I think a moment of darkness would be less jarring to light-theme users, than the other way around

**Comment by proginosko** [comment]
This is on Firefox for Android, right? I tested it on both Firefox and Chrome for desktop and I didn't get any white flash.

**Comment by Jonta** [comment]
Android. Correct
