### ISSUE TITLE
block websites in certain languages. 

### ISSUE THREAD

**Issue by liutiming** [proginosko/LeechBlockNG#188]
Thanks again for this awesome work!

I would like to create a feature request on the following superuser question and I wonder if you have any ideas... I could not create an account on tapatalk... 

https://superuser.com/questions/1580737/how-can-i-block-web-pages-that-are-in-a-certain-language

> 
> I am bilingual and I realised that most content that I consume in Chinese are distractions and should be blocked during working hours. I am using LeechBlock to some distractive websites but I can still get distractive content on multilingual websites (e.g. YouTube).
> 
> Is there an extension/way for me to block a web page when it is in Chinese? I am thinking perhaps something could be done to detect the title of the website so that if it is in a certain unicode then it can block the web page.
> 
> (p.s. only mentioning Chinese because it uses unicode so it might be more feasible)

**Comment by proginosko** [comment]
I think the simplest solution would be to block with keywords, using some very common Chinese words or characters as keywords. You should be able to copy and paste Chinese characters into the options.

**Comment by liutiming** [comment]
Thanks!
