### ISSUE TITLE
Bypassing LeechBlockNG - Fix possible?

### ISSUE THREAD

**Issue by grinbeamuser** [proginosko/LeechBlockNG#190]
It's possible to remove LeechBlockNG despite having access to general options, about:addons and about:support disabled. Would it be possible to disable this, too?

Setting > Customize > drag LeechBlockNG to toolbar > Done > right click on LeechBlockNG > Remove extension

**Comment by proginosko** [comment]
Fix here: https://www.proginosko.com/leechblock/faq/disable-remove-extension/

**Comment by grinbeamuser** [comment]
Thx.
