### ISSUE TITLE
Delay page redirects to earlier page instead of target page

### ISSUE THREAD

**Issue by benwr** [proginosko/LeechBlockNG#192]
Occasionally (~ once every 20 times it's triggered), the delay page will open targeting the page I left rather than the page I'm trying to open.

It might be that it happens more often when sites use weird redirect tricks (like Facebook exit links), but it also sometimes happens even when I type a URL directly into the URL bar.

**Comment by benwr** [comment]
It occurs to me that this might only happen when going from one blocked domain to a second blocked domain, though I'm unsure.

**Comment by GeeWee** [comment]
I have the same issues and have had it for long times.
I'm pretty sure it only happens when going from blocked domain A to blocked domain B, where the delaying page will refer you back to domain A, instead of domain B.

It often happens e.g. between twitter and reddit, and can happen when writing stuff on the address bar (so not necessarily when clicking links).
I don't think those sites do anything particularly weird in regards to redirect tricks.

**Comment by proginosko** [comment]
I would like to fix this, but I need to be able to reproduce the issue to track down the problem. Please give info on which OS you're using and provide a series of steps to reproduce the issue (even if intermittent).

**Comment by benwr** [comment]
I'm on MacOS Big Sur, and also Android 11

Reproduction steps:

1. Start on any page at a delayed domain A (e.g. facebook.com in my case)
2. Type a different delayed domain B into the address bar (say twitter.com in my case)

Expected behavior: delay page opens and eventually redirects to the page at domain B
Actual behavior: delay page opens and eventually redirects back to the page at domain A

My only block group is:

```
*facebook.com
*reddit.com
*twitter.com
```

And here are the other settings for the block group:

![Screenshot_20210119-124354](https://user-images.githubusercontent.com/198835/105091078-2afe6580-5a54-11eb-98c0-46d834d55fa3.png)

**Comment by proginosko** [comment]
Excellent -- very helpful. Follow-up question: in the case where the delaying page redirects to domain A, is the URL shown in the delaying page correct (domain B) or incorrect (domain A)?

**Comment by benwr** [comment]
It shows domain A

**Comment by GeeWee** [comment]
My experiences are exactly the same, also with the delaying page url.

**Comment by proginosko** [comment]
Thanks for the reports. I have been able to reproduce the issue and I'm working on a fix.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.11, currently awaiting review. Reopen if you find otherwise.
