### ISSUE TITLE
Wildcards no longer working for blocking sites?

### ISSUE THREAD

**Issue by Marglf** [proginosko/LeechBlockNG#193]
I have some settings that block all sites(except a few whitelisted ones) during certain times of day by using * and **. However, it seems they dont get blocked anymore? Only specified site names get blocked, I cant just block everything that wasnt whitelisted.

This seems to have started within the last 48 hours, not sure exactly when, but definitely this morning.  I am up to date on version 1.0.9. I assume the commit 2 days ago did this?

Thanks again for working on this fantastic addon. It has helped me a lot.

**Comment by proginosko** [comment]
Thanks for the report. Not sure why 1.0.9 would have broken wildcards! Are you using keyword blocking at all?

**Comment by Marglf** [comment]
Nevermind. I somehow whitelisted **, although I'm really unsure how that happened, since it was in 3 locations at once. Maybe I accidentally messed up my selection while copying for copy paste, and then ended up with a stray +**. It seems to be working now. Very sorry to spend your time on this. I hope you have a nice week.

**Comment by proginosko** [comment]
No problem! Glad you figured it out.
