### ISSUE TITLE
Timer continues to countdown despite tab no longer being active

### ISSUE THREAD

**Issue by MarkG55** [proginosko/LeechBlockNG#194]
I'm running the current version of LeechBlock NG on Firefox 85 (was the same on Firefox 84) on Windows 7 and seeing that the countdown timer continues to count down, even if I switch to another tab, or click on a completely different application so that Firefox is no longer in focus.

This seems somewhat similar to:
https://github.com/proginosko/LeechBlockNG/issues/81

The main difference is that this is on the desktop and even switching to a tab for a page that isn't blocked doesn't prevent the countdown from continuing.

Similar to the other issue, the delay page knows that a tab is no longer in focus and stops counting when you either click on a different program, or onto a different tab.

The block option "Count time spent on these sites only when browser tab is active" doesn't seem to make any difference and neither does the general option "Process only active tabs (improves performance when multiple tabs open)"

**Comment by proginosko** [comment]
This is the first report I've seen of this behavior on the desktop version. If the option "Count time spent on these sites only when browser tab is active" is selected, the timer shouldn't go down if you switch to another tab or another application.

How many block sets are you using? Is it possible that you have different settings for different block sets?

Also, is the option "Treat browser windows as always focused" selected? (It should be deselected by default.)

**Comment by MarkG55** [comment]
OK, I've worked out that this is actually user error/a misunderstanding on my part.

It looks like it's because I'm using an override and the override time is always counting down because it has a hard time cutoff instead of giving you (say) 5 minutes to use a bit at a time until it's all gone.

**Comment by MarkG55** [comment]
Maybe the count down could be changed to say "Override: 1:00" as a reminder that it's an override that's counting down and not necessarily the block time that's being used up.

**Comment by proginosko** [comment]
I'll give that some consideration. The LB toolbar icon should switch from green to yellow when override is active.

**Comment by MarkG55** [comment]
Ah - I hadn't noticed that before.  Maybe there could be a mouseover popup for the timer countdown which says something like: "Override ends at: xxxx"  The mouseover for the toolbar icon could also be updated to say the same thing.

**Comment by cls-nebadje** [comment]
On my system the timer continues to count down even if the tab is not active. The corresponding check box is active. Firefox 87 on Ubuntu with LeechBlock 1.0.11
