### ISSUE TITLE
forcing settings (not just install) on Firefox

### ISSUE THREAD

**Issue by chriswep** [proginosko/LeechBlockNG#196]
i know that its possible to force/lock the extension through firefox policies (https://github.com/mozilla/policy-templates#extensions). locking the extension once it is set up does work well. however i think there is nothing stopping a user to reset his firefox profile and start over. Since force installing the extension has no real effect without settings i wonder if there is a way to also force initial settings?

**Comment by proginosko** [comment]
Yes, it should be possible to force install the extension for all users with the Install policy (just provide the URL of the XPI). However, resetting a Firefox profile will also reset the _settings_ of extensions, so merely forcing the extension to be installed won't solve the issue. Better to use userChrome and userContent files to hide the options to reset the profile.

**Comment by proginosko** [comment]
Sorry, I just realized I misread your original post: you were talking about settings, not installation. Still, my final sentence applies.

**Comment by chriswep** [comment]
i'm looking for a firefox solution, so i haven't looked into how chrome works in this regard - however i suppose a user can always just reset the profile data from the filesystem (which is a one second job as soon as s.o. figures it out)? Therefore my thinking was the solution has to be outside of the users scope/account, like firefox policies.json.

**Comment by proginosko** [comment]
I was thinking of this Firefox solution: https://www.proginosko.com/leechblock/faq/disable-safe-mode/

But perhaps this policy offers a simpler solution: https://github.com/mozilla/policy-templates#disableprofilerefresh
