### ISSUE TITLE
Can't copy or paste websites 

### ISSUE THREAD

**Issue by ghost** [proginosko/LeechBlockNG#197]
I'm not able to copy and paste websites (or anything else) to or from the Options page. 
When I click on the right cursor, nothing happens, so I don't get the option to copy or paste something.

**Comment by proginosko** [comment]
Interesting. Apparently the right-click context menu doesn't appear at all on the options page, and the following error is thrown in the browser console:

`TypeError: pageMenu.sendShowEvent is not a function PageMenu.jsm:41:14`

I have no idea why that's the case! I will have to look into this...

**Comment by myrthe95** [comment]
That's great, thank you! :)

**Comment by proginosko** [comment]
In the meantime, I guess you can use keyboard shortcuts to cut/copy/paste.

**Comment by myrthe95** [comment]
Thank you for the tip, I didn't think of that.

**Comment by proginosko** [comment]
This seems to be resolved now. I'm guessing it was a Firefox bug that got fixed.
