### ISSUE TITLE
keyword not stable

### ISSUE THREAD

**Issue by dervisbey** [proginosko/LeechBlockNG#199]
Hello,
I am the author of this issue on the forum for chrome:
https://github.com/proginosko/LeechBlockNG-chrome/issues/27
I am having the same issue for firefox (thank you for solving this issue for chrome btw!).

Also, with firefox the other way round doesnt work stable too, when keywords are used to block

**Comment by proginosko** [comment]
That's strange, because the same fix was added to the Firefox and Chrome versions. Can you give an example so I can reproduce the issue on Firefox?
