### ISSUE TITLE
Minor bug with the 'Add Site' option

### ISSUE THREAD

**Issue by TheGamer007** [proginosko/LeechBlockNG#20]
To replicate, take an empty block set and use the "Add Site" option in the context menu to add any site to that set. It is inserting a new line before the entry, and so the set becomes applicable to _all_  websites instead of just the one that was added. (Easily evident if the set's constraints are block 24x7) If the block set already has sites in it, then there seems to be no such issue.

Just going to the options page and removing that blank line fixes it. Or even saving the set again with no changes, since it seems to be trimming the field before saving.

**Comment by proginosko** [comment]
Thanks for the report!
