### ISSUE TITLE
Combining exceptions and referrer

### ISSUE THREAD

**Issue by robert-samal** [proginosko/LeechBlockNG#200]
Hi, 

is it possible to set an exception to be pages linked from somesite.com? 
I tried +>somesite.com and >+somesite.com and neither of them works. 

(Planned usage is to help someone who has trouble focusing: block for some time all internet with the exception of the webpage of a school class and the links on it. But the links are changing over time, so they can't be listed in the rules.)

Thanks, 

Robert

**Comment by proginosko** [comment]
Yes, it's possible. Use the referrer prefix > and select the option "Treat referrers as allow-conditions rather than block-conditions" under Advanced Options.
