### ISSUE TITLE
Leechblock doesn't work on Pinned Tabs until after manual refresh

### ISSUE THREAD

**Issue by gungfujoe** [proginosko/LeechBlockNG#201]
I've got a handful of pinned tabs that open every time I open Firefox, including the sites I want to limit using LeechBlock (FaceBook & Twitter). I've noticed, however, that when I first open my browser, there's no timer in the corner on those sites, and if I manually refresh the tab, the timer starts at the beginning, and none of the time I spent on the page before refreshing counts toward my limit.

Perhaps pinned tabs load before LeechBlock finishes initializing, and it's not re-checking the URLs of tabs that were already running? There must be a way to resolve this, since my other extensions that affect FB and Twitter's operation work as expected on pinned tabs. This issue is unique to LeechBlock.

I'm running Firefox 86.0.1 x64 on Windows 10, and LeechBlock NG 1.0.11

**Comment by Myvh** [comment]
I faced the same issue and found a workaround: [disabling automatic pinned tabs loading](https://support.mozilla.org/en-US/questions/1271043). By default, pinned tabs load on Firefox startup. With this configuration change, they now load only when the user goes inside, so Leechblock works as usual.

**Comment by proginosko** [comment]
Thanks for the comment. A couple diagnostic questions:

1. Do you have the option "Immediately block pages on these sites once blocking conditions are met" selected for the relevant block sets?
2. Do you have the general option "Process only active tabs" selected?

**Comment by gungfujoe** [comment]
I'm now using Firefox 102.0.1, and I still have this problem **intermittently**. Most of the time, the timer is there right from the beginning, but sometimes it's not. It more often seems to fail on Twitter than Facebook, and I have a common block set for both sites.

I do have "Immediately block pages..." for my "Facebook & Twitter" block rule.
I do not have "Process only active tabs" selected.

**Comment by proginosko** [comment]
> I'm now using Firefox 102.0.1, and I still have this problem **intermittently**. Most of the time, the timer is there right from the beginning, but sometimes it's not. It more often seems to fail on Twitter than Facebook, and I have a common block set for both sites.

These are pinned tabs, correct?

**Comment by gungfujoe** [comment]
Yes, the tabs are pinned, and I'm not using Myvh's workaround of telling Firefox to disable auto-loading of pinned tabs.

I also should've mentioned that I'm using LeechBlock NG 1.4.2. I'm definitely not still using the same version from the original report. :)

**Comment by Myvh** [comment]
> Do you have the option "Immediately block pages on these sites once blocking conditions are met" selected for the relevant block sets?
Yes.
> Do you have the general option "Process only active tabs" selected?
Yes.
> … I still have this problem intermittently.
Same for me, the timer sometimes works and sometimes not. I’ve not noticed any “pattern” about when it works or not.

**Comment by proginosko** [comment]
Working on a fix for this. Looks promising so far...

**Comment by proginosko** [comment]
This should be fixed in the most recent release (v1.5.1).

**Comment by gungfujoe** [comment]
Thanks! You're the best, @proginosko ! 😀
