### ISSUE TITLE
Add option to keep Delaying Page counting after focus loss

### ISSUE THREAD

**Issue by Illiou** [proginosko/LeechBlockNG#202]
I would like to have an option to allow me to unfocus the Delaying Page (i.e. switch to a different window or tab) and still have it count down.

I get that having to stay on the delaying page, doing nothing, is probably a stronger motivation to abandon it but it also wastes your time if you actually need to open a page for work.
There are pages which can both waste your time and be needed for work, for example Wikipedia, which I don't want to allow. But then when you do need them you have to just sit there and wait which actually wastes your time too.
I would rather switch back to my work and keep working on it and then come back after say a minute. I think it would still work against actual distracting pages, since you usually open them in a brief urge. If you have to wait a minute that urge is likely gone already, no matter if you starred at the delaying page or something else.

Well at least I'd like the option to try it. And, maybe there is an even better middleground that I didn't think of.
Thanks

**Comment by proginosko** [comment]
Added in version 1.2.
