### ISSUE TITLE
Mute blocked pages

### ISSUE THREAD

**Issue by iliadaili** [proginosko/LeechBlockNG#203]
Hi!

First of all, thanks for the great add on, it's very useful and it has helped me a lot. One idea I had while using it was the option to force mute tabs when they have pages that are blocked open. That's something I thought about while in a block that had filters (blur 4px) turned on. In my situation, besides the filter, it would be very useful to be able to force mute these pages while they're blocked as well. Something else that would also be cool, at least in my personal experience with the add on, would be the option to blur the screen even more during block session. Just some ideas, not really an issue, I hope it's okay to leave it here. Am new to Github.

**Comment by proginosko** [comment]
Why did you close this? It was a good suggestion! I think it would be relatively easy to implement.

**Comment by iliadaili** [comment]
Glad to hear it! Thank you.

**Comment by funnym0nk3y** [comment]
Would love that too!

**Comment by proginosko** [comment]
Added in version 1.0.13.

**Comment by iliadaili** [comment]
Thank you!
