### ISSUE TITLE
Translate addon

### ISSUE THREAD

**Issue by Elaborendum** [proginosko/LeechBlockNG#204]
Is there any way to help with the localization of the addon, if not, are there any plans to support localization?

**Comment by proginosko** [comment]
Thanks for the offer! I do want to support localization and I hope to work on that soon. I will be in touch!

Which language is local for you?

**Comment by Elaborendum** [comment]
I was thinking of doing spanish, since I would love to use this in my language. Can't wait for that announcement!

**Comment by proginosko** [comment]
Please email me (leechblockng@proginosko.com) to help me get started with the Spanish localization.

**Comment by Elaborendum** [comment]
Sure! I just did.

**Comment by starise** [comment]
Hello @proginosko, I saw some 'locale' files but I'm not sure if it's fully implemented. If you like i could make/contribute to the italian translation. Let me know, thanks.

**Comment by proginosko** [comment]
Translations need a localized version of `messages.json` (see `_locales` folder) as well as localized versions of `blocked.html` and `delayed.html`. If you can create these and send them to leechblockng@proginosko.com, that would be great!

**Comment by starise** [comment]
Thanks. It's not easier to just clone the repo and send a pull request?

**Comment by proginosko** [comment]
Sure, that would be even better. You'll need to create `it` folders in the right places.
