### ISSUE TITLE
Suggestion: moving block sets

### ISSUE THREAD

**Issue by iliadaili** [proginosko/LeechBlockNG#208]
I had this idea for the implementation of the possibility to move block sets. The purpose of this feature would be mainly to make it easier for when I want to add a block that I wish takes precedence over another block that already exists.

**Comment by proginosko** [comment]
Yes, this would be useful. I think the simplest implementation would be to allow the user to swap two consecutive block sets (which would be equivalent to "move this block set to the right/left in the series"). I will add that to the "requested features" list.

**Comment by proginosko** [comment]
Added in version 1.3.
