### ISSUE TITLE
Setting privacy.resistFingerprinting to true breaks time periods for when blocksets are active

### ISSUE THREAD

**Issue by TooMuchofEverything** [proginosko/LeechBlockNG#209]
I noticed this issue when I was setting up hardened Firefox using FF Profilemaker. When I enabled resist fingerprinting for my profile, the time periods for my blocksets broke and seemed to only work on some start and end times. I also tried turning privacy.resistFingerprinting to true in about:config and the issue did manifest as well.

I had this same problem with another addon called Intention (similar to LeechBlock and others) so maybe the option itself is buggy. Unless I'm missing the point of privacy.resistFingerprinting, I don't think this should've broken addons like LeechBlock.

**Comment by proginosko** [comment]
Thanks for this report! This is a known issue (see #70). Basically, when resist fingerprinting is used, extensions can no longer get the local time (i.e., local time zone is hidden). The workaround is to use the "Offset clock" setting under General options.
