### ISSUE TITLE
Specified URL for Block-Sets not working

### ISSUE THREAD

**Issue by MortimerDoe** [proginosko/LeechBlockNG#21]
Since the update to LeechBlockNG, the redirection to a specified URL (in my case: to a html-file on my computer) does not work anymore. Instead, I end up on the Website I tried to connect to, even if it should be blocked. 
If I change the settings to the default block site, everything works well...
(except to the fact that my settings randomly reset as it has been described by other users in Issue #18)

Best Regards

Mortimer

**Comment by proginosko** [comment]
Unfortunately, Firefox (57+) no longer allows extensions to open local files in a browser tab. So the URL for the blocking page must either be within the extension itself (e.g., default page) or accessed via HTTP.
