### ISSUE TITLE
Some suggestions for blocking

### ISSUE THREAD

**Issue by funnym0nk3y** [proginosko/LeechBlockNG#214]
Hey, 

I like the idea of leechblock, but I have some suggestions which would perfect the experience for me. 

- The blur filter with 4px is too weak for 4K displays. Options to choose intensity of blur would be nice. 
- A combination of different filters would be nice too. E.g. blur, grayscale and mute #203 
- A delaying mode which makes the site really slow. I don't know how to put it right, but being instantly presented with completely blocked page feels like it is forbidden and it somehow triggers my circumvention instinct , whereas a page being unbearable slow just reduces my interest in it. I know it can be made really hard to circumvent leechblock, but that keeps me from activating it in the first place. I'd rather use it reduce interest in some sites. 

EDIT:
- Would be nice to be able to relock before override period ends.

**Comment by proginosko** [comment]
Added some more filter options in version 1.0.13.

**Comment by proginosko** [comment]
Closing this for now. Feel free to post as separate feature requests under Discussions/Ideas.
