### ISSUE TITLE
Exporting Chrome Block:extensions doesn't import block:addons in Firefox

### ISSUE THREAD

**Issue by pwintz** [proginosko/LeechBlockNG#215]
In Chrome, I had a block set that blocked extensions at certain times. When I exported my Leechblock settings from Chrome and imported into Firefox, I expected that setting to be translated into blocking the addons page, but it was not. Is this intentional?

**Comment by proginosko** [comment]
It wasn't intentional. It's just the consequence of the fact that the options have different names in the code. But it wouldn't be much trouble to have them translated between Firefox and Chrome. I'll add that to a future version.

**Comment by proginosko** [comment]
Fixed in version 1.5.2.
