### ISSUE TITLE
LeechBlock no longer unblocks after about:config edits for privacy

### ISSUE THREAD

**Issue by TdXYZ** [proginosko/LeechBlockNG#216]
On Firefox I made some adjustments to the about:config to increase privacy according to https://privacytools.io/browsers/#about_config.

Ever since then LeechBlock hasn't been working properly. It still blocks sites as it should when the scheduled time arrives, but the block still persists even after the blocking time frame is over and unblocking is no longer possible.

I tried to revert some of the about:config adjustments, but it didn't do anything and I can't figure out which of them causes the problem. Can this be fixed? If not, which tweaks do I have to do in the about:config to restore proper functionality?

**Comment by proginosko** [comment]
Did you set privacy.resistFingerprinting to true?

**Comment by TdXYZ** [comment]
Yes. I didn't try reverting that one though as I didn't think that that one could be the cause. I'll try doing that later and report back if that fixes the issue.

**Comment by proginosko** [comment]
That's probably the cause. See #209 and #70 for details.

**Comment by TdXYZ** [comment]
I adjusted the offset clock as detailed in the other issues and it solved the problem. Thank you very much.
