### ISSUE TITLE
Can't specify a filepath url.

### ISSUE THREAD

**Issue by gertrud-af-svaneholm** [proginosko/LeechBlockNG#217]
Hi! Lovely extension!
I'm having a tiny error though.
I'm using firefox and I want to show a picture stored as a local file by using the " Enter the fully specified URL of the page to show instead of these blocked sites: " option. When I do this in chromium it works as expected but in firefox the website list is not blocked when I specify a filepath. Access to the block menu is prevented as expected and the block set works fine when I specify a "normal" url but when a filepath is specified I can use the websites as if nothing happened.

**Comment by proginosko** [comment]
Unfortunately Firefox's security model prevents extensions from opening local files. It has to be an http/https protocol. One workaround would be to use a simple webserver on the local machine. Some cloud servers might also support HTML pages.

**Comment by gertrud-af-svaneholm** [comment]
Ok, thanks!

**Comment by JorgeMadson** [comment]
Sorry for bump this top this, but it would be awesome if I can add a phrase to the block page. Or edit it.
I want to block some porn websites and I want to add  a motivational phrase to not break my nofap journey.

**Comment by proginosko** [comment]
The blocking page shows the name of the set, so perhaps change the set name to the phrase you want to see!

**Comment by JorgeMadson** [comment]
Thank you, I will do it!
