### ISSUE TITLE
All url's fail 'correct format' verification ; unable to initilze leechblock

### ISSUE THREAD

**Issue by keithmacinnis** [proginosko/LeechBlockNG#218]
Firefox 89.0.2 (64-bit)
MacOS 11.4

I am unable to set this plugin up as the format for websites is a mystery to me:

<img width="672" alt="Screen Shot 2021-07-24 at 10 47 55 AM" src="https://user-images.githubusercontent.com/6054402/126876976-21fa65d5-187f-4a3d-8461-34960fb6ef9d.png">
<img width="671" alt="Screen Shot 2021-07-24 at 10 47 36 AM" src="https://user-images.githubusercontent.com/6054402/126876978-a1be439c-568b-400f-8b26-0575096a1bee.png">
<img width="604" alt="Screen Shot 2021-07-24 at 10 47 19 AM" src="https://user-images.githubusercontent.com/6054402/126876979-a5a4f5a5-b7f9-4f1b-982e-979d39facff8.png">

**Comment by proginosko** [comment]
In the list of sites, you only need to specify the domain name (`facebook.com` is enough). But for the blocking page, you need to specify the entire URL, because it may or may not be an external web page. In your case, you should enter `https://www.google.com`.

**Comment by keithmacinnis** [comment]
Hmm, I wonder why mine does not function then :/

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6054402/126914108-36ae26c5-b3e5-4f53-bba3-c49c75e1a1c9.png">

**Comment by proginosko** [comment]
You haven't specified when to block. You need to enter a time period, a time limit, or some combination of the two.

**Comment by keithmacinnis** [comment]
Ok that worked, but it's counter to the forms directions with the labelling of these fields as optional. 

Could I make a suggestion ?
We could remove the drop down menu for choosing And || Or (Which on it's own is confusing)
Then Just have those two fields listed as optional, and use the following form logic:
Case 1) If user inputs anything in field timePeriod && nothing in field timeLimit => It's an OR block
Case 2) If user inputs nothing in field timePeriod && anything in field timeLimit => It's an OR block
Case 3) If user inputs anything in field timePerod && anything in field timeLimit => It's an AND block
Case 4) If user inputs nothing in field timePeriod && nothing in field timeLimit => it's a 24/7 block

**Comment by proginosko** [comment]
Thanks for the suggestion, but I don't think that will work, for two reasons. (1) Some users want a combination of time periods and time limits but with the OR combination of the two. (2) If I implemented the above, it could change the blocking behavior for many users unexpectedly and inexplicably (from their point of view). I realize that the current UI isn't ideal, but once you understand it, it works just fine for most users.
