### ISSUE TITLE
Support For Pale Moon (Firefox Fork)

### ISSUE THREAD

**Issue by noellarkin** [proginosko/LeechBlockNG#219]
Hey!

Thanks for the amazing work on this plugin, I've used it on Firefox and it works really well. However, I've recently shifted to Pale Moon browser (which is a fork of Firefox) and the extension isn't working on Pale Moon.

It seems that Pale Moon, and many related browsers (Basilisk, Sea Monkey, IceCat, K Meleon) use the XUL framework, as opposed to WebExtensions.

I'd really appreciate it if you could make a Pale Moon compatible plugin. I'd love to be able to continue using your plugin.

**Comment by proginosko** [comment]
XUL is legacy technology now, so it doesn't make sense to develop a XUL version of LBNG. However, the original LB extension used XUL, so you might still be able to use that with Pale Moon. The last released version (Nov 2017) can be downloaded [here](https://www.proginosko.com/files/leechblock/leechblock-1.0.9.xpi). The code is available on GitHub [here](https://github.com/proginosko/LeechBlock).
