### ISSUE TITLE
Load list of sites from URL

### ISSUE THREAD

**Issue by aicoutos** [proginosko/LeechBlockNG#22]
I did the following:
1. I removed the leechblock ng 0.6
1. I installed leechblock ng v0.7b1
1. I imported as URL via http
1. I set the days
1. I saved

the following error was occurred:
1. the urls appeared in the list with the names of the sites to block
1. the extension not blocked any of the sites in the list

**Comment by proginosko** [comment]
Thanks, I will look into this. Would you mind sharing the URL so I can test your scenario? (You can email it privately to leechblockng@proginosko.com.)

**Comment by proginosko** [comment]
Don't worry -- I found the bug and fixed it.
