### ISSUE TITLE
Misses tabs opened after initial load

### ISSUE THREAD

**Issue by wasuregusa18** [proginosko/LeechBlockNG#221]
Quit firefox, then right after start it again, if you start a page loading and then open some new tabs i.e. so that the first page gets loaded in the background, leechblock doesn’t notice the page (until refresh). (see video)

https://user-images.githubusercontent.com/73337508/131229773-d5f8e8ef-adcc-40c0-9cbe-4e7b00864c36.mp4

**Comment by proginosko** [comment]
Yes, if you open a tab fast enough, LB will miss it, because it takes Firefox some time to load and initialize the extension. Workaround is to select the option "Immediately block pages on these sites once blocking conditions are met".

**Comment by wasuregusa18** [comment]
See options below: I have the option "Immediately block pages on these sites once blocking conditions are met" selected and the above behaviour still occurs. 
![Image 2021-08-29 09-20-36](https://user-images.githubusercontent.com/73337508/131243887-98d46b42-5669-4c21-ac4f-c48bcba410cc.jpg)

**Comment by proginosko** [comment]
Hmm. Could be related to #201. I'll look into it.

**Comment by proginosko** [comment]
I'm assuming this was fixed in v1.5.1. Reopen this issue if the problem recurs.
