### ISSUE TITLE
Suggestion: Option at the right click menu that allows to block specific parts of a website instead of the whole website.

### ISSUE THREAD

**Issue by gelatinbomb** [proginosko/LeechBlockNG#223]
First of all thanks for this extension. It's surprisingly complete in comparison with other options.
As you see on the title I think an option like that could be useful. Sometimes I need to blocks parts of one website because I need the rest of it so I have to add the specific section that I will block. 
The problem is I like to set leech-block as difficult to access so I don't deactivate the extension and start procrastinating. As you might imagine accessing the options menu is not the most optimal solution in that situation.
I prefer that right click menu option because it lets me block pages easily without allowing me to change the settings of the extension.
So an option to block specific parts of an website could help to do that like you do on the main options page but in the right click menu options.
Thanks for reading.

**Comment by proginosko** [comment]
Thanks for this suggestion. I plan to add something like this to a future version.

**Comment by gelatinbomb** [comment]
Just came here to thank you. I just saw the new panel on the right click menu. Nice!

**Comment by proginosko** [comment]
I'm also considering adding a more flexible "Add Item to Block Set" option that will allow you to type in (or copy-paste) any site or page to add to a block set without going into the options. Not sure when that will happen, but I'm glad to hear the "Add Page" menu item is a useful addition.

**Comment by proginosko** [comment]
Closing this for now. Feel free to post a fresh feature request under Discussions/Ideas.
