### ISSUE TITLE
request (or help): I want to hit a button confirming going ahead

### ISSUE THREAD

**Issue by wolftune** [proginosko/LeechBlockNG#231]
So, when I visit a blocked site, I want an option to have to say "yes, I want to continue" or similar. That would be better than just a delay that automatically reloads the site. The delay should be the time before hitting the button is allowed.

Is that possible already? If not, I'd like it. Similar to https://addons.mozilla.org/en-US/firefox/addon/pawblock/ (which is usable but lacks most of the robust controls and dark theme and other stuff from LeechBlock)

Put another way: **I want delay + manual reload**. After the delay, I don't want the reload to be automatic. I'd prefer a button with a label I can set.

**Comment by wolftune** [comment]
I guess this might be duplicate of https://github.com/proginosko/LeechBlockNG/issues/184

Not precisely. If the capacity for a customizable button for manual reload existed, it could potentially be mixed with whatever other features.

**Comment by wolftune** [comment]
Okay, sorry for noise. I see the forum now, and this topic is similar too https://www.tapatalk.com/groups/leechblock/override-link-on-blocking-page-t456.html

The other requests are missing the idea of customizable button, so I can say "I have a whole-body yes to going to this site" or whatever.

I do find the override process nicely tedious and a lot of friction. But override is for the whole of LeechBlock. I want to override only for the one domain and only for the session until that domain is closed.

**Comment by proginosko** [comment]
Added in version 1.5.3 (but instead of a button, you have to click on the link to the page).
