### ISSUE TITLE
[Feature Request] More informative 'override activated' message

### ISSUE THREAD

**Issue by DMR-coding** [proginosko/LeechBlockNG#235]
When overriding is enabled in general options, each block set still does not allow overriding by default. This can be confusing when you activate the override, get the message that blocking will now be suspended, but in practice all blocking is still active because no sets are included.

It would be useful if the message which appears after activating override specifies which sets are actually overridden.

E.G. "Override activated. Blocking will be suspended for Block Sets 2, 3, and 5 until 2:05:57 PM."

or "Override activated until 2:05:57 PM; however, none of your Block Sets can be overriden."

**Comment by proginosko** [comment]
Looks like you need to select the option "Allow temporary override for these sites".

**Comment by DMR-coding** [comment]
Oh, I see... I didn't realize that was controlled per set. Let me edit this to a feature request that would make that clearer...

**Comment by proginosko** [comment]
There is this:

![image](https://user-images.githubusercontent.com/16375152/154768069-0f3233e7-e31f-4c77-82bd-56b92ddc24f8.png)

What else do you think would help?

**Comment by DMR-coding** [comment]
I've edited the description of this ticket to my proposal. Basically, I think it would be useful to expose at the time of actually activating an override which sets it has taken effect for.

**Comment by Tsarpf** [comment]
That option is way too hidden, after uninstalling the add-on several times due to frustration with overriding not working, trying to google the problem a couple of times, now I came to make a bug report but found this.

Perhaps the "overriding activated" window should show a hint that you need to specifically enable this.
