### ISSUE TITLE
[Feature Request] Add a separate text field for adding new items to blocklists

### ISSUE THREAD

**Issue by jaintj95** [proginosko/LeechBlockNG#238]
Right now, the block list is a single large text box. However, this means that I cannot add new items to the list when blocks are active. 
Not being able to edit, update lists during blocks is fine because it stops me from trying to access sites I've blocked. 

However, I should be able to add new sites to blocklist because I am only trying to reduce distractions

**Comment by proginosko** [comment]
You can currently add a site to a block set using the context (right-click) menu on the website itself. I plan to add another option in a later version so that you can add sites manually without entering the options. Stay tuned!

**Comment by YuriiZhydetskyi** [comment]
@jaintj95 can this issue be closed? Looks like block by using the context menu is a good solution.
