### ISSUE TITLE
[Feature Request] Reset roll over time

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#241]
I got a long roll over time after tweaking the rules and I don't know how to reset it.
It's probably a good idea to add a way to reset it.

**Comment by proginosko** [comment]
Thanks for the suggestion. The workaround for now would be to change your time period to something short (5 mins), wait for the next time period, and then change back the time period to whatever you want it to be.

**Comment by proginosko** [comment]
Added in version 1.5.2.
