### ISSUE TITLE
[Feature Request] Roll over time upper limit

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#242]
It might be a good idea to add a roll over time upper limit option to encourage people to do things at healthier intervals without disabling the roll over mechanism completely.

For example, I want to use social media only for a maximum of 30 minutes every 6 hours, but I want to use the rollover time because I want to have longer interaction there occasionally, but I also don't want to accidentally accumulate several hours of rollover time and makes the tool pointless.

**Comment by proginosko** [comment]
The rollover time isn't cumulative. You only get credited the unused time from the previous time period.
