### ISSUE TITLE
[Bug] Putting a colon in a keyword means that rule will always match

### ISSUE THREAD

**Issue by JessFairbairn** [proginosko/LeechBlockNG#249]
Adding the keyword `~foo:bar` as a blocking rule, or any other keyword containing a colon means that rule will always be matched, regardless of whether the string is actually on the page or not.

Discovered this trying to be clever and trying to add `Template:Navbox_musical_artist` to stop me wasting time on Wikipedia by blocking all articles about musicians. Admittedly including non-alphanumeric characters as a "keyword" is probably stretching the original aim of that feature but this was still a strange behaviour.

**Comment by fmorroni** [comment]
Hi, I tried this after reading your post and interestingly it produces the opposite effect on my side. If I add a keyword with a colon no sites will be blocked even if they match other keywords. And as soon as I remove the colon from the keywords the sites start getting blocked normally again.

**Comment by proginosko** [comment]
This should be fixed in version 1.5.

**Comment by JessFairbairn** [comment]
Oh wonderful thank you!
