### ISSUE TITLE
do not block links that are bookmarked

### ISSUE THREAD

**Issue by mleue** [proginosko/LeechBlockNG#25]
Hey there,

First of all: thanks a lot for this great firefox extension, it really helps me stay on track throughout the day.

One thing I'd love to see is an option for a block set to not block links that are bookmarked. 
Basically that's links that might come from blacklisted sites but that I deemed important enough at some point in the past to wait for leechblock to load (i.e. waiting until my countdown ran out) and then actively marked to be important enough to revisit again in the future.

It would basically be like a new way of quickly marking a specific link to be whitelisted.

What do you say?

I could also do it myself (I don't know the specifics of accessing bookmarks in web extensions but I'm sure one should be able to grab them as a hash-table set and then be able to do O(1) membership testing) if you point me towards where the necessary changes would have to be made (I assume both somewhere in the blocking pipeline and then a UI toggle in the block set settings).

Thanks in advance.

**Comment by proginosko** [comment]
Thanks for a good suggestion! I haven't grappled with the bookmarks API yet, but it shouldn't be too difficult to implement. I'll consider adding it in a future version.
