### ISSUE TITLE
"Load list of sites from URL" doesn't work in Firefox for Android

### ISSUE THREAD

**Issue by imkaihao** [proginosko/LeechBlockNG#250]
The FAQ says the list will be loaded when the browser is first started and also when the options are changes.
But neither works in Firefox for Android.

**Comment by proginosko** [comment]
I just tested it, and it seems to work. Try using this URL and see if it works for you:

https://www.proginosko.com/files/sites.txt

**Comment by imkaihao** [comment]
Thank you. It works now.
