### ISSUE TITLE
Always apply filter (e.g. grayscale) regardless of remaining time

### ISSUE THREAD

**Issue by VFansss** [proginosko/LeechBlockNG#253]
Hi!

First of all: AMAZING PLUGIN, can't describe how much I'm happy to have found something that comply with my (high) requirements for a software 😄 

I'm messing with the plugin (is my first time with it) and I've found the "Apply filter instead of blocking page" option.

I would like to keep the classic "block" option (so when time's over...that's over!) but keeping the grayscale always on regardless on how much time remains.

Why? It would discourage the using as much as possible, without having to resort to blocking the website entirely.

Probably there are other plugins to realize this, but would make LeechBlock even more feature-complete for a sane use of web (what a bad place, btw).

Is it possible without messing too much with the code?

**Comment by VFansss** [comment]
You're right!

The only downside is that, for the "blocking set", now I can't see the remaining time probably because, somehow, the second block set (the "always on" to greyscale the page) tell the plugin that the times already run out.

It's a minor downside, and I can live with it honestly.

If is not a feature that would be good to have, I guess we could close the Issue (maybe we can add it to the FAQ? I'm sure it would be useful for someone else)

Also, thanks for your quick answer!

**Comment by proginosko** [comment]
Yes, that's the downside. LB will show the lowest time left of all the block sets that apply to the current page. In this scenario, that will always be 0:00 because the filter is always active.
