### ISSUE TITLE
Wrong unblocked time calculation: 12 am insteam of 3 am

### ISSUE THREAD

**Issue by d9k** [proginosko/LeechBlockNG#257]
Settings: When to unblock:

```
Enter the time periods within which to block these sites (optional): 0000-2400
Enter a time limit after which to block these sites (optional): 30 minutes in every 3 hours.
```

30 minutes elapsed at 23:50

Expected unblocked time: `3 am`
Actual unblocked time: `12 am`

My timezone: `GMT +3`

Settings screenshot:

![Screenshot from 2022-08-04 00-34-43](https://user-images.githubusercontent.com/7331988/182716654-3a26b148-991a-421c-99fe-d710b59c00ef.png)

Leechblock block page screenshot at `0:35`:

![Screenshot from 2022-08-04 00-34-16](https://user-images.githubusercontent.com/7331988/182716727-640bea89-33f7-4b29-a8a2-d6422f57b857.png)

**Comment by d9k** [comment]
If I temporary set 

```
Enter a time limit after which to block these sites (optional): 30 minutes in every 4 hours.
```

I temporary get

```
The page will be unblocked at: 1:00:00 AM
```
on block page

**Comment by proginosko** [comment]
Please try this: go to the LeechBlock Options page, open the browser console (Ctrl+Shift+I), enter `new Date();` at the prompt, and see if the return value gives you the correct date and time.
