### ISSUE TITLE
Refresh website automatically after blocking period is finished!

### ISSUE THREAD

**Issue by de-gozaru** [proginosko/LeechBlockNG#259]
Hi,

Thanks for the great tool!

I'm using LeechBlock to block my email website all the morning 0800-1200. But after the period of blocking is finished, the website doesn't refresh automatically, and shows the icon of the website instead of Leech icon, which makes me to forget to check my emails as I think they are still blocked.

Is there a way to automatically refresh websites after blocking period is finished, so that their icon appears?

Thank you in advance!

**Comment by proginosko** [comment]
You can get the same result with the option "Attempt to reload blocked page every __ seconds" (30 is a good value).

**Comment by de-gozaru** [comment]
that worked for me, closing the issue!
