### ISSUE TITLE
Settings disappear after a reboot

### ISSUE THREAD

**Issue by IrisLev** [proginosko/LeechBlockNG#26]
OS: WIndows 10

BROWSER: Firefox Quantum 57.0.3 (has AdBlock installed)

SCENARIO:
1. Install LeechBlockNG
2. Set blocking some site after a certain amount of time
3. Reopen Firefox to verify the settings are saved
4. Reboot the PC
5. Open Firefox, LeechblockNG settings

EXPECTED RESULT: the settings are there
ACTUAL RESULT: the settings are gone

**Comment by proginosko** [comment]
Thanks for reporting this issue. A few diagnostic questions:

1. Which version of LB do you have installed?
2. Is the problem reproducible? Does it happen every time you follow the scenario above?
3. Did you close all Firefox windows before rebooting the PC?
4. When you open the LB options page (step 5) do you get any error message? Or do you just get the options page with all fields blank?

**Comment by loorlab** [comment]
+1

WIN 10
Firefox Quantum 57.0.4
LeechBlock NG  0.8

Is the problem reproducible? Does it happen every time you follow the scenario above? --> Yes, The created site block disappears, the options are reset.

Did you close all Firefox windows before rebooting the PC? --> Yes

When you open the LB options page (step 5) do you get any error message? Or do you just get the options page with all fields blank? --> No error message appears, all options are blank, it does not save the values.

Please check this, thanks !
Nice Tool !

Regards

**Comment by proginosko** [comment]
Thanks, that's useful (and weird). Try this: uninstall LB, restart Firefox, reinstall LB. Now see whether you still experience the problem.

**Comment by loorlab** [comment]
@proginosko Hi my friend, The steps you give us work well.

Thanks !

PD: Any anomaly we will report.

Blessings !

**Comment by proginosko** [comment]
Thanks. Are you reporting that the problem is resolved for now?

**Comment by loorlab** [comment]
@proginosko Yes !

Regards !

**Comment by IrisLev** [comment]
Hi,

1. When I opened the bug, it was LeechblockNG 0.7. At the moment it's 0.8.1
.
2. With the previous version the problem was reproducible. Today I rebooted
my PC and the issue didn't reproduce. But this is a newer version
3. I don't remember
4. No error messages, just blank fields

I guess, the bug doesn't reproduce in the new build.

Regards,
   Iris Zarakhovsky
