### ISSUE TITLE
Sync Storage options appear/disappear in Firefox Android

### ISSUE THREAD

**Issue by sherrmann** [proginosko/LeechBlockNG#266]
Hi, I don't see the Sync Storage options in the Firefox for Android settings.
However, as soon as I load a settings file, the Sync Storage options are shown.

**Comment by proginosko** [comment]
Sync storage is not yet supported on FF for Android, so that's why the options are hidden. If they become visible after loading options from a file, that's a bug that needs to be fixed. 🙂

**Comment by proginosko** [comment]
Here's the Bugzilla thread if you want to monitor it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1625257
