### ISSUE TITLE
Blank Options Page

### ISSUE THREAD

**Issue by Paljassie** [proginosko/LeechBlockNG#27]
As per you request. When I click on options or any other button, I just get a blank page. When I add a page by right-clicking, it does add the page. This is extremely frustrating as I can't remove page I no longer want to block or customize anything.

I am using FireFox 56 and not really interested in 57 at the moment. I have installed it previously. It is slower than any other browser and 75% of extensions are not working.

I will use the older version of LeechBlock for as long as possible. A pity the NG version is not working on 56. I have tried every fix I can't think of, but nothing. It takes me to the following browser page, but it is completely blank. I have unistalled all versions on LeechBlock restarted the brower and installed NG version again and exactly the same result.
moz-extension://50e94f05-c49b-4028-9911-02822f437220/options.html

**Comment by Paljassie** [comment]
![image](https://user-images.githubusercontent.com/35251031/34707621-2edb54f6-f517-11e7-9894-626cb022beeb.png)

**Comment by proginosko** [comment]
Thanks for this report. Which OS are you using and exactly which version of Firefox?

You can try the following to help me figure out why the options page isn't loading properly:
1. Open the Browser Console in Firefox (Ctrl+Shift+J).
2. Select to show JS (JavaScript) entries only (use the selectors at the top of the console).
3. Clear the console (click trashcan button).
4. Open LeechBlock options.
5. Go back to the console window, look for any errors generated by **options.js**, and report them here.

**Comment by Paljassie** [comment]
I have upgraded to FF 58 and will see how it performs. So far, not very impressed with FF so thinking of moving over to Chrome.

**Comment by proginosko** [comment]
Okay. LeechBlock is available for Chrome too now! 😃
