### ISSUE TITLE
Override does not work in Firefox

### ISSUE THREAD

**Issue by codeulike** [proginosko/LeechBlockNG#270]
Hi I've got Firefox 104.0.2
And Leechblock NG 1.5.1

The "override" feature doesn't seem to work in Firefox.

Steps to repoduce:
- In Firefox with Leechblock active
- Click on green Leechblock icon
- Click Override
- Enter minutes (e.g. 10) and press Activate Override
- Window pops up saying 'Override activated....'
- In another tab, try to go to usually blocked site (e.g. facebook)
- Site is still blocked.

**Comment by proginosko** [comment]
Did you select the option "Allow temporary override for these sites" for the relevant block set(s)?

**Comment by codeulike** [comment]
No. 
Sorry.
