### ISSUE TITLE
Leechblock (firefox) doesn't work unless I disable and re-enable it

### ISSUE THREAD

**Issue by supdoodle** [proginosko/LeechBlockNG#271]
Hi there!

Every time I put my laptop to sleep and then wake it up to use it, Leechblock doesn't work on Firefox. When I visit the Extensions page, it says it's enabled. If I disable it and re-enable it, it works.

Please excuse any bad GitHub etiquette; I've never used the site before.

I hope you're having a great day!

**Comment by proginosko** [comment]
Is the Firefox window still open when you put the laptop to sleep?

When you say that LB doesn't work, can you be more specific? Perhaps give an example of what you would expect to see that you're not seeing after you wake the laptop.

**Comment by supdoodle** [comment]
Yes, the Firefox window is open while my laptop sleeps.

What I mean is, when I go to a website that is on my "delayed" list, it doesn't bring up the delay page. If I go to a website on my "blocked" list, it doesn't go to the blocked page. It just allows me to access any website with no delay or redirect. 

After I toggle the switch on the about:addons page, it then delays and blocks as expected.

**Comment by proginosko** [comment]
Which OS are you using?

**Comment by supdoodle** [comment]
I'm using Windows 10 Home, build 19043.1826, 64bit (not sure which of those are relevant). 

For the last week or so, though, LeechBlock has been working as expected. It blocks and delays sites as usual, even after I close and open my laptop.

**Comment by proginosko** [comment]
Okay, good. I'll close this for now, but reopen it if the problem returns.
