### ISSUE TITLE
Access Control Password should be Masked too!

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#276]
Please mask the Password for the Access Control in the General tab like you do for Temporary Override. This would protect it from onlookers.

I also believe it should not be part of the export file, just like the Temporary Override password is not exported either.

Please correct these.

**Comment by proginosko** [comment]
Thanks. Both passwords are included in the export file. Why should they not be?

**Comment by smayer97** [comment]
The masking is not about the export file. This is about the Options page in LeechBlock. The latter is masked, the former is not. So, I am asking that the Access Control one be masked too.

Regarding the export file, for some reason, I only get the Access Control exported. So it this a potential bug?

As for why they should not, that creates a potential breech by exposing sensitive information. Maybe provide the option as to whether or not to export them?

**Comment by smayer97** [comment]
So, are you willing to consider the masking of the Access Control password to be implemented, please?

**Comment by proginosko** [comment]
Yes.
