### ISSUE TITLE
Bugged when two delay pages are applied at the same time

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#282]
The countdown just keeps alternating between different delay pages and never ends.

**Comment by proginosko** [comment]
What do you think should be the expected behavior in that case?

**Comment by gepz** [comment]
I think the same delay page should not be shown again before the user get into the web page they want to see.

Might also be a good idea to fuse multiple delay pages into one and make them countdown at the same time.

**Comment by proginosko** [comment]
I would have thought the expected behavior would be that only the first delay (in the order of block sets) takes effect.

**Comment by gepz** [comment]
Well, different delays might have different countdown time and different options.
Counting down together would have the effect as only applying the first one when all of them are identical.

**Comment by proginosko** [comment]
Duplicate of #173.
