### ISSUE TITLE
Default theme should respect dark/light mode setting of browser 

### ISSUE THREAD

**Issue by real-or-random** [proginosko/LeechBlockNG#284]
It would be awesome if the default theme respected the respect dark/light mode setting of the browser. 

At the moment, the "block" page is fully white, which looks awkward in a dark mode browser. (Though that adds to the "warning" effect. ;))

**Comment by proginosko** [comment]
Thanks for the suggestion. Right now, I don't see any way for the extension to detect which theme the browser is using. I'll keep looking. In the meantime, are you aware that you can manually set a dark theme from the LeechBlock options?

**Comment by real-or-random** [comment]
Thanks for the quick reply!

> Right now, I don't see any way for the extension to detect which theme the browser is using.

I'm not at all an expert here, but given that normal websites can change theming based on the browser setting, I'd toally expect that an extension can do the same. See here for more info: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

For reference, I'm using LeechBlock NG in Firefox, which has a setting for light vs dark (which defaults to "automatic" = use whatever the OS suggests).


> In the meantime, are you aware that you can manually set a dark theme from the LeechBlock options?

Yes. The thing is that I often switch between dark and light mode globally, and it would be too much to open the LeechBlock options everytime. But I figured that the green "Sprout" theme is nicely in the middle and looks okay on either setting.

**Comment by real-or-random** [comment]
Thanks, works like a charm!

**Comment by real-or-random** [comment]
> Thanks, works like a charm!

Actually, no. It works in the options, but not on the blocking page. Can you reproduce this?

**Comment by proginosko** [comment]
Dang, you're right. How'd I miss that? I'll get that fixed!
