### ISSUE TITLE
Not blocking Youtube Music

### ISSUE THREAD

**Issue by shyam2520** [proginosko/LeechBlockNG#288]
While the extension block all other sites well it hasn't been able to block **https://music.youtube.com/**  even after adding it to my block list

**Comment by proginosko** [comment]
Please post your block list here (or email it to leechblockng@proginosko.com if you prefer).

**Comment by shyam2520** [comment]
Mailed

**Comment by proginosko** [comment]
Thanks for sending the block list. I tested it on my setup (Firefox on Windows 10) and it blocked music.youtube.com as expected. Are all the other sites in the list blocked as expected?

**Comment by shyam2520** [comment]
Yes only this YouTube music doesn't work everything else works

**Comment by shyam2520** [comment]
Could you try firefox on Manajro Linux does that OS  actually make any
difference?

**Comment by proginosko** [comment]
It shouldn't make a difference. Please export your settings to a text file (Options > General > Export Options to File) and email it to me at the address above so I can take a closer look.

**Comment by proginosko** [comment]
Thanks. I see the problem now. As some point you must have entered a regular expression in the field "Use regular expression to match URLs to block" (under Advanced Options). You probably clicked the "Generate From Site List" button. But that field overrides your site list, so when you later added music.youtube.com it was ignored. Just clear that regular expression field and everything should work as expected.

**Comment by shyam2520** [comment]
Yes, I remember now. Thanks a lot it worked now. Your extension is amazing.
Are we allowed to make PRs for the extension ?

**Comment by proginosko** [comment]
Anyone is welcome to submit a PR, but if it makes major changes to the functionality of the extension it will probably take a while before I can properly test and approve it.
