### ISSUE TITLE
Low resolution icon

### ISSUE THREAD

**Issue by quackerex** [proginosko/LeechBlockNG#289]
Leech block options page has a low resolution favicon. A similar low res icon can be seen on the extensions panel in Firefox.

<img width="621" alt="comparison between favicon on option page and on the website" src="https://user-images.githubusercontent.com/41659980/216859483-eaefb51d-726e-4da9-9979-8e012559f448.png">

<img width="511" alt="Firefox extensions panel" src="https://user-images.githubusercontent.com/41659980/216860138-01ab69eb-c932-4b41-9cca-5da80a8c19b9.png">

**Comment by proginosko** [comment]
Thanks! I didn't realize that. I'll get that fixed.
