### ISSUE TITLE
Advanced options not working

### ISSUE THREAD

**Issue by leem32** [proginosko/LeechBlockNG#29]
None of the advanced settings are working for me i.e 
Prevent access to options for this block set at times when these sites are blocked
Prevent access to about:addons at times when these sites are blocked
Prevent access to about:support at times when these sites are blocked

Is this a known bug??

OS: Windows 7
Browser: Firefox 57.0.4

**Comment by proginosko** [comment]
This is the first report of this issue. Are the settings saved when you change them? If you change those settings, close options, and reopen options, are the changes preserved?

**Comment by leem32** [comment]
Strange, I've just checked again and it looks to be working now. Both about:addons and leechblock options are disabled.

Yes the settings where saved, but nothing was happening. I could still get to about:addons and change the leechblock settings.

Great addon by the way. I use it daily :)

**Comment by proginosko** [comment]
Okay, good. BTW, those settings are only applied when the block is active, not all the time. You probably knew that, but I'll mention it just in case. If the problem resurfaces, reopen the issue here.

**Comment by leem32** [comment]
Just realized the issue with the advanced options not blocking about:addons and leechblock options is caused because I have a 5 Minute time limit before the blocks kick in. 

Is there any way to keep the 5-minute time limit before sites are blocked, but block about:addons and Leechbock options immediately when the time period for blocking begins?

The problem is that I may not even use up the 5-minute time limit for the time period so about:addons and Leechblock options will never be blocked.

I can obviously just remove the time limit, but I prefer not to.

Thanks :)

**Comment by proginosko** [comment]
As a workaround, you could set up a second 'dummy' block set with the same time period, and select the "Prevent access" options for that set instead. Make sure you put _something_ in the site list though (e.g., foobar.com) otherwise the block set will be ignored.

**Comment by leem32** [comment]
Ah, good idea. I'll do that. Thanks
