### ISSUE TITLE
Move Set symbol is not showing

### ISSUE THREAD

**Issue by quackerex** [proginosko/LeechBlockNG#290]
Move Set symbol is not showing on Firefox running on macOS.

<img width="732" alt="Leechblock option page" src="https://user-images.githubusercontent.com/41659980/216860476-fd550bc9-e28b-4958-903c-358c8c1aa5cd.png">

**Comment by proginosko** [comment]
Interesting. What do you see on the line below? (It should be two arrows.)

&#x2BC7; &#x2BC8;

**Comment by proginosko** [comment]
Thanks, that's very helpful.

**Comment by proginosko** [comment]
How do these look? I'm experimenting with some other options.

&#x2190; &#x2192;

**Comment by proginosko** [comment]
Thanks. Yes, it does seem to vary quite a bit depending on the font.
