### ISSUE TITLE
APP not working

### ISSUE THREAD

**Issue by DestinationAI** [proginosko/LeechBlockNG#291]
I really like your app; very useful and customizable!

However, it seems February 9 update (v1.53) somehow disable its function on my Windows 10 PC. 
> The diagnostics show that it is identifying block sites, but the timer shows up both on the tool bar icon and upper left hand portion of screen with 0.00 and it does not actually block any of the sites on clocked list 

Meanwhile I have the same exact settings (I import them from my Win10 PC) on my Windows 7 Pro PC; including same browser Firefox version 110.0 and it works fine!

![firefox_1yEt1WWnDp](https://user-images.githubusercontent.com/56764206/221925764-57a05b49-b5c4-47bc-9e14-27762eb19c1d.png)

**Comment by proginosko** [comment]
Do you use keyword blocking in your list of sites?

**Comment by DestinationAI** [comment]
No I don't

**Comment by proginosko** [comment]
Please export your options to a text file (Options > General > Export Options to File) and email it to me (leechblockng@proginosko.com) so I can take a closer look.
