### ISSUE TITLE
Clock seems to use wrong time zone

### ISSUE THREAD

**Issue by helmbold** [proginosko/LeechBlockNG#293]
If I enter `0900-1200` in the field "Enter the time periods within which to block these sites (optional):" the blocking starts only at 10:00, so exactly 1 hour too late. I'm in the GMT+1 time zone (Germany).

Same happens if I override the  blocking time.

**Comment by proginosko** [comment]
Do you have resist fingerprinting enabled?

https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting

**Comment by matt-beamish** [comment]
Can confirm this issue was resolved for me by disabling resist fingerprint.

**Comment by helmbold** [comment]
You're right, I've enabled the fingerprinting protection in Firefox! So, I have to decide whether I want to protect my privacy a bit more or to be able to configure blocking times correctly, right?

**Comment by helmbold** [comment]
Thanks. I wasn't aware of this setting.

Would it be possible for the plug-in to show a warning if the finger printing protection is enabled?

**Comment by proginosko** [comment]
It's possible, but I'm not sure where or how such a warning would be displayed. It isn't easy for regular Firefox users to activate the "resist fingerprinting" option (you have to go to about:config and change the preferences) and I'm inclined to think that those who do ought to be aware of the consequences!
