### ISSUE TITLE
Some sites are blocked, others are not...

### ISSUE THREAD

**Issue by pderby1** [proginosko/LeechBlockNG#295]
Dear listmembers,

I would like to block ALL websites,
except the ones with the (+) sign.

However some are working,
and some are blocked when they should not be,...

For example the Tradingview.com website is blocked.
So are the ones about Chatgpt.

Any ideas to help please ?

All the best
Peter
![1](https://user-images.githubusercontent.com/129307065/228583863-80101efd-2e54-4546-95a7-9fffb12a3a59.jpg)

**Comment by proginosko** [comment]
Remove "https://" from those lines. You only need to give the site domain name, not the full URL.

**Comment by pderby1** [comment]
Thank you very much
