### ISSUE TITLE
Whitelist a website 

### ISSUE THREAD

**Issue by pderby1** [proginosko/LeechBlockNG#296]
I would like to access chatGPT during cerain hours.

I have whitelisted the login page, and it works fine.
+chat.openai.com/auth/login

However, when I put my login details,
then I am redirected to another page with a huge url,
which changes each time.

This is an example:
**auth0.openai.com/u/login/identifier?state=hKFo2SBISF9YV2RQTnFYRmotVDU5c25FQjQ3c1JDNjl2OFJEUqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGo5UDAtbklNcEhYUF9iaG14WlE3Q0Q1OV9mTUNzbDVZo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc**

The constant part is : **auth0.openai.com/u/login/identifier?** 
After the question mark, it is different most of the times.

How can I whitelist it in such occassions since the url is slightly different each time ?

thank you in advance
peter

**Comment by proginosko** [comment]
**+auth0.openai.com/u/login** should do it.

Please note that GitHub is really for bug reports and feature requests. For usage assistance, please use the forums. Thanks!

https://www.tapatalk.com/groups/leechblock/leechblock-usage-f3/
