### ISSUE TITLE
Load list of sites from URL

### ISSUE THREAD

**Issue by xmha97** [proginosko/LeechBlockNG#297]
Hi, I want to block all pornography sites using this extension:

If I enter sites manually, everything works fine but load list of sites from URL does work.

![Screenshot_2023-04-03-13-58-42-946_org mozilla fenix](https://user-images.githubusercontent.com/23485114/229484498-27aa46fa-04f9-4f30-8acd-c6569cdc2d97.jpg)

https://raw.githubusercontent.com/Bon-Appetit/porn-domains/master/block.txt

Please help me.

**Comment by proginosko** [comment]
My guess is that the list is way too long. 228,254 entries! When LB tries to generate a regular expression out of such a long list, it breaks. If you want to completely block these sites, I recommend you use a router-level solution. Take a look at OpenDNS Family Shield and see if that meets your needs.

**Comment by xmha97** [comment]
OK, thanks. 🙏
