### ISSUE TITLE
Pages that use AJAX navigation are not blocked when timer runs out

### ISSUE THREAD

**Issue by ArloL** [proginosko/LeechBlockNG#3]
Thanks for making this extension :)

Sadly I have an issue on pages that use AJAX navigation (where only part of the page is refreshed, e.g. imgur.com). When you are surfing on the page and the timeout reaches zero the page is still available. Refreshing the page or opening a new tab will block the page immediately.

Would it be possible to open the blocked page immediately once the timeout has reached zero?

**Comment by proginosko** [comment]
Have you selected the option "Actively block pages on these sites once time period is entered or time limit is exceeded"?

**Comment by ArloL** [comment]
No, I hadn't. Thanks @proginosko Keep up the good work!
