### ISSUE TITLE
Multi regex support

### ISSUE THREAD

**Issue by xmha97** [proginosko/LeechBlockNG#300]
Hi, I want to block the NSFW site in some regex:

1st regex:
```
^(https?|file):\/+([\w\:]+@)?((www\.)?badsite1\.com|(www\.)?badsite2\.com|(www\.)?badsite3\.com)
```

2nd regex:
```
^https?:\/\/(www.)?google\.com\/search\?.*q=.*(badword1|badword2|badword3).*
```

3rd regex:
```
^https?:\/\/(www.)?yandex\.com\/search\/\?.*text=.*(badword1|badword2|badword3).*
```

Please help me.

(I don't want to change DNS for this)

**Comment by proginosko** [comment]
Why not use three block sets, one for each?

**Comment by xmha97** [comment]
The first reason is that I don't know how to merge these three regex together.
The second reason is that it's hard to change a long regex, and it's easier to change them if it's in separate blocks.

**Comment by proginosko** [comment]
So why not use three block sets, one for each? 🙂

**Comment by xmha97** [comment]
Excuse me my English is weak and now I realized you. 😅

Now I use three block sets and everything works fine.

You can close this issue.

Thanks for your help 🙏
