### ISSUE TITLE
[Feature Request] Support file URLs containing drive specifiers (e.g., "file:///C:/path")

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#303]
I'm trying to block some local webapps.

But currently "file:///C:/path" when saved becomes "C:/path" which works at first, but when saved again becomes "path" which stops working.

updates:
`*/C:/path` does work however.

**Comment by proginosko** [comment]
Yes, I can see why that is happening. LB treats anything before a colon as a protocol and removes it, but in this case, it's not a protocol but a drive specification. The workaround would be to use a wildcard instead of a colon:

`C*/path`

**Comment by gepz** [comment]
I see, that's a good workaround.
