### ISSUE TITLE
[Feature Request] Enhence Time Limits and It's Countdown Mechanism for Better Flexibility and Habit Management

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#304]
I have been regularly using the time limit features for my Block Sets and appreciate their role as a productivity management tool, providing flexibility that calendar scheduling do not have. However, I have come across a few limitations in their current design.
While I understand that incorporating these suggestions may not be feasible or in line with the original design intent, I'd like to propose the following enhancements to improve usability:
- **More granular time period adjustments**: The current time period settings aren't very granular, making it challenging to incrementally adjust my habits. Allowing for more precise time period adjustments could help users better manage their habits.
- **Rethink the countdown mechanism**: The present mechanism resets the countdown at specific times of the day, resulting in excessive allowance time if the user start their browsing routines closer to the reset time, especially when "roll over unused time" is enabled and high time limits are set. For instance, if I set a 90-minute limit every 3 hours with "roll over unused time" enabled, and I start using the site at 7:30 after waking up, I will be allowed to use it for 4.5 hours straight until 12:00.
To address this, I suggest either:
  - Implementing a "x duration of total usages are allowed within any y duration" mechanism in a literal sense. I can see that this might be challenging to integrate with other existing functions, although I'm not sure.
  - Alternatively, instead of aligning the periods with specific times in the day and weeks. periods starting times could be realigned to (deferred to) when the user start browsing the sites for the first time in a while.
  - Alternatively, add a button for user to realign the current period starting time to the current time (thus deferring the limit reset time, the starting time of the next period).
 
In my opinion, these changes would enhance the flexibility and effectiveness of the time limit features. Thank you for considering my suggestions, and I look forward to any feedback.

**Comment by Azirine** [comment]
How about a time allowance of x minutes every y minutes up to a maximum of z minutes? Time allowance only accumulates when blocked sites are not being used.

**Comment by gepz** [comment]
That sounds good too. If I understand correctly, once the user has used other sites for 20 minutes first, your mechanism will become functionally the same as my mechanism if I set mine to "10 minutes allowed within every 20 minutes"?

**Comment by gepz** [comment]
Now I see how your time allowance feature is a little different. A user can get a small allowance whenever they take a small break. Even if they have just used up all their allowance, while mine always requires the user to wait for a sudden reset.
That sort of removes the concept of a period altogether, although I have also noticed a situation where this is not desirable, as it might be useful to encourage a user to accumulate a "minimal allowance" before using it, since some tasks require a minimal amount of time to be done, or to be done efficiently.
If we add another option "the minimum allowance", and have a rule for it that "the newly earned allowances will be preserved(can't be used) if they are needed to reach the minimum allowance before the next period", it will be powerful enough to simulate both your new mechanism and the current one and any in-between.
