### ISSUE TITLE
Bug: Options are locked forever if "Prevent access to options" and "delaying page" features are used together

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#306]

**Comment by gepz** [comment]
The bug is here I think
https://github.com/proginosko/LeechBlockNG/blob/72844b778d72a2d03ef9f72b55a7daf2ada9a76b/options.js#L498-L504

**Comment by proginosko** [comment]
Can you provide a fuller description of the problem, so I can try to reproduce it?

**Comment by gepz** [comment]
If I set a block set to use delaying page and also enable "Prevent access to options for this block set at times when these sites are blocked" in the advanced settings, the options for that block set will forever be disabled.

**Comment by proginosko** [comment]
Did you set the time period to 0000-2400? If so, it's working as expected.

**Comment by gepz** [comment]
But I am unable to add new sites or change anything, override also does not work.

**Comment by proginosko** [comment]
Correct. That's the whole point of the "Prevent access to options" setting. It's meant to stop users (if they so choose!) from circumventing the blocking behavior by editing the options. You can add new sites via the context (right-click) menu.

**Comment by gepz** [comment]
I see. I forgot about the context menu. Thanks for the help.

**Comment by proginosko** [comment]
No worries. It's easy to miss!
