### ISSUE TITLE
Leechblock NG launches a large number "Site Blocked" tabs instead of 1

### ISSUE THREAD

**Issue by AstroMike** [proginosko/LeechBlockNG#31]
Leechblock NG launches a large number of "Site Blocked" tabs instead of 1. 

This behaviour only started happening recently... so perhaps linked to recent upgrade to FF 58? 

The number does not seem to be consistent. First blocked tab I tried launched 11, the second one launched 37 ...

**Comment by proginosko** [comment]
Thanks for the report. Which OS are you using?

Does it happen for all blocked sites or only some?

**Comment by AstroMike** [comment]
(OS is Mac 10.12.16, and it seems to happen on every one that I have tried so far.)

But after a bit more experimentation, I think I have discovered that interaction with the "New Tab from Location Bar 3.11" add-on is causing the issue, because when I disable that add-on, but leave LB enabled, the problem goes away. 

(Aside: never had this problem with old LB and Tab Mix Plus, which was configured with similar behaviour, but unfortunately the FF 57 upgrade broke a lot of the good old add-ons.)

**Comment by proginosko** [comment]
Okay, that's useful to know. I'll leave this issue open for now.
