### ISSUE TITLE
Does not show the "blocked by LeechBlock" page after set time exceeds

### ISSUE THREAD

**Issue by SharifMAbdullah** [proginosko/LeechBlockNG#311]
I was using LeechBlock as firefox extension. I set a timer of 10 minutes for Facebook. When 10 mins is up, I can still browse FB but if I click on any site within facebook.com domain, i get the expected "blocked by LeechBlock" message. 
Shouldn't FB be immediately blocked when the time is up?

**Comment by proginosko** [comment]
Did you select the option "Immediately block pages on these sites once blocking conditions are met"?

**Comment by SharifMAbdullah** [comment]
I am very sorry, didn't see the option😅
