### ISSUE TITLE
how to prevent disabling Leechblock (Firefox-Addon)

### ISSUE THREAD

**Issue by janpr84** [proginosko/LeechBlockNG#312]
hello friends of Leechblock,

I am looking for a way to prevent disabling an addon. it's about the web blocker LeechBlock.

It was intended as an alternative to the web blocker ColdTurkey, but unlike ColdTurkey, which does not work for Linux systems, there is no password protection to prevent disabling and/or uninstalling the addon. Thus, it is quite easy to get distracted even though you don't really want to.

does anyone know a solution?

can you customize Leechblock to make it harder to disable or uninstall Leechblock by entering a (very long) password?

This is possible with the browser addon for Cold-Turkey. So it must be possible for Leechblock too.

**Comment by proginosko** [comment]
See: https://www.proginosko.com/leechblock/faq/remove-extension-firefox/

Also, you can find some further discussion on the community support forums:

https://www.tapatalk.com/groups/leechblock/

**Comment by smayer97** [comment]
For further reference, see this WIP list:
https://github.com/proginosko/LeechBlockNG/issues/328

Most are for Chrome, but it may give you direction on additional things to consider. You will also find some apply to Firefox
