### ISSUE TITLE
Doesn't work for wikipedia.org

### ISSUE THREAD

**Issue by RodrigoDiazDVivar** [proginosko/LeechBlockNG#313]
I cant block en.wikipedia.org nor es.wikipedia.org even if i write it with **, * before and/or after... nothing works for a reason... it used to work but stopped suddently. I think it may have somthing to do that this is my last filter (7th)
edit: i'm usign last version of firefox on windows 10 btw

**Comment by RodrigoDiazDVivar** [comment]
fixed: i forgot sunday and saturday were turned off by default (makes no sense to me anyways) lol

**Comment by proginosko** [comment]
Workdays by default. 🙂
