### ISSUE TITLE
Is it possible to clock and block pages provided by a local extension?

### ISSUE THREAD

**Issue by dzx-dzx** [proginosko/LeechBlockNG#315]
They would appear as `moz-extension://********/***.html` in the address bar, but so far I don't know what parts to add to the block list.
If that's not supported, Would you consider it a feature request? I'd be very grateful!

**Comment by proginosko** [comment]
The only way to do it right now is with regular expression blocking. Go to Advanced Options and enter the regex in the field "Use regular expression to match URLs to block". For a URL like the one above, you can simply put "^" in front of the URL and put "\\" before the "/" and "." characters. For example:

`^moz-extension:\/\/18782b4e-c6fd-4f66-909b-e4d051c0de01\/stats\.html`

**Comment by dzx-dzx** [comment]
Oh now the block page does appear, but only when the site is set to be block under all conditions. If I set a time limit, the clock doesn't appear, and the page isn't blocked after it. Is that expected behaviour?

**Comment by proginosko** [comment]
Yes, it will only work for blocking by time periods. There are technical reasons why LeechBlock can't track time spent on extension pages.

**Comment by dzx-dzx** [comment]
I see... Thanks for your help!
