### ISSUE TITLE
Blocking rules are not associative 

### ISSUE THREAD

**Issue by mzaja** [proginosko/LeechBlockNG#316]
I am trying to do the following:
- Block `linkedin.com` (just the homepage)
- Block `linkedin.com/feed*`
- Allow everything else on the domain. 

I have created a ruleset:
```
linkedin.com
linkedin.com/feed*
+linkedin.com/*+
```
but this ruleset blocks only the homepage and allows everything else, including `linkedin.com/feed`.

However, if I split the ruleset above into two sets like this, then it works as intended:
```
linkedin.com
+linkedin.com/*+
```
```
linkedin.com/feed*
```

I do not know whether this is a big of a feature, but I would expect a combination of rules and rulesets to be associative, e.g. (a + b + c) == (a) + (b + c).

**Comment by proginosko** [comment]
It's not a bug if it's the intended behavior. 🙂

Basically, LB tests the URL against _all the blocking patterns_ before testing it against _all the allowing patterns_. So think of it as _any_ exception trumping _all_ blocks.

The easiest way to get the behavior you want is to use two block sets, as you've done. The neater way is to craft a regular expression that matches only the URLs you want to block (documentation [here](https://www.proginosko.com/leechblock/documentation/#BlockSetAdvancedOptions)). Then you only need one block set.

**Comment by mzaja** [comment]
Thanks, got it. Feel free to close this issue if you wish.

**Comment by smayer97** [comment]
> It's not a bug if it's the intended behavior. 🙂
> 
> Basically, LB tests the URL against _all the blocking patterns_ before testing it against _all the allowing patterns_. So think of it as _any_ exception trumping _all_ blocks.
> 
> The easiest way to get the behavior you want is to use two block sets, as you've done. The neater way is to craft a regular expression that matches only the URLs you want to block (documentation [here](https://www.proginosko.com/leechblock/documentation/#BlockSetAdvancedOptions)). Then you only need one block set.

To be clear, does this only apply WITHIN a block set, and not ACROSS ALL block sets?

Also, could you create a section in the documentation that captures such important nuances like this? 
(not sure what others like this would be significant to share).
