### ISSUE TITLE
Bug? Extension and Settings page unblocked also when Override used

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#317]
When a block set has the option checked to block the Extensions and Settings page and the option to allow override is selected, these pages are unblocked when the Override is used. 

Is this intneded behaviour or a bug? If a bug, please fix. If intended, please make this a feature request to provide option prevent this...

My work around solution (for the benefit of all), I created a second block set with random text in the list of blocked sites, checked to block the Extensions and Settings page, and did not select allow Override. This means the Extensions and Settings pages will always stay blocked.  Is there a more elegant way to do this?

(see also related BUG about these pages not automatically getting blocked again when Override is over).

**Comment by smayer97** [comment]
I'm not sure what it means, " added a commit that referenced this issue". Does this mean my suggestion is implemented in an upcoming release? Is there anything to read on what is implemented? Please clarify.

**Comment by proginosko** [comment]
Yes, it is fixed. In the next release, the Extensions and Settings pages will still be blocked during override.

**Comment by smayer97** [comment]
Thx for the reply. Will this be an optional behaviour, as I can see some scenarios where it is appropriate to have or some people still wanting the current behaviour?

**Comment by proginosko** [comment]
No. I consider this a fix, since it should always have behaved this way. The override is meant to apply to the websites only.

I don't want to make it optional, because the options are getting cluttered already.

**Comment by smayer97** [comment]
As you can see by this latest issue, #396, clearly there are scenarios that would warrant making it optional. I too have scenarios were that would be the desired, and preferred, way of functioning. 

Please consider this.

**Comment by proginosko** [comment]
So you want the fix, except for those scenarios where you don't want it. Got it! 😉

I'll consider making it optional.

**Comment by smayer97** [comment]
As you can see there is a need for it to work in either way. I am not the only one that has that need. And I did mention in my OP "...please make this a feature request to provide option prevent this..."

Thanks for your considering this.

**Comment by smayer97** [comment]
Thanks for the change.
