### ISSUE TITLE
[Feature Request] Allow blocking access to the LeechBlock Documentation pages

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#320]
Please allow the ability to block these pages. 

By default, these pages are currently ALWAYS accessible. Currently, there is no way to block these pages. 

BONUS: If you can make this work such that the documentation pages are only blocked when the LeechBlock Options page is not open but the links inside the Options pages are still functional.

**Comment by proginosko** [comment]
This is by design. I don't see why it would be necessary to block the documentation pages.

**Comment by smayer97** [comment]
The reason is that if you are acting as a accountability partner to someone else, then them having access to the documentation gives them ideas about how to bypass LeechBlock or extended times that may otherwise not be obvious to the user normally. In other words, the less they know, the better.

All I am asking is that it be an option.

**Comment by smayer97** [comment]
To elaborate, the documentation includes information on how to block bypassing LeechBlock. By inference, this makes it not only makes it clearly known that there are ways to bypass it, but makes some of those methods front and centre. This can arouse temptation to try those and/or seek out more ways on how.

**Comment by proginosko** [comment]
Sorry, I still don't understand the rationale for this. Why would anyone want to block the documentation in the first place? If it's only because they've discovered that "the documentation includes information on how to block bypassing LeechBlock," then it's too late for them! But what _other_ reason could they have for blocking the documentation? It looks like the rationale here is self-defeating.

**Comment by smayer97** [comment]
First, just to clarify, what I am asking it to ideally not show the documentation URLs on the Block Page and allow the documentation site to be blocked, at least in a block set, but not when inside the LeechBlock settings/options. That is the ideal.

As for the reasoning, again, this only makes sense in the context of an accountability partner situation, like a spouse, friend, etc, where you do not have access to LeechBlock but rather the other person does. So, you cannot change the settings; and you are unlikely to let the user into the settings, in this context. So, therefore, not allowing access to the documentation makes sense, because, having access can become a temptation to try to circumvent LeechBlock.

LB was great until you make the documentation accessible front and centre on the block pages, as of v1.5.7. So, again, at a minimum, I am suggesting making it an option to have the documentation URLs visible on the block pages, and second, to be able to block access to the documentation as a user; the simplest I can think of for the latter is to allow blocking the documentation site by adding the site to a block set (unless you can think of a better implementation that provides the same result.

HTH

**Comment by smayer97** [comment]
P.S. If it is too difficult to implement all of this, please consider at least make it an option to show the URL links on block page or not.

**Comment by proginosko** [comment]
The next release will include an option to allow/disallow blocking of the LeechBlock website.
