### ISSUE TITLE
[Feature Request] Option to set Maximum Rollover Time

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#321]
I think self-explanatory. Then there would be no need to clear the override amount manually.

It looks like there currently is no maximum. There is also no obvious way to know how much rollover has accumulated.

**Comment by proginosko** [comment]
Time is rolled over only from the previous time period. So with rollover selected, the maximum time allowance in any time period will always be double the time limit (time from previous period + time for this period). The countdown timer will always display the total amount of time left.

**Comment by smayer97** [comment]
Thanks for clarifying. 
Based on the documentation:
"Roll over unused time

If selected, any unused time from the previous time period will be added to the time allowance for the current time period.
Example: If you set a time limit of 10 minutes in every hour, and you accessed the sites for only 7 minutes in the previous hour, you will be able to access the sites for 13 minutes in the current hour."

You can see that it is easy to interpret that all leftover continues to be carried over.

That said, if I set the time limit to 2 hrs/day, but I do not use any, or very little, I may not want the next day to allow me to use 4 hours. I would still like to be able to limit it to a lower amount. 

Could you please consider this?

Also, could you please update the documentation to add your clarification for reference?

**Comment by proginosko** [comment]
I've updated the documentation to clarify the functionality, and I will consider your feature request.

**Comment by smayer97** [comment]
Thanks for the update. SO I am clear, you mentioned considering the feature request and reopened this only to close it immediately after. So is this still being considered?

**Comment by smayer97** [comment]
BTW, just to build on the case for this, a block set may be set up with a max of 2hrs/day 7 days/wk but Sundays may often be inconsistent, since lots of stuff happens on the weekends. This would mean that many Mondays I would end up with up to 4 hours on the first day.... not sure that is a great way to start the week.
