### ISSUE TITLE
[FAQ Edit Suggestion] Update about adding comments in a block set

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#323]
On the FAQ about adding comments, it should be made clear that you cannot use spaces between words, since LB automatically parse the line and creates new lines. Instead, it is necessary to use some character in between words (Suggestions: "-", ",", ".", "-", "_", etc)

https://www.proginosko.com/leechblock/faq/comments/

**Comment by proginosko** [comment]
As the FAQ entry says, the # character is not really intended for comments. It's for temporarily deactivating sites without removing them from the list.
