### ISSUE TITLE
[Documentation Edit Suggestion] "Caution: " in "Prevent Access to..." shoudl be replicated

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#327]
I strongly suggest repeating this "Caution" under every "Prevent Access to..." instructions. 

https://www.proginosko.com/leechblock/documentation/

**Comment by proginosko** [comment]
I don't think the same caution is needed for the other options, because they don't get you into a Catch-22 situation where you can't undo the option itself.

**Comment by smayer97** [comment]
Thanks. Upon further reflection based on your feedback, I see what you mean.
