### ISSUE TITLE
Don't show warning if site will not be immediately blocked

### ISSUE THREAD

**Issue by benburrill** [proginosko/LeechBlockNG#33]
I immediately block some sites after time is up, so a 30-second warning is useful.  On others (like wikipedia), I allow 10m/3h of unrestricted time and then afterwards show delay pages for future pages.  For those, warnings are redundant and annoying (and possibly counterproductive if I start using that as a cue to queue up a bunch of links I might be interested in before the delay sets in).

I think there should either be a warning setting dependent on whether the page I'm on will be immediately blocked _or maybe_ a warning setting on a per-block-set basis.

**Comment by proginosko** [comment]
You're right. There should be a per-block-set option for the warning message. I will add that in the next version.
