### ISSUE TITLE
BUG? Block Time Counter displays 00:00 instead of blocking the sites when using set with keywords

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#331]
For some reason , as soon as I turn on a set with keywords the timer for sites in another block set shows 00:00 instead of the actual time left, and it seems to give unlimited access to those sites. (The display of 00:00 in itself seems like a bug).

Not sure if I am missing something in my setup. Please take a look at my attached settings file.

The sites in the Downtime set seem to get overridden with the Keywords set.

[LBOptions NO PW set-Chrome AM 3.txt](https://github.com/proginosko/LeechBlockNG/files/12783711/LBOptions.NO.PW.set-Chrome.AM.3.txt)

**Comment by proginosko** [comment]
Once you add keywords to a set, the sites are blocked _only if_ the keywords appear. (See FAQ entry for details.) So the timer showing 00:00 indicates that there's no further _time_ condition to be fulfilled for blocking, only a _keyword_ condition.

Suppose, for example, you set it to block somesite.com from 0900-1700 and included the keyword "foobar". At 8:30am, the timer will show 30:00, counting down. At 9:00am, it will show 00:00, but somesite.com will be blocked _only if_ the current page includes the keyword "foobar". That situation will continue until 5:00pm.

If you don't like seeing the 00:00, you can disable the timer. 🙂

All this to say, this may seem like quirky behavior to some users, but there is a logic to it, and I don't consider it a bug.

**Comment by smayer97** [comment]
I used whitelist as one block set, with times to apply. How do I also block using keywords without it overriding the time, so that the keywords block the sites within the times of the whitelist.

Currently, I tried using a separate block set with the keywords with ALL DAY selected, meaning I want the keywords to always block sites...but I still want to control which sites apply and when.

**Comment by smayer97** [comment]
Can you please clarify how this is supposed to work? From what I am reading, are you saying that there is no way for someone to know how much time is left until the time of that block set is over, if there is a keyword list being used? Or am I misunderstanding? (Same seems to be the case when override is used).

So from your example, if I have a whitelist:
*
+somesite.com
Blocked  All Day

and another block set:
somesite.com blocked from 0900-1700

and another set for keyword blocks:
*
~keyword1
~keyword2
etc.
Blocked all day

at 0830 I would expect it to show 00:30 remaining but what I am seeing is 00:00. 

And from 0900-1700 somesite.com, when somesite.com is blocked, but I use override, I am again seeing 00:00 instead of the remaining time until the override is over. 

Is this expected behaviour? If so, how is a user to interpret this, as there is no applicable remaining time showing?

**Comment by smayer97** [comment]
Hi again, could you please provid some guidance on the use of keywords, beyond the FAQ? My goal is to be able to use the keywords to filter already filtered sites (whitelist). But when I enable the keyword block set, it seems to override the whitelist, and only block sites from the whitelist IF they keywords apply. Please clarify how I can make this work in tandem.
