### ISSUE TITLE
BUG - "Immediately block pages..." option does not block set using using Regular Expression after Override expires

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#332]
Options used:
- Immediately block pages on these sites once blocking conditions are met
- Regular Expression: ^chrome:\/\/history
Block time is 0000-2400. 7 days 

When use Override and time expires, page does not automatically block. Please fix.

**Comment by proginosko** [comment]
Regular expression should be **^chrome:\\/\\/history** because forward-slashes are special characters.

**Comment by smayer97** [comment]
Sorry,but I did type that in my question above but for some reason it did not show; strange. So, yes, I am using ^chrome:\/\/history.

So this is still an issue.

**Comment by smayer97** [comment]
Hmmm.... every time I try to type \ followed by /, this editor filters it out.

**Comment by smayer97** [comment]
\\/

**Comment by proginosko** [comment]
I figured out why this is happening. Should be a relatively easy fix for the next release.

**Comment by proginosko** [comment]
Just FYI: this repo is for the Firefox version. Chrome repo is here: https://github.com/proginosko/LeechBlockNG-chrome

**Comment by proginosko** [comment]
This is fixed for the next release.
