### ISSUE TITLE
[Feature Request] Show page title on "Site blocked" page

### ISSUE THREAD

**Issue by d9k** [proginosko/LeechBlockNG#333]
Please show page title on "Site blocked" page, not only URL.
It would help to open only required pages fast when block time is over, not every blocked page to see which of them you need right now.

**Comment by proginosko** [comment]
The problem with this suggestion is that the title of a page is only available once the page is loaded. It's part of the content of the page. When a page is blocked by LB on the basis of its URL alone, no content is loaded, so the title isn't available. To implement this feature, LB would have to load the page content elsewhere. That seems wasteful, just to get the page title!

**Comment by proginosko** [comment]
Closing this for reason given above.
