### ISSUE TITLE
[BUG?] Cannot see timer on top-left corner anymore

### ISSUE THREAD

**Issue by Endternal** [proginosko/LeechBlockNG#334]
When I first got LB on Microsoft, it wouldn't work. Later it started working, but when I made two block groups for the same site it wouldn't work again. Now I use Fire/Waterfox. I reinstalled the extension on Mozilla, but I'm stuck as I was before. Is there a setting I am not using that I should be? The only blocked sites I have now in settings are 3 with some page exceptions.

**Comment by proginosko** [comment]
Please export your options to a text file and email it to me (leechblockng@proginosko.com) so I can take a closer look.

**Comment by Endternal** [comment]
How do I export it?

**Comment by proginosko** [comment]
Options > General > Export Options to File

**Comment by Endternal** [comment]
I figured it out, but thanks for offering help. I did not put the option for every [something] I get 20 minutes. Really love the extension, keep up the good work!
