### ISSUE TITLE
"Prevent access to about:addons at times when these sites are blocked" doesn't work when using allow keywords

### ISSUE THREAD

**Issue by pets-er** [proginosko/LeechBlockNG#336]
Hi there!

First of all, great tool and a big thank you to all the contributor, especially the maintainer.
I use restrictive blocksets and unblock via keywords that are usually part of texts that I'm working on ("Treat keywords as allow-conditions rather than block-conditions").
When combined with the option "Prevent access to about:addons at times when these sites are blocked" and (even completely random) keywords, the latter option appears to break down.
A dummy blockset with the same times etc. and a dummy site (see #310) does work, so minor bug.

Thanks :)

**Comment by proginosko** [comment]
Good catch! That should be fixable.
