### ISSUE TITLE
On Microsoft Edge, there is a way to circumvent by using Read mode

### ISSUE THREAD

**Issue by michaeldacanay** [proginosko/LeechBlockNG#340]
Example:

If I have a url, I can type `read:` + URL, and I can read the webpage even though the URL had the keyword or is a blocked website.

`read:https://thehill.com/homenews/senate/4348844-college-football-playoffs-senate/`

Desired behavior is to have the same behavior as if `read:` was not prepended.

**Comment by proginosko** [comment]
Please repost in the LeechBlock for Edge repository: https://github.com/proginosko/LeechBlockNG-edge/issues

Thanks!

**Comment by michaeldacanay** [comment]
Just reposted!
