### ISSUE TITLE
[Suggestion] Change titile of this GitHub Issues section to say "LeechBlockNG-firefox"

### ISSUE THREAD

**Issue by smayer97** [proginosko/LeechBlockNG#343]
This will emphasize the need to submit tickets under the other section.

**Comment by proginosko** [comment]
Thanks for the suggestion. I would rather not rename the repository, in case it unexpectedly breaks something. (The other versions treat this one as the upstream repository.) I've added a pinned issue instead. Hopefully that will do the job.
