### ISSUE TITLE
Block subdomains by default

### ISSUE THREAD

**Issue by benburrill** [proginosko/LeechBlockNG#35]
Usually you don't just want to block `example.com`, but also all its subdomains.  Currently, `www.example.com` will automatically get blocked when you block `example.com`, but not `potato.example.com`.  You can use `*.example.com`, but unfortunately this won't block `example.com` itself, so you need to block both `example.com` **and** `*.example.com` (or `*example.com`, but obviously that's a little problematic).

Another option would be to make `*.example.com` a special case that blocks `example.com` as well.

**Comment by Metaception** [comment]
I second this change.

It's always annoying thinking you blocked a site and then discovering they have multiple subdomains. Even double checking at the subdomains when you add it is problematic as site like to use subdomains to test new beta versions by default (go.twitch.tv is an example).

Blocking access to `www.example.com` and `example.com`, but allowing all the subdomains seems backwards. Blocking all subdomains, then write exceptions for select subdomains

Not sure if there is any performance issues. uBlock seems to handle this efficiently though.

**Comment by proginosko** [comment]
The problem here is that it would change the default behavior for users who didn't ask for it. With the new behavior, sites would be suddenly blocked that users never wanted to be blocked.

**Comment by benburrill** [comment]
I could add an option for that to #39, but I can't really imagine why users wouldn't want the new behavior.  Also, they can just do `+*.example.com` to whitelist the subdomains.

**Comment by proginosko** [comment]
Scenario: someone is blocking google.com from 9am to 5pm. (Why? Who knows. But it's impossible to predict user behavior.) They're used to having access to Gmail, but all of a sudden mail.google.com is blocked, and they can't change their settings until 5pm because they're locked down. User is not happy. 😒

**Comment by benburrill** [comment]
Ok, I added an option for it (disabled by default) so we don't need to bother that one user who relies on the current behavior and also locks themselves out from changing the settings.

https://xkcd.com/1172/

On an unrelated note, the handling of options really needs to be cleaned up.  Adding an option currently means changing a lot of things across several files.

**Comment by proginosko** [comment]
Thanks for the contributions, Ben. You'll see that they featured in v0.9.
