### ISSUE TITLE
Time Limit not Counting Properly

### ISSUE THREAD

**Issue by Scarsn** [proginosko/LeechBlockNG#36]
When you use the options "within time period and time limit" as well as "show timer", you can see the timer is not counting down when you leave the window/tab open but use another tab/window. 

This may be reasonable in many cases but misses the point when the tab in question is a streaming or video service like youtube or netflix. The site can remain open and play videos without ever advancing countdown and can therefore continue to distract.

Leaving the timer running even if you tab out may not be a sensible solution, I realize, but perhaps the issue can be solved by checking wether a site produces sound or wether the tab is currently displayed in front of the browser. 

Alternatively the option "advance timer while window/tab not active" may be introduced. The issue then can be cirumvented by having multiple blocks. 

Alternatively alternatively, an additional options tab can be added where you enter sites like which advance countdowns despite being tabbed out if they are also part of the Block set.

**Comment by benburrill** [comment]
There already is "Count time spent on these sites only when browser tab is active".
