### ISSUE TITLE
Having issue blocking a site

### ISSUE THREAD

**Issue by greendost** [proginosko/LeechBlockNG#37]
Hi, I am having some difficulty properly blocking yahoo mail.  (Firefox quantum 58.0.1 / Mac)

Issue
I am using the url "mail.yahoo.com", and time periods set to "0900-1300,1500-1700", and when I attempt to browse to that site (with Leechblock NG turned on), it works and I get the expected delaying page.  

But once I do get the mail page to load, I can't seem to get it to re-block.  I tried refreshing the page a number of times, but no luck.  I suspect it might have something do with the fragment after the url:  
      e.g. mail.yahoo.com/#5555    

In the advanced section, I do have this setting checked, though:
      Ignore fragment (hash part) when checking URL 

I looked at the instructions, but I couldn't find anything for this issue; it's likely that I am not doing something correctly.  Also, not sure what the "00:00:00" that shows up on the mail page means?

Any help would be appreciated.  Thanks.
  - Harteg

**Comment by proginosko** [comment]
Sounds like you need to uncheck the option "Block only first accessed page of site when delaying page is used".

**Comment by greendost** [comment]
Hi James, thanks for the tip.  However, not sure if that is resolving the issue: how to re-block the site again, after I wait 60 seconds and start viewing it.  

I can open up the site in a new tab, and yes, that correctly triggers LeechBlock.  But a page refresh would be preferable.  My question then --  is refreshing the tab a way to re-trigger LeechBlock ?  or, would that be a feature request?

I tried another site as well - financial times, www.ft.com - which does not alter the url, and same issue - after waiting the 60 seconds to view the site, page refresh does not re-trigger LeechBlock.

Thanks.

**Comment by proginosko** [comment]
I think what you're describing is the intentional behavior of LB when the delaying page is used. When you use the delaying page, LB initially blocks the page of the listed website and then (via an internal flag) allows it indefinitely until you navigate to another page. Refreshing the page forces LB to check the page again, but (due to the internal flag) it won't be blocked. Only navigating to another page will clear the flag.

**Comment by greendost** [comment]
It does seem to be working a little better this week (or maybe I didn't notice earlier) - my tab with yahoo mail was correctly blocked this morning, and blocked again at 3pm per my setting without needing a refresh.  

(1) However, given my setting of "0900-1300,1500-1700", I would have expected it to automatically unblock at 1pm, but that did not happen.  I had to wait through the delaying page.  Is this expected?


(2) Thanks for clarifying about the "internal flag".  

So a couple questions: is a page refresh treated the the same as navigating to a page, whether the first time, or perhaps via the back button?  Or, can you explicitly identify the event where a user physically initiates a refresh ?

If you can identify a user refresh event, then my question would be whether an option could be added for bypassing the internal flag on a refresh (and only a refresh)?  I think this could solve the issue for sites like Yahoo mail, which I assume don't "navigate" to another page when checking mail, as well as work with other sites that do navigate to other pages when "block only first accessed page..." is checked.

Thanks.

**Comment by greendost** [comment]
Looks like this has been fixed.  Things have been working as expected for the past number of months.  Thanks.
