### ISSUE TITLE
Rollover unused time to the next period

### ISSUE THREAD

**Issue by chocolateboy** [proginosko/LeechBlockNG#38]
Thanks for this great addon (and for the original)! I wish I could quit it but I can't :-)

Is it possible to implement a "rollover" feature to complement the time-limit feature? e.g. say I restrict access to certain sites to 5 minutes an hour, and then get my head down for a couple of hours, I'd like to "bank" those unused minutes so that I'm rewarded them as a lump sum at the end of that period e.g. 15 minutes of play for three hours of distraction-free work.

IMO this could help to [gamify](https://en.wikipedia.org/wiki/Gamification) focus and attention by setting up a clear cost (disincentive) for slacking and reward (incentive) for working. This is similar to the tug of war between pleasure and pain in dieting e.g. exercise or fasting to pay off or purchase pleasurable (but [non-nutritional](http://www.independent.co.uk/news/uk/home-news/social-media-bingeing-as-bad-as-junk-food-parents-warned-childrens-commissioner-anne-longfield-a7879066.html)) treats.

**Comment by proginosko** [comment]
This is a good suggestion. Let me give it some thought.

**Comment by proginosko** [comment]
Finally got around to implementing this! Look for it in version 1.4, currently under review.
