### ISSUE TITLE
BUG: Cannot access blocked sites after uninstallation of LeechBlock for Firefox

### ISSUE THREAD

**Issue by 1-icenine** [proginosko/LeechBlockNG#408]
I installed the extension this week and adjusted the settings for YouTube to be blocked. Outside of the time range, I tried to reaccess YouTube but could not access it. I attempted to override for 15 minutes several times, but that didn't work. I also uninstalled and reinstalled it, but I still have the same issue (both with and without Leechblock). I have also tried seeing if I could change the website URL to show something else when blocked, but nothing happened. 

For context, I am running this on a Macbook Pro, Mid 2015. I don't expect this to be a CPU or memory issue, but I am still confused about how to remedy this problem.

I had this URL pop up occasionally: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi3vNz27aOEAxVfkokEHflbApAQFnoECAYQAQ&url=https%3A%2F%2Fwww.youtube.com%2F&usg=AOvVaw0usXxGa_x5y1xoI_LaL0-1&opi=89978449. I am not sure how helpful this is.

**Comment by proginosko** [comment]
Are you saying that you can't access YT even when LeechBlock is uninstalled? If so, it can't be due to LB. Am I misunderstanding you?

**Comment by 1-icenine** [comment]
Yes, I couldn't access YT even after LB was uninstalled. If that's the case, then I'll reinstall a new browser.
