### ISSUE TITLE
Lost settings 

### ISSUE THREAD

**Issue by rnc** [proginosko/LeechBlockNG#41]
Using 0.8.1. under Firefox 58.0.1 on Fedora 27 I configure Leechblock with a number of sites/options and then it seems to 'loose' them. This especially happens on restart, especially if Firefox crashed.

**Comment by proginosko** [comment]
Repeat of #26?

**Comment by rnc** [comment]
@proginosko  Yes it does seem related : I have just tried, on another user account in my machine, with a fresh profile and even running "kill -9 firefox" I was unable to reproduce any data loss corruption. I don't know if its feasible another add-on is conflicting.

**Comment by proginosko** [comment]
There have been reports that uninstalling and reinstalling LB makes the issue go away. It could be related to a corrupted storage file.

**Comment by rnc** [comment]
@proginosko Given I'm unable to reproduce it reliably with sufficient information to make a diagnosis I'll close this for now. Thanks anyway!
