### ISSUE TITLE
[Feature Request] Option to enter password first to override blocking.

### ISSUE THREAD

**Issue by devxbasit** [proginosko/LeechBlockNG#424]
Hello, the option to enter a password to override blocking would be productive. I sometimes go and override for 5 or 10 minutes. There should be a system in place so one does not go and override whenever one wishes. 

![image](https://github.com/proginosko/LeechBlockNG/assets/24441401/75fb97b9-72a2-4c8c-b912-6f37dc8a0b95)

**Comment by proginosko** [comment]
Happily, that feature already exists. 🙂

Go to Options > General > Temporary Override. Select "Require the user to enter a separate override password" and enter the desired password in the field below.

Note that you can also set a limit to the number of overrides per hour/day/week.

**Comment by devxbasit** [comment]
Thank you @proginosko, I believe this feature should be enabled by default.
