### ISSUE TITLE
"Show timer over page" doesn't work

### ISSUE THREAD

**Issue by Bmandk** [proginosko/LeechBlockNG#427]
I have enabled the "Show timer over page" button, but I don't see any timer on the page in the corner I specified.

**Comment by proginosko** [comment]
Check that you've granted the right permissions for the extension. See "Important" under **Quick Start** section [here](https://www.proginosko.com/leechblock/documentation/).

**Comment by Bmandk** [comment]
That was indeed it, thanks!
