### ISSUE TITLE
Only Non-Private Tabs Blocking is Unreliable without Delay

### ISSUE THREAD

**Issue by ReylordDev** [proginosko/LeechBlockNG#432]
Hey there,

First of all, thank you so much for your work on this amazing extension.

When setting to block pages in ```only non-private tabs```, pages still get blocked in incognito mode for me. However, when using the setting to wait a few seconds after the page has loaded before checking blocking conditions, this issue is mostly resolved. I need to use at least 3 seconds of delay and some unreliability remains.

I have tested this with a minimal block set.

**Comment by proginosko** [comment]
You're using Firefox, correct?

**Comment by ReylordDev** [comment]
Yes, Firefox 125.0.1

**Comment by proginosko** [comment]
Okay, thanks for reporting this. Good catch! I can see why this is happening. It has to do with the fact that LB doesn't get notified that a page is in incognito mode until the initial page content has been loaded. But I should be able to fix this in the next version. In the meantime, using the "Wait __ second(s)..." setting under Advanced Options is the best workaround.
