### ISSUE TITLE
Doesn't track time at all [Firefox 57.0.2, Debian Buster]

### ISSUE THREAD

**Issue by CosineP** [proginosko/LeechBlockNG#46]
I see no timer / counter in blocked pages. It never reaches zero and starts blocking.

Things work fine with the time-of-day block, but the "time period" blocks don't work at all.

The statistics page tracks my general stats, but not my per-day stats. For example:

Time Spent Per Day | Time Left in Limit Period
-- | --
00:04:04 | 00:45:00
20:52:38 | 04:30:00
00:27:14 | 00:45:00
00:17:30 | 01:15:00

The left column is (probably) accurate but the right column is just the time I have configured for the groups.

Here's my config, just run-of-the-mill stuff.

[LeechBlockOptions.txt](https://github.com/proginosko/LeechBlockNG/files/1777176/LeechBlockOptions.txt)

**Comment by CosineP** [comment]
BTW this still happens if I disable all my other extensions.

**Comment by proginosko** [comment]
Thanks for this report. I'm having trouble understanding your settings. It looks like your first block set is set up to block sites all day (0000-2400) OR after 45 minutes in every 24 hours. Because you've selected OR rather than AND, the sites will simply be blocked all day. The blocking condition is always met, and thus the time limit becomes irrelevant. So it makes sense that the "Time Left in Limit Period" isn't decreasing. Does that make sense now?

**Comment by CosineP** [comment]
Nah, these settings are carried over from the old/XUL version and they worked fine. They're blocked all day *on weekdays* (look at the days bitfield), and time-blocked on weekends. OR makes sense here. The error occurs on the weekends, when they're supposed to be time-blocked.

**Comment by proginosko** [comment]
I'm talking only about your first block set. Those settings will block the listed sites all day, Mon-Fri, and not at all at weekends. The time limit is irrelevant because of the OR setting. Trust me on this. 😃

**Comment by CosineP** [comment]
OH, so the blocked days actually affect both the time elapsed and the time period? That seems odd, I don't recall it being that way before but maybe I'm wrong.

How could I achieve my desired behavior of "fully blocked on weekdays, timed on weekends?"

I was able to make days only affect time periods and not time elapsed with [this patch](https://github.com/proginosko/LeechBlockNG/files/1778087/background.js.patch.txt), which makes it work, but I'd prefer to use vanilla if it's possible / easy.

**Comment by proginosko** [comment]
Yes, that's right. Blocking (both conditions) only applies to selected days. To get the behavior you want, you'd need to use two block sets: one for weekdays, the other for weekends.
