### ISSUE TITLE
LeachBlock counts time even if tab is not looked at.

### ISSUE THREAD

**Issue by stefan11** [proginosko/LeechBlockNG#472]
Currently Leachblock seems to be not working if multiple tabs are open. Even though I checked "Count time spent on these sites only when browser tab is active", it keeps counting the time although I do not look at the tab.

**Comment by proginosko** [comment]
Which browser and OS are you using?

**Comment by stefan11** [comment]
Sorry, this was a mistake of mine in configuring leachblock. I put the complete time of the day into the field for when the restrictions had to apply. I then extended the time for some minutes and this seems to have ignored me changing browser tabs. Now it works as expected for the basic application. Maybe the time extension problem is still there.

This is firefox and Mac OS.

**Comment by proginosko** [comment]
If you're using the override function, then the time allowance goes down regardless of which tabs are open/active. The override time is different from the time limit. For example, if you ask to override for 5 minutes at 8pm, you will be allowed access until 8:05pm regardless of what tabs/sites you have open.
