### ISSUE TITLE
Leechblock doesn't block sites

### ISSUE THREAD

**Issue by CentroChico** [proginosko/LeechBlockNG#485]
The title is pretty self explanatory. I add sites and keyword to the blocklist, I allow every permission and nothing is ever blocked. 

The thing is supposed to help me reclaimed my time, but I'm here having lost one hour trying to make it work

**Comment by proginosko** [comment]
Did you specify time periods and/or a time limit?

See the [examples page](https://www.proginosko.com/leechblock/examples/) for some pointers.

**Comment by CentroChico** [comment]
> Did you specify time periods and/or a time limit?
> 
> See the [examples page](https://www.proginosko.com/leechblock/examples/) for some pointers.

There's a list without and 2 lists with time periods. None of them work

**Comment by proginosko** [comment]
Please export your options to a text file (Options > General > Export Options) and email it to me at leechblockng@proginosko.com so I can take a closer look.

**Comment by CentroChico** [comment]
> Please export your options to a text file (Options > General > Export Options) and email it to me at [leechblockng@proginosko.com](mailto:leechblockng@proginosko.com) so I can take a closer look.

Done

**Comment by proginosko** [comment]
Thanks. I see that you have a list of sites _and_ keywords in both block sets. What this means is that those sites will only be blocked when one of the keywords is found on those sites. See [here](https://www.proginosko.com/leechblock/faq/keywords/) for explanation of keyword blocking.

If you want those sites to be blocked _always_, and also for _any_ sites with those keywords to be blocked, you will need to set up two block sets, like this:

**Block Set 1**
`blockme.com`
`blockmetoo.com`

**Block Set 2**
`*`
`~keyword1`
`~keyword2`

If that's not what you had in mind, let me know.
