### ISSUE TITLE
more granular active tab settings

### ISSUE THREAD

**Issue by moben** [proginosko/LeechBlockNG#49]
The `Count time spent on these sites only when browser tab is active` setting currently takes into account both window focus and the tab being active ([code](https://github.com/proginosko/LeechBlockNG/blob/master/background.js#L226)). It would be nice if this was more granular.

For example, I would like time to count down if a blocked tab is active even if the browser window is not focused. This prevents me from having a blocked tab open on one monitor while having something else focused on a second monitor. But I don't want to block them unnecessarily as long as they are in background tabs and I don't look at them.

Another thing that would be nice is counting time while a tab from a block set is playing media, even if the tab is inactive. (e.g. having a youtube video playing in the background and just listening to the audio)

I would propose splitting the existing setting into `Count only tabs in active windows` and `Count only active tabs`. The question is in which order to apply those conditions. The window focus setting should probably be evaluated before any settings that affect if tabs count. (Something along the lines of `focus && (active || media || ...)`

**Comment by Metaception** [comment]
One important issue with the current implementation and default settings is that if you open a blocked video on say YouTube then take focus away from the browser window, the timer stops.

This also applies to long-form web pages as you can scroll windows with giving them focus in modern OS.

**Comment by woj-tek** [comment]
+1

Basically it seems to boil down to "is visible" property.

**Comment by maxexcloo** [comment]
I'd like this too!

**Comment by proginosko** [comment]
I would have to rewrite a lot of code to make this a _per-set_ option. It would be easier to have a general option like "Treat unfocused browser windows as focused" (which would have the same effect, but for all block sets).

How would that do?

**Comment by woj-tek** [comment]
I think that having this as general option would be more than enough.

**Comment by proginosko** [comment]
General option "Treat browser windows as always focused" added in release version 1.0.8.
