### ISSUE TITLE
setting page to grayscale doesn't happen automatically

### ISSUE THREAD

**Issue by Crare** [proginosko/LeechBlockNG#492]
I have to click on the LeechBlock-plugin in my browser-top-navbar, after that the page turns to grayscale. tested with youtube.
setting the tab to immediately to close works, but I want it to go grayscale when timer runs out or the website opens after timer has run out.

**Comment by proginosko** [comment]
Go to **about:addons** > LeechBlock NG > Permissions and check that "Access your data for all websites" is selected.

**Comment by Crare** [comment]
ok that fixed it. Thanks!
