### ISSUE TITLE
Missing some features of old Leechblock...

### ISSUE THREAD

**Issue by mygithuber** [proginosko/LeechBlockNG#5]
Hello,
I am missing some features of outstanding old Leechblock v1.0.9:
- Load list of sites from url
- Access control features (password, hiding options...)

Is it not implemented?
Thx + regards!

**Comment by proginosko** [comment]
These are not implemented yet. Access control features are at the top of my list, so look out for those soon. Note that you do already have the option to disable the options for a particular block set when those sites are blocked (look under Advanced Options). It won't be possible to implement the option to hide LB in the Add-ons Manager due to new restrictions on what extensions are allowed to do.

As for the "Load from URL" option, I'm not sure if/when that will be implemented. I don't get the impression there's much demand for it, but I may be wrong!

**Comment by mygithuber** [comment]
Access control features: Impatient awaiting it... ;)
Load from Url: In my opinion it is an outstanding feature, because it allows configuration of block set for different computers (or users) in one central file!

Features of old Leechblock v1.0.9 are as far complete as needed, top tool!
Thx + regards!

**Comment by aicoutos** [comment]
- Load list of sites from url (2)
I need it! It's so practical write a external file and backup it. I trust in plain text format, i don't trust in proprietary backup formats.

**Comment by proginosko** [comment]
I hear ya! I will make sure that gets implemented in a future release.

**Comment by proginosko** [comment]
Access control features implemented in v0.5 (just released).

**Comment by mygithuber** [comment]
Access control features are working like expected, even the import/export function too. (FF-57,Win7-64) 
Thank you!!
Last feature thing I am missing: "Load list of sites from url"
Really nice tool, thanks once more!

**Comment by proginosko** [comment]
"Load list of sites from URL" is implemented in v0.7b1 (beta version) so give it a try:

https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/versions/beta

**Comment by aicoutos** [comment]
good work @proginosko ! with scheme http:// works fine but don't with scheme file:///. acording new security policy this is not a problem. thank you =)

**Comment by aicoutos** [comment]
sorry @proginosko , i found a bug. the import system it's ok but the block system don't work. the information is loaded but isn't applied.

**Comment by proginosko** [comment]
@aicoutos Did you save options after importing? You need to do that to apply the imported options.

**Comment by aicoutos** [comment]
@proginosko yes, i have saved and restart the browser and nothing happened. the URLs list remains but don't work.

**Comment by proginosko** [comment]
@aicoutos Is this an issue with the "Load list of sites from URL" option? If not, please start a new issue.

**Comment by aicoutos** [comment]
@proginosko ok, but still missing some features of old Leechblock #22

**Comment by proginosko** [comment]
@aicoutos Which features are you missing?
