### ISSUE TITLE
Fragment identifiers stripped from URLs

### ISSUE THREAD

**Issue by benburrill** [proginosko/LeechBlockNG#50]
To reproduce:
 * Put a delay page on en.wikipedia.org
 * Visit https://en.wikipedia.org/wiki/Fragment_identifier#Examples
 * Once the delay is finished, the fragment identifier is stripped from the url you are redirected to.

**Comment by proginosko** [comment]
Go to Advanced Options for that set and uncheck "Ignore fragment (hash part) when checking URL".

**Comment by benburrill** [comment]
Okay, that fixes it, but that option shouldn't affect the URL passed to the delay/block pages, it should only affect URL matching.

**Comment by proginosko** [comment]
Yes, you're right. In the early versions of LB the hash part was always stripped off for reasons related to page refreshes. The "Ignore fragment" option was added more recently. But yes, the hash part really ought to be passed always. I'll change that.

**Comment by benburrill** [comment]
Did you close the issue on accident?  You haven't pushed any commits to github since before you closed it.

**Comment by proginosko** [comment]
Not accidentally, but prematurely. 😃 

I've simply been too swamped with Real Life lately to work on LB. I will try to carve out some time over the weekend.
