### ISSUE TITLE
Leechblock stopped working on Iceraven browser since v1.6.6

### ISSUE THREAD

**Issue by lesar8** [proginosko/LeechBlockNG#505]
Hi, i use Iceraven browser on Android which allow to install Firefox addons. Leechblock addon works fine for me for more than a year, but since v1.6.6 it's stopped block pages. The website (which match the block rule) never finish loading and will not redirect to the block page. Issue happens with all the sites matching the block rule.

Hope for your helps, thank you.

**Comment by proginosko** [comment]
Can you open the options page?

I don't know anything about the Iceraven browser. You might have to uninstall and reinstall the extension. If you can access the options page, then you can export your settings before uninstalling.

**Comment by proginosko** [comment]
Can you export your options as a text file and email it to me (leechblockng@proginosko.com)?

**Comment by lesar8** [comment]
> Can you export your options as a text file and email it to me ([leechblockng@proginosko.com](mailto:leechblockng@proginosko.com))?

Hi, just PMed you.

**Comment by proginosko** [comment]
Thanks. I don't see any obvious problem with your settings. I'm not sure what more I can do at this point, since I've never used Iceraven and I'm not sure what debugging options it provides. Am I right that v1.6.5 worked fine with it? Can you revert to that version?

**Comment by lesar8** [comment]
Unfortunately it's not possible to revert to an older version once it's been updated. Iceraven only allows to install addons from Firefox's addon store, the installation from the XPI file is not possible..

**Comment by proginosko** [comment]
That's too bad. I can't think what changes in v1.6.6 would have broken it. There were no changes to the core functionality.

Is there a reason for using Iceraven rather than Firefox?

**Comment by lesar8** [comment]
It's basically Firefox with Mozilla's proprietary stuff removed and some other neat privacy tweaks. There is no significant different in performance as i can tell. So well, I guess it's time to switch back to Firefox..

**Comment by proginosko** [comment]
Would you mind trying it with Firefox for Android and letting me know whether it blocks correctly? That would help to narrow down the source of the problem.
