### ISSUE TITLE
Leechblock very unreliable

### ISSUE THREAD

**Issue by blex-max** [proginosko/LeechBlockNG#508]
Firefox on mac Sonoma 14.7.1 - I'd say leechblock works about 30% of the time. The other 70% it does nothing. This is kind of functional, as after a few clicks it kicks in, but it's not great. This is regardless of my referer and keywords as far as I can tell. I've attached screenshots of my options, but I haven't modified them in a way that would obviously cause this imo. Also, perhaps a "dump settings to json" or similar might be useful for submitting these? Thanks!

<img width="803" alt="Screenshot 2024-11-19 at 20 29 15" src="https://github.com/user-attachments/assets/9d88b2d2-e96b-4722-a440-f150fba0549a">
<img width="818" alt="Screenshot 2024-11-19 at 20 29 59" src="https://github.com/user-attachments/assets/7d438eb2-ffaa-436a-b6c9-ef41f4928e53">
<img width="808" alt="Screenshot 2024-11-19 at 20 30 27" src="https://github.com/user-attachments/assets/e79b4842-6af8-4547-96d3-26f8938dc71d">

**Comment by blex-max** [comment]
Actually, on further investigation, this does seem to be related to my referrers/keywords - it works much better without them. This is unfortunate as it's my main attraction to leechblock!

**Comment by blex-max** [comment]
ok, on further experimentation - keywords as allow conditions don't seem to work how I expected them to. I think they're bugged, but I can't be certain.

This works fine:
+reddit.com/r/modular
+reddit.com/r/synthdiy
reddit.com

I'd like to be able to use a referrer allow condition like
>google.com
I assumed that would allow only the first page referred from, and would block subsequent pages on clicking links - however, it does not, instead allowing all subsequent browsing. Is that expected behaviour?

**Comment by proginosko** [comment]
Explanations of keywords and referrers here:

https://www.proginosko.com/leechblock/faq/keywords/

https://www.proginosko.com/leechblock/faq/referrers/

LB relies on the browser accurately reporting the referring site, but unfortunately that doesn't always happen. In theory, only the first page referred from the site should be blocked/allowed.

**Comment by blex-max** [comment]
to be clear, with keywords as allow conditions:

> reddit.com
> ~modular

The above basically stops reddit.com being blocked reliably, regardless of whether the keyword is in the URL. I don't think thats supposed to be happening.

The referrer limitation makes sense, thanks for explaining

**Comment by proginosko** [comment]
LB doesn't look for keywords in the URL, only in the text of the page.

To allow based on keywords in the URL:

> reddit.com
> +reddit.com/**modular

**Comment by blex-max** [comment]
Understood - possibly that could be emphasized in the doc as that's I don't think that's the natural interpretation (though I see the intention). Many thanks!

**Comment by proginosko** [comment]
Good suggestion. I've added a clarification to the FAQ page.
