### ISSUE TITLE
Add website to blocked list without unlocking the settings 

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#51]
I blocked the settings to further prevent me from circumventing the block but today I ran into an issue - I wanted to add a website to the block list and... I had to type the long random string to actually be able to add it (a but against the idea).
It would be nice if it were possible to add an URL to the list without unlocking the preference - it could be either as an option in the current menu (add website to blocked listed -> select block rule) or while opening the preferences show "just add website" or something like that and all settings will be inactive and on the rule tab you would have button "add to list"

**Comment by proginosko** [comment]
Actually, this feature is already available. Right-click either on the LB toolbar button or on the web page.

**Comment by woj-tek** [comment]
Wouldn't have thought to search that (as usually addons don't put much there). However I would still ask to move this to the bubble menu that opens up after normal click as... on mobile firefox it's impossible to access the context menu of the addon and the bubble menu (with options, statistics, etc) works just fine. And moreso - typing 128 random characters on mobile to add a website it's a bit tedious ;)

**Comment by Frivolous2** [comment]
"Add site" has no reason to be hidden in an additional menu in my opinion - since that menu is exactly the same as the popup, with the exception that it has "Add site", it's clearly not a problem of too many options that are better hidden from the main popup. 
Getting punished for wanting to do the right thing is not only annoying, but runs counter to the very purpose of the extension itself.

**Comment by proginosko** [comment]
To be clear: you want the Add Site options to appear in the popup menu from the toolbar button. Correct?

**Comment by woj-tek** [comment]
Yes, exactly.

**Comment by proginosko** [comment]
Closing this for now. Feel free to post fresh feature request under Discussions/Ideas.

**Comment by codethief** [comment]
@proginosko That's too bad. I still think this feature would be really useful.

**Comment by proginosko** [comment]
To be clear, I'm not rejecting the request! I'm just moving all the 'live' feature requests to Discussions/Ideas. The original request changed during the course of this thread; that's why I suggested posting it as a fresh request under Discussions/Ideas.

**Comment by proginosko** [comment]
Added in version 1.6.4.
