### ISSUE TITLE
Block webiste after the time is up

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#52]
Currently, when the time is up it only shows "0:0" but you can still continue reading. It's easy to circumvent the blocking but opening multiple tabs from the main website and then continue at a leisure.

**Comment by proginosko** [comment]
Have you checked the option "Immediately block pages on these sites once blocking conditions are met"?

**Comment by woj-tek** [comment]
Ah! That would be it! Thanks :-)

**Comment by proginosko** [comment]
You're welcome. :)
