### ISSUE TITLE
Active tab option not working well on Firefox Mobile

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#524]
I use "count only if tab is active" ob my desktop and it works well but on Firefox Mobile the timer is still going if the page is not visible (either other tab open or browser in the background).

I tried searching for similar issue but didn't find anything for mobile. 

Not sure if it could b3 fixed with android limitations...

**Comment by proginosko** [comment]
Thanks. This is a known issue. Working on a fix...

**Comment by proginosko** [comment]
See #81, #418, #495.
