### ISSUE TITLE
Flexible scope when activating temporary overrides?

### ISSUE THREAD

**Issue by wbskr** [proginosko/LeechBlockNG#54]
First of all thank you for the awesome extension.

I was wondering whether you can implement a feature that would be very convenient to reduce unintended procrastination when using temporary overrides. The issue is that right now the temporary override applies to block sets, so it lacks the low-level granularity of choosing a specific website or a specific url. Let me make this clearer with an example. Say I want to learn car driving, so I decide to watch a bunch of Youtube videos about using the clutch, braking, parking, driving uphill, driving with traffic, etc. Sounds like a very productive way of using Youtube. Therefore, I activate the temporary override for 2 hours, which applies to all block sets, including the one with Youtube.com. So far so good, I can watch the videos and learn about driving, great! ... But! since I have 2 hours of free Youtube, the temptation to watch OTHER videos arises, so most of the 2 hours of productivity end up being wasted in other videos. 

Moreover, since the temporary override applies to block sets, and since there is a maximum of 6 block sets, it's very likely that the temporary override also unlocks other websites, say Facebook. So back to my example, that would mean I have 2 hours of free Facebook, although my original intention was to have access to the driving videos on Youtube and nothing more.

Therefore, it would be much better if the application scope of the temporary override could be set flexibly. For example, being able to choose between:

- The current url (the url of the currently focused tab). For example, if I'm standing on https://www.youtube.com/watch?v=ASx4JtLvx_M, make the temporary override apply only to this specific url.
- The current website. For example, if I'm standing on https://www.youtube.com/watch?v=ASx4JtLvx_M,  make the temporary override apply to the whole https://www.youtube.com domain.
- One/some/all block sets the current url/website belongs to.

Additionally, it would be even better to complement this with a flexible way of inputting time spans for the temporary override. Let me show you a possible use case to illustrate why:
- I go to Youtube.com and activate a temporary override with Youtube.com as its scope, for just 5 minutes. So I have full access to Youtube but for 5 minutes only, which is a limited but reasonably enough amount of time to quickly search for car driving videos.
- Then, I write down all these car driving videos urls on a .txt file for further use.
- Then, for each car driving video, I open its url and activate the temporary override for that specific url for, say, 30 minutes.

Thus, after the first 5 minutes, I would no longer have access to Youtube.com as a whole, but I still would retain access to the specific car driving videos. In other words, the idea is to have a brief, website-scope temporary override of a few minutes to quickly search urls of interest, and then activate url-scope temporary overrides for each of the safe urls previously found, so that I would no longer be tempted by other, "unsafe" video urls. This is a Youtube example, but this can certainly be generalized to other domains where there is a mixture of productive and non-productive content, and you just want to forbid access to the latter.

UPDATE: from an implementation and performance point of view, I think using a Trie (https://www.youtube.com/watch?v=zIjfhVPRZCg) should work, you can quickly search a url in the Trie and detect if any rules at the domain level or with the full url are active for the given url.

**Comment by wbskr** [comment]
@proginosko, I know this feature request is probably not very high in your priority list, but at least I would like to know what you think about it.

**Comment by proginosko** [comment]
Sorry for the delay in replying. I do think this is a reasonable suggestion, although it would take some work to implement well. I have added it to the requested feature list.

**Comment by proginosko** [comment]
I'm closing this, because since version 1.3 the user has the option to specify the override duration when the override is activated.
