### ISSUE TITLE
Does not block youtube

### ISSUE THREAD

**Issue by Anton-Velikodnyy** [proginosko/LeechBlockNG#55]
Software: Ubuntu 16.04, Firefox version 58.0.2
Problem: Attempting to block youtube with `https://www.youtube.com/`, `*youtube*`, `*youtube.com` , and `*youtube.com*` does not block the website.
Settings: 
I have set the hours 1700-2400 
No time limit is set
OR is used for  is used for how its is set
Every day of the week
Url is given with  file path
Checkmarks: 
- Immediately block pages on these sites once blocking conditions are met
- Count time spent on these sites only when browser tab is active
- Block only first accessed page of site when delaying page is used 
Delay is set to 60 seconds

Thing I have tried:
Blocked twitter and facebook: those work
Different hours: did not work with youtube
Manualy lockdown: did not work with youtube
Upgrade firefox: already at newest version

**Comment by Anton-Velikodnyy** [comment]
I have also tried the redirect url with default for youtube block, but that did not work with only youtube

**Comment by proginosko** [comment]
Are you using a custom URL for the blocking page? Does it point to a local file?

**Comment by proginosko** [comment]
I just tested blocking youtube.com with FF 59.0.2 (Win10) and it works fine. Please export your options to a text file and email them to me (leechblockng@proginosko.com).

**Comment by proginosko** [comment]
I just tested blocking youtube.com with FF 59.0.2 (Win10) and it works fine. Please export your options to a text file and email them to me (leechblockng@proginosko.com).

**Comment by Anton-Velikodnyy** [comment]
The local file works when blocking twitter or facebook

**Comment by Anton-Velikodnyy** [comment]
where would the options be located?

**Comment by proginosko** [comment]
Thanks for sending your exported options. I tried them and YT was not blocked for the reason I suspected ("Illegal URL" error appears in the console). I changed the URL to the default blocking page and YT was blocked immediately. Not sure what to say!

**Comment by Anton-Velikodnyy** [comment]
Ok, got it to work without the custom image. Would be nice if I knew you couldn't do personal files.

**Comment by proginosko** [comment]
You can use personal files, but they need to be web hosted (http protocol). Dropbox would be one workaround.
