### ISSUE TITLE
Counter visible in print (preview)

### ISSUE THREAD

**Issue by real-or-random** [proginosko/LeechBlockNG#56]
The counter should not be displayed when printing.

(Currently, the style is applied inline but note that inline styles cannot have media rules.
https://stackoverflow.com/questions/9808233/is-it-possible-to-put-css-media-rules-inline?rq=1 )

**Comment by proginosko** [comment]
Good catch. Yes, this needs to be fixed.

**Comment by proginosko** [comment]
Workaround added in v0.9.3: double-click on countdown timer to remove it from page. I will work on a full fix for a future release.
