### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#57]
Would it be possible to somehow have dark theme on in the settings/on the count screen?

**Comment by Metaception** [comment]
I personally think a dark settings page would be a bit excessive, you really shouldn't be using the settings page often enough for this to be an issue. It should be a set and forget thing, YMMV ofc.

I do think a dark countdown timer would be nice though. I prefer dark themes for browser UI and light themes for web pages, so this would keep Leechblock consistent with the rest of my theme.

**Comment by qazip** [comment]
I would also like a dark page for when a page is blocked.

**Comment by proginosko** [comment]
Version 0.9.9 includes some theme options. Enjoy!
