### ISSUE TITLE
Leave site icon and text in tab

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#59]
Hi,
I started with "block by night" rule of all sites (works great) but combined with "block immediately" it, well… blocked immediately all sites and in the morning I ended up with:
https://www.dropbox.com/s/of6iwi3urkq423f/leechblock.png?dl=0

Two problems:
* sites weren't unblocked automatically after period which I quite ok - I don't want to load all of them (I use auto-tab unloading so Firefox don't use to much resources)
* I had no idea which site is which - adding at least domain to the tab name (i.e. "Site Blocked: google.com) would be handy

**Comment by proginosko** [comment]
Version 0.9.8 includes an option to automatically attempt to reload a blocked page every __ seconds. Also, the name of the block set is now shown in the title of the blocking page.
