### ISSUE TITLE
Time left in blocklist deceases linearly with # of blocked sites loaded

### ISSUE THREAD

**Issue by Metaception** [proginosko/LeechBlockNG#6]
When LeechblockNG is set to count time on loaded tabs, it seems to count each one separately.

With two tab it decreases 2s every second, with three tabs 3s, etc.

IIRC the old Leechblock had the same issue once, but web-extensions might be different.

Anyways, nice job! Leechblock is super useful to me, thx for the speedy port!

**Comment by proginosko** [comment]
Ah, yes. Same bug as before! I'll have to add that to the to-do list...

**Comment by proginosko** [comment]
This should be fixed in version 0.5.1.
