### ISSUE TITLE
Can't block subdomain with # sign

### ISSUE THREAD

**Issue by lyuboy** [proginosko/LeechBlockNG#64]
Hey, I installed it today and found it really useful, just having some trouble with the subdomains in Gmail.

In Gmail I have created a filter for all the emails coming from Facebook to be inserted inside a label that I have called Facebook (https://mail.google.com/mail/u/0/#label/Facebook)

I would like to be able to access Gmail, but block the access to the Facebook label during the day

I can completely block Gmail, but can't make it to allow to open Gmail and block clicking the filter for the Facebook label (the one linked above)

I also tried only blocking (https://mail.google.com/mail/u/0/#label/Facebook) but that doesn't work. I guess it has something to do with the # symbol

Any help would be appreciated

PS: I tried blocking `**Facebook** , *Facebook* , **+Facebook** ` and other variations of it again without any success

**Comment by lyuboy** [comment]
So I managed to make facebook be blocked, but I can't block the subdomain in Gmail for the facebook label (https://mail.google.com/mail/u/0/#label/Facebook)

I can completely block Gmail, but can't make it to allow to open Gmail and block clicking the filter for the Facebook label (the link above)

Any help would be appreciated

**Comment by proginosko** [comment]
By default LB ignores the hash part of URLs. If you don't want that behavior, uncheck the option "Ignore fragment (hash part) when checking URL" under Advanced Option for that block set.

**Comment by lyuboy** [comment]
That worked! Thank you very much :)
