### ISSUE TITLE
Reset time not on midnight

### ISSUE THREAD

**Issue by macius702** [proginosko/LeechBlockNG#67]
I'd like to reset daily allowed time for a website at say 3 a.m.

**Comment by proginosko** [comment]
Version 0.9.8 includes the option to specify an offset (in hours) for the time limit period (see under Advanced Options).

**Comment by Keavon** [comment]
@proginosko I can't seem to find this, has it been moved or something? It seems like this should be a common enough use case that it should also be made much more discoverable.

**Comment by proginosko** [comment]
Go to the relevant block set and click the button "Show Advanced Options" at the bottom. You'll see the option "Offset time limit period by ____ hours".
