### ISSUE TITLE
Access Code can be copied from Inspect Element

### ISSUE THREAD

**Issue by Metaception** [proginosko/LeechBlockNG#68]
While the access code cannot not be copied from the web page, using the inspect element context option lets you easily copy the code and paste it regardless of the length/complexity.

I believe the only way to stop this would be to use an image or stop pasting from working on the options/override page.

I know this might be going into the excessive territory, but I thought I should let you know.

**Comment by Erudition** [comment]
Clever!

**Comment by proginosko** [comment]
Version 0.9.9 includes option to display access code as image. Try it out!
