### ISSUE TITLE
Blocking time periods in UTC?

### ISSUE THREAD

**Issue by paulstodghill** [proginosko/LeechBlockNG#70]
I found that LeechBlockNG on Firefox blocks sites earlier than I expected. I have tracked down the "problem" to the fact that the blocking time intervals are interpreted as UTC times, and not local times. I have tried this on both Ubuntu 18.04 and MacOS 10.12 using Firefox 60.0.2. Is this expected behavior?

If so, could you please change the message to, for example, "Enter the time periods in [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) within which to block these sites (optional):" and perhaps add an entry to the FAQ?

If not, please consider a request to change the code to use localtime instead of UTC. I believe that this would be least surprising behavior.

If this is already documented somewhere, I missed it and I apologize.

Thank you.

**Comment by paulstodghill** [comment]
I am in Eastern (US) (EDT).

~~~~
>> var date = new Date();
undefined
>> date.getHours();
13
>> date.getMinutes();
41
~~~~

~~~~
$ date
Fri Jun 22 09:42:24 EDT 2018
$ date -u
Fri Jun 22 13:42:26 UTC 2018
$ uname -a
Darwin sharon 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64 i386 Macmini7,1 Darwin
sharon$
~~~~

**Comment by proginosko** [comment]
Hmm. Looks like a Firefox bug, doesn't it?

**Comment by proginosko** [comment]
Try this in the console:

``new Date().toString();``

**Comment by paulstodghill** [comment]
It's definitely a Firefox issue.

Firefox 60.0.2:
~~~~
>> new Date().toString();
"Fri Jun 22 2018 14:03:13 GMT+0000 (UTC)"
~~~~

Chrome 67.0.3396.87:
~~~~
> new Date().toString();
"Fri Jun 22 2018 10:04:01 GMT-0400 (Eastern Daylight Time)"
~~~~

**Comment by proginosko** [comment]
Yes, Firefox is messed up. Not sure what to suggest!

**Comment by paulstodghill** [comment]
It's not a bug with Firefox; it's a feature. No, really, it is. :-/

If the config setting `privacy.resistFingerprinting` is toggled to TRUE, then it would appear that all "local" javascript times are reported in UTC.

Kinda makes sense when you think about it.

I could specify block times in UTC, but I will have to change them twice a year (standard/daylight savings). So, feature request: allow the TZ to be specified in the block times. I don't have a better idea.

**Comment by paulstodghill** [comment]
> What return values do you get for the following?
> 
> Date()
> new Date(Date()).toString()

With `privacy.resistFingerprinting` toggled TRUE,

~~~~
>> Date()
"Fri Jun 22 2018 14:28:37 GMT+0000 (UTC)"
>> new Date(Date()).toString()
"Fri Jun 22 2018 14:28:42 GMT+0000 (UTC)"
~~~~

With `privacy.resistFingerprinting` toggled FALSE,

~~~~
>> Date()
"Fri Jun 22 2018 10:28:52 GMT-0400 (EDT)"
>> new Date(Date()).toString()
"Fri Jun 22 2018 10:28:54 GMT-0400 (EDT)"
~~~~

**Comment by proginosko** [comment]
Mystery solved. That's a pain to work around though.

**Comment by paulstodghill** [comment]
Ok, instead of adding TZ's to block strings, how about adding a single "Override default timezone" setting under the "General" tab?

**Comment by paulstodghill** [comment]
Fair enough. Thanks for your consideration.

**Comment by proginosko** [comment]
Good to know!

**Comment by thiswillbeyourgithub** [comment]
Hi,
1 year and a half later and still no improvement from firefox. I am very sad to not be able to use this addon.
Consider me very interested by this feature.
Thanks!

**Comment by ChristopheBougere** [comment]
Same issue here, it would be great to have information about the used timezone so you can easily adapt settings

**Comment by Lezcano** [comment]
Same!

**Comment by proginosko** [comment]
I hear you guys. I'm thinking of adding an option to specify an arbitrary clock offset in minutes (either +ve or -ve). So if the browser's clock is off by 4 hours, for example, you can just enter "240" to correct it. Would that work?

**Comment by Lezcano** [comment]
That would be great!

**Comment by proginosko** [comment]
Here's a beta version with the clock offset option (under General options):

https://www.proginosko.com/files/lbng/leechblock_ng-1.0.8b1-an+fx.xpi

Give it a test drive and let me know whether it does the job. (Note that if you do install it, you'll need to _manually_ update to the next release version when it appears.)

**Comment by proginosko** [comment]
Added in release version 1.0.8.

**Comment by adam-sroka** [comment]
Thank you so much! You can't imagine how much mental arithmetic converting time zones you saved me from.

**Comment by punyidea** [comment]
I'm not sure if this is related. I recently changed timezones and my laptop seemed to be restricting website access based on the previous timezone. The issue only fixed itself after I restarted my machine.
