### ISSUE TITLE
Stopped blocking

### ISSUE THREAD

**Issue by Fyka2** [proginosko/LeechBlockNG#71]
I haven't done any changes to my blocks but it suddenly stopped blocking sites. How can it be possible?, it only counts time and doesn't block when I'm out of limits and doesn't block while forbidden periods. Thank you for support in advance!

**Comment by proginosko** [comment]
Please export your settings to a text file (Options > General > Export) and email it to me (leechblockng@proginosko.com) so I can investigate. Also provide some specific examples of URLs you think should be blocked but are not.

**Comment by proginosko** [comment]
Thanks for sending your settings. Glad we could resolve the issue.

For the record: the problem was using ``about:home`` as the URL for the blocking page.
