### ISSUE TITLE
Automatic save after import, or confirm before discard.

### ISSUE THREAD

**Issue by NisJorgensen** [proginosko/LeechBlockNG#72]
I would like to suggest that "import options" automatically saves the options after the import. 

I realize that there could be a argument for NOT doing this. Thus, alternatively or additionally, I would like to suggest that closing the "options" window while there are unsaved modifications issues a warning message ("you have unsaved changes, are you sure you want to ...")

**Comment by proginosko** [comment]
Reminder message added in version 0.9.8.
