### ISSUE TITLE
Exporting settings doesn't work on mobile (Android)

### ISSUE THREAD

**Issue by codethief** [proginosko/LeechBlockNG#73]
When I click the "Export" button nothing happens. I only see a "file upload" button next to "import".

I suppose this is because downloading on Firefox for Android works differently than on, say, Linux? (As on Android downloading files doesn't involve selecting a path using a "Save as" dialog.) If so, could you possibly provide a clickable download link for the exported `settings.json`?

**Comment by proginosko** [comment]
Thanks for reporting this. Yes, it's a bug. I didn't realize FF for Android doesn't (yet?) support a file picker for downloaded files. I will try to fix it in the next release.

**Comment by proginosko** [comment]
Fixed in version 0.9.4.

**Comment by sojusnik** [comment]
Exporting doesn't work with v.1.1.1 on Firefox 94.1.2 on Android 12.

Clicking on the export button does nothing.
