### ISSUE TITLE
site impossible to block

### ISSUE THREAD

**Issue by zortag** [proginosko/LeechBlockNG#74]
Hello,
I'm trying to block this site

https://it.shein.com/Popads-IT-Swimwear-20180312-Y-D15-vc-61297.html?utm_source=popads.net&utm_medium=cpm&url_from=popadsit_20180402_Swimwear

but everything I do not works. I also analyzed the page source and the hystory and I blacklisted everything. I checked the page loading sequence and locked everything, from the single domain to the complete URL but nothing worked. I'm good trained to configure Leechblock and I keep online a blacklist page for friends, I'm not a newbie. There is something that bypass the Leechblock code in the page or I'm less expert I was thinking?

I locked:

*.ltwebstatic.com
*.shein.com/*
it.shein.com
it.shein.com/*
ltwebstatic.com

and all parent ad-laucher pages.
Locking the ad-launchers works since they are not changed (usually 1 week) and every other ad page opened will be locked without problem. 
The only page I can't lock is that damn shein.com, and sometimes i'm submerged by 7/8 of that s**t back the main Firefox page.
I never tryied in other browsers like Chrome or Edge and I know Firefox lacks is some situations.
I can accept to change my default browser at this time because the issues starts to be too many. I accept advice

**Comment by proginosko** [comment]
I created a test block set with only it.shein.com in the list of sites and that page is blocked immediately for me. So I'm not sure what the problem would be. Two things you could try:

1. Open Firefox's browser console (Ctrl+Shift+J). Clear the console then try to access that site and see if any error messages appear in the console. Do it a few more times and see if the same error messages appear. If they do, post them here.

2. Export your options to a text file (Options > General > Export) and email them to leechblockng@proginosko.com. I'll take a look and see if there's an issue with your configuration.

**Comment by proginosko** [comment]
Are you using about:home as your blocking page? If so, that's a known issue (Firefox bug). Try changing it to a different URL.

**Comment by zortag** [comment]
sorry i not answered before but i had no time. i'm using a page from my domain as blocking page. that page simply self close immediatly. 
my exported option file can be readed [here](https://pastebin.com/PuyQGtMe)
nothing useful in the firefox console

**Comment by proginosko** [comment]
I looked at your exported options, but I see nothing except the default settings.
