### ISSUE TITLE
Import from sync storage lost days on which to block sites

### ISSUE THREAD

**Issue by benburrill** [proginosko/LeechBlockNG#76]
When I imported settings from sync storage, I found that the "Select the days on which to block these sites" checkboxes got unchecked for all the block sets.  I had to manually check them all to match the settings page where I exported the settings from.  I have not tested whether this happens if you load from a file.  I thought I successfully loaded from a file in the past, but I might be wrong.

**Comment by proginosko** [comment]
Good catch! Yes, I screwed up. I'll get that fixed ASAP.

**Comment by proginosko** [comment]
Fixed in v0.9.7.
