### ISSUE TITLE
Timer not visible (mostly od reddit)

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#79]
LeechBlockNG 0.9.7
Firefox 62.0.3 (64-bit)

I started using LeechBlockNG again after a while and it works well (I just skipped using "block all rule, which messed up my session and I ended up loosing tabs) with one exception: for some reason, quite often I don't see timer on reddit - I'm not sure if it's only not shown or it's not working (most likely the latter).
Statistics says:
`Time Left in Limit Period: 00:00:00`

It looks like the problem affects all sites from the group.

Settings look fairly normal: https://www.dropbox.com/s/fhobiuutrbnpxwb/LeechBlockNG.png?dl=0

**Comment by woj-tek** [comment]
This is not valid, it was simply my misunderstanding of how the plugin works.
I set the rule to "delayed.html?$S&$U", with my understanding being:
* Upon opening those page show me delay page, afterwards track spent time.
* When the time's up, block the website completely

Currently, with `delayed.html?$S&$U` it works by opening the page normally and then I can navigate it without any limitation, which is kinda bad (I can wait configured time and then spend half a day on reddit...) so the only valid option is to use `blocked.html?$S&$U` (which would count the time and then block the page permanently)

----

bottomline, it would be great to have an option, which is kinda merger between blocked and delayed - delay all entries to the page (this would fall under "Block only first accessed page of site when delaying page is used") and then count the time spent. If the time spent is greater then limits then block the page completely under subsequent open timeframe.

**Comment by woj-tek** [comment]
I'll try that.

I think this is somewhat related to  #60 -- basically nesting time rules for particular set of websites.

**Comment by proginosko** [comment]
This should be fixed in version 1.0.7.1. Make sure the block-after-time-limit set _precedes_ the always-delay set in the order of sets.

**Comment by woj-tek** [comment]
Seems to be working fine now - thank you! :-)
