### ISSUE TITLE
It's not shutting down sites without refresh or loading another link.

### ISSUE THREAD

**Issue by nextgenthemes** [proginosko/LeechBlockNG#8]
I think I even had this issue with the old addon (at some point).

When the counter reaches 0 I still can stay on that site (watching the counter at 0), and if its a Ajax site like YouTube then I can basically continue to watch stuff. Even after clicking links. As soon as I refresh the page or try to open youtube.com or any other site from that blocklist it will be blocked but only then.

I hope this is a bug that is easy to fix.

**Comment by proginosko** [comment]
Have you selected the option "Actively block pages on these sites once time period is entered or time limit is exceeded"? If not, you should. Otherwise, report back here!

**Comment by nextgenthemes** [comment]
Ah sorry I missed that option, awesome! Thanks NG works perfectly for me!
