### ISSUE TITLE
[FR] Safari version?

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#83]
Hi,
this is more of a question - do you plan to release Safari version as well?

**Comment by proginosko** [comment]
Sorry, Safari does not support the WebExtensions API on which LB is built.

**Comment by woj-tek** [comment]
Thanks. I did a bit of *DuckDuckGoing* and found an alternative (WasteNoTime - if someone would endup looking for same problem and end-up here)

**Comment by justauserid** [comment]
> Thanks. I did a bit of _DuckDuckGoing_ and found an alternative (WasteNoTime - if someone would endup looking for same problem and end-up here)

Anyone planning to try this - this doesn't work since Safari 13 (current is 14). Developer has mentioned that "may change" with Big Sur. But it doesn't work on Big Sur either.

So no there's essentially no alternative for Safari.

**Comment by woj-tek** [comment]
tbh, I just gave up on extensions in safari altogether as their handling of them is just utterly broken and every (even maintenance) update everything would just disappear...

**Comment by justauserid** [comment]
> tbh, I just gave up on extensions in safari altogether as their handling of them is just utterly broken and every (even maintenance) update everything would just disappear...

That is true. And time and again they have proved they would do things that just doesn't make sense technically, practically, or normally. But they still sell lots of devices so apparently they have stopped giving two hoots about it.

As of now I am just using SelfControl.
