### ISSUE TITLE
[bug] High energy impact

### ISSUE THREAD

**Issue by woj-tek** [proginosko/LeechBlockNG#85]
Latest Firefox sports new `about:performance` and after playing a bit with it it turned out that LeechBlockNG occupies relatively high position there:
﻿https://www.dropbox.com/s/rlzbkndbx14cnw8/leechblock-energy_impact.png?dl=0

**Comment by proginosko** [comment]
This shouldn't be surprising. LB typically processes all open tabs every second to keep track on time spent and to check whether any blocking conditions have been met. So it's going to be using more processing power relative to add-ons that are only triggered by user input events. The more tabs are open, the more processing there will be. I've been monitoring LB in `about:performance` and on my machine the "energy impact" (!) hasn't ever been more than "medium". YMMV...

I wouldn't consider this a bug. It's like complaining that your Ferrari has low MPG. :wink:

**Comment by woj-tek** [comment]
> This shouldn't be surprising.

Disclaimer: had no idea how LB works internally…

> LB typically processes all open tabs every second to keep track on time spent and to check whether any blocking conditions have been met. So it's going to be using more processing power relative to add-ons that are only triggered by user input events. The more tabs are open, the more processing there will be.

Why though? This seems kinda inefficient. From the quick check there seems to be an API that allows listening on tab events: created/activated/destroyed (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) so instead of checking every tab you could act on those events, which should greatly reduce energy impact.
What's more (not remember if there is an option to only track active tabs or not, and I made opening options PITA ;) ) but even you are checking all tabs (not only active one) then you should most likely attach a timer/timeout when they are created and match condition?

Yes, I'm a tab hoarder so this bit of information about checking all the tabs every seconds would explain a couple of things :-)

>  I've been monitoring LB in about:performance and on my machine the "energy impact" (!) hasn't ever been more than "medium". YMMV...
> 
> I wouldn't consider this a bug. It's like complaining that your Ferrari has low MPG. 😉

European here - "low MPG" threw me off at first - "eats lots of liters per 100kms" ;)

At any rate - I'm sporting `2,4 GHz Intel Core i7` which is not the most sluggish machine, but - I would love to keep using Firefox when I'm going cordless and have to squeez every wat out of the battery, and for now I'm forced to switch to Safari on that occasions.
Would you consider re-opening this as "Feature request" with further optimization in mind? Just recently uBlock origin author announced porting parts of code to WASM to improve performance so I don't think considering CPU usage is unpopular :-)

**Comment by proginosko** [comment]
LB does listen to those events, but it also has to check tabs at regular intervals to keep track of the time spent on websites. Have you tried selecting the option "Process only active tabs" (Options > General)? Does it improve performance and energy usage for you?

**Comment by woj-tek** [comment]
OK, I checked and I have enabled `Process only active tabs (improves performance when multiple tabs open)` so this should result in lower resource usage.
Is there a way to run some sort of profiler to see hot codepaths?
