### ISSUE TITLE
Timer problems on Waterfox

### ISSUE THREAD

**Issue by ElhemEnohpi** [proginosko/LeechBlockNG#86]
Hi, and thanks for this extension! I just installed it on the latest Waterfox 56.2.6, and have noticed the following problems with the timer and active tabs. I understand if you don't want to support this browser, but if it's a reasonably simple fix, I'd appreciate it!

Tested with a new clean profile and only LeechBlockNG installed:

1. Checking "Count time spent on these sites only when browser tab is active" doesn't do anything. Time still counts down, even when the tab loses focus.
2. If "Process only active tabs" is unchecked, the on-page timer and icon tooltip display of an active tab doesn't update. Time still counts down, but you have to reload the page to update the display.

**Comment by proginosko** [comment]
I'd never heard of Waterfox until you posted this!

I don't have a good solution to this issue right now, since I can't find any documentation for Waterfox. My hunch is that Waterfox doesn't support the windows.onFocusChanged event (or doesn't support it properly). But that's just a first guess.

Does Waterfox have a browser console with an error log? If so, take a look and see if there are any relevant error messages there.

**Comment by ElhemEnohpi** [comment]
Oh, sorry - Waterfox is a fork of Firefox 56, with some recent security patches, for those of us who want to keep using legacy addons. Should be basically the same as Firefox 56.

I didn't notice anything obvious in the browser console. I can take another look.

**Comment by ElhemEnohpi** [comment]
Hi, I tried the latest version (1.0.4), but still no luck with Firefox/Waterfox 56. I still get the error: `Error: Type error for parameter details (Error processing title: Expected string instead of null) for browserAction.setTitle.` once a second, from background.js. Now I get that even when the tab has focus and "process only active tabs" is checked, and I don't see the timer at all.

So I'm stuck on 0.9.7 - it would be great to be able to use the latest version!

**Comment by grahamperrin** [comment]
Also maybe add a `strict_min_version` to the manifest. 

https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#Firefox_(Gecko)_properties

**Comment by proginosko** [comment]
Is this still an issue or has Waterfox caught up with the API?

**Comment by ElhemEnohpi** [comment]
It's still an issue with "Waterfox Classic" the version that's a fork of Firefox 56 and supports legacy XUL addons. It's not really getting API updates, and was never expected to, it just gets some "best effort" security patches and small fixes. There are still lots of people using it, but it's now failing on a lot of things, being several years out of date. There is https://github.com/zakius/Polly that helps with some things. I've moved back to Firefox, though I _really_ miss Session Manager...

The other main version of Waterfox is based on Firefox LTS, doesn't support legacy addons, and probably works fine.

**Comment by proginosko** [comment]
Okay, thanks. I'm closing this, since I don't think it's a live issue.
