### ISSUE TITLE
Keep counting when opening a new tab from a link in a blocked site

### ISSUE THREAD

**Issue by dan-dr** [proginosko/LeechBlockNG#89]
There are some sites like Hacker News that I don't actually spend a lot of time in, but rather open many links which lead me to other random sites, which aren't blocked by LeechBlock... is there a way to make tabs that I open from blocked sites count as blocked sites?

**Comment by nurgasemetey** [comment]
Hello @dan-dr . You can actually limit your hackernews site visit. They included such options in profile settings. 
 
![image](https://user-images.githubusercontent.com/4669437/52562960-2adda000-2e11-11e9-8905-6836bd1fc7fa.png)

**Comment by jordanenglish** [comment]
+1
I've been looking through the Taptalk forums and then came here to try and see if it is being discussed here. I used to like that StayFocusd would continue the timer on new tabs from blocked sites links. Is it just really low on the list? I figured more people would want this feature. I open up Feedly (my RSS reader) and open new tab on articles I want to read. 

Thanks.

**Comment by proginosko** [comment]
The referrer feature should cover this:

https://www.proginosko.com/leechblock/faq/referrers/
