### ISSUE TITLE
Override does not override

### ISSUE THREAD

**Issue by plmayer** [proginosko/LeechBlockNG#92]
I am using Leechblock von Firefox with the absolute default settings; I only entered some URLs (eg. amazon.com) and a blocking time (0800-1600). Blocking works during this time. However, when I click "Override", I get a screen showing that the override is now active until in 5 minutes; but I still cannot access the blocked web sites (I get the usual blocked notice).

**Comment by proginosko** [comment]
Please export your settings to a text file (Options > General > Export) and email it to me (leechblockng@proginosko.com) so I can try to reproduce the issue on my setup. (I know you described the settings here, but I'd like to check them exactly.)

Also, please let me know which OS and version of Firefox you're using. Thanks!

**Comment by proginosko** [comment]
Thanks for the email and sorry for the delay in responding. The solution is to select the option "Allow temporary override for these sites" in the relevant block set. That option exists so that users can be selective about which block sets the override applies to. I know it's not 100% obvious though!

**Comment by plmayer** [comment]
Aha! Thanks. I did look through the options multiple times but this one completely escaped my attention. Sorry! As a suggestion, the override page (which says "Override activated.") might mention that it really wasn't in case the option is disabled.

**Comment by proginosko** [comment]
Good suggestion!
